BEGIN;

ALTER TABLE a_v
    ADD COLUMN IF NOT EXISTS ddd TEXT,
    ADD COLUMN IF NOT EXISTS eee TEXT,
    ADD COLUMN IF NOT EXISTS fff DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS ggg TEXT;

COMMIT;
