package model

// MetaRegistry — de single source of truth voor alle type-metadata.
// Gegenereerd door cmd/codegen — niet handmatig bewerken.


// MetaRegistry is the hardcoded meta model registry.
var MetaRegistry = MetaRegistryType{
	"NatuurlijkPersoon": {
		Typenaam:    "NatuurlijkPersoon",
		Description: "Entiteit A met materiële tijdlijn en onderliggende representaties U, V, W en Rel_A_B.",
		Metatype:    MetatypeEntiteit,
		IsMaterieel: true,
		Kleur:       "#bfdbfe",
		Veldnaam:    "natuurlijkpersoon",
		Padnaam:     "natuurlijkpersoons",
		Factory:     func() Representatie { return &NatuurlijkPersoon{} },
		SliceFactory: func() any { return &[]NatuurlijkPersoon{} },
		Tabelnaam:      "natuurlijkpersoon",
		IDKolom:        "id",
		DBFactory:      func() Representatie { return &NatuurlijkPersoon{} },
		DBSliceFactory: func() any { return &[]NatuurlijkPersoon{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "PersoonsIdentificaties", JSONRolnaam: "persoonsidentificaties", Doeltype: "NatuurlijkPersoon_PersoonsIdentificatie", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Naams", JSONRolnaam: "naams", Doeltype: "NatuurlijkPersoon_Naam", Momentvoorkomen: Meervoudig},
			{Rolnaam: "Burgerschaps", JSONRolnaam: "burgerschaps", Doeltype: "NatuurlijkPersoon_Burgerschap", Momentvoorkomen: Meervoudig},
			{Rolnaam: "Bereikbaarheids", JSONRolnaam: "bereikbaarheids", Doeltype: "Bereikbaarheid", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "NatuurlijkPersoon_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "NatuurlijkPersoon_Einde", Momentvoorkomen: Enkelvoudig},
		},
	},
	"NatuurlijkPersoon_PersoonsIdentificatie": {
		Typenaam:     "NatuurlijkPersoon_PersoonsIdentificatie",
		Description:  "Enkelvoudig gegevenselement van A met formele tijdlijn.",
		Metatype:     MetatypeGegevenselement,
		IsMaterieel:  false,
		GESubtype:    GESubtypeHub,
		DataTypenaam: "NatuurlijkPersoon_PersoonsIdentificatie_Data",
		Kleur:        "#bfdbfe",
		Veldnaam: "persoonsidentificatie",
		Padnaam:  "natuurlijkpersoon_persoonsidentificaties",
		Factory:  func() Representatie { return &NatuurlijkPersoon_PersoonsIdentificatie_Input{} },
		Tabelnaam:              "natuurlijkpersoon_persoonsidentificatie",
		IDKolom:               "rel_id",
		DBFactory:             func() Representatie { return &NatuurlijkPersoon_PersoonsIdentificatie{} },
		DBSliceFactory:        func() any { return &[]NatuurlijkPersoon_PersoonsIdentificatie{} },
		HeeftPFK:              true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:       "natuurlijkpersoon_id",
		Momentvoorkomen:       Enkelvoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "NatuurlijkPersoon_PersoonsIdentificatie_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"NatuurlijkPersoon_Naam": {
		Typenaam:     "NatuurlijkPersoon_Naam",
		Description:  "Meervoudig gegevenselement van A met onder andere een datumveld.",
		Metatype:     MetatypeGegevenselement,
		IsMaterieel:  false,
		GESubtype:    GESubtypeHub,
		DataTypenaam: "NatuurlijkPersoon_Naam_Data",
		Kleur:        "#bfdbfe",
		Veldnaam: "naam",
		Padnaam:  "natuurlijkpersoon_naams",
		Factory:  func() Representatie { return &NatuurlijkPersoon_Naam_Input{} },
		Tabelnaam:              "natuurlijkpersoon_naam",
		IDKolom:               "rel_id",
		DBFactory:             func() Representatie { return &NatuurlijkPersoon_Naam{} },
		DBSliceFactory:        func() any { return &[]NatuurlijkPersoon_Naam{} },
		HeeftPFK:              true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:       "natuurlijkpersoon_id",
		Momentvoorkomen:       Meervoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "NatuurlijkPersoon_Naam_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"NatuurlijkPersoon_Burgerschap": {
		Typenaam:     "NatuurlijkPersoon_Burgerschap",
		Description:  "Meervoudig gegevenselement van A met numerieke waarden.",
		Metatype:     MetatypeGegevenselement,
		IsMaterieel:  true,
		GESubtype:    GESubtypeHub,
		DataTypenaam: "NatuurlijkPersoon_Burgerschap_Data",
		Kleur:        "#bfdbfe",
		Veldnaam: "burgerschap",
		Padnaam:  "natuurlijkpersoon_burgerschaps",
		Factory:  func() Representatie { return &NatuurlijkPersoon_Burgerschap_Input{} },
		Tabelnaam:              "natuurlijkpersoon_burgerschap",
		IDKolom:               "rel_id",
		DBFactory:             func() Representatie { return &NatuurlijkPersoon_Burgerschap{} },
		DBSliceFactory:        func() any { return &[]NatuurlijkPersoon_Burgerschap{} },
		HeeftPFK:              true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:       "natuurlijkpersoon_id",
		Momentvoorkomen:       Meervoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "NatuurlijkPersoon_Burgerschap_Data", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "NatuurlijkPersoon_Burgerschap_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "NatuurlijkPersoon_Burgerschap_Einde", Momentvoorkomen: Enkelvoudig},
		},
	},
	"Bereikbaarheid": {
		Typenaam:     "Bereikbaarheid",
		Description:  "",
		Metatype:     MetatypeRelatie,
		IsMaterieel:  false,
		GESubtype:    GESubtypeHub,
		DataTypenaam: "Bereikbaarheid_Data",
		Kleur:        "",
		Veldnaam: "bereikbaarheid",
		Padnaam:  "bereikbaarheids",
		Factory:  func() Representatie { return &Bereikbaarheid_Input{} },
		Tabelnaam:              "bereikbaarheid",
		IDKolom:               "rel_id",
		DBFactory:             func() Representatie { return &Bereikbaarheid{} },
		DBSliceFactory:        func() any { return &[]Bereikbaarheid{} },
		HeeftPFK:              true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:           "natuurlijkpersoon_id",
		SecondaireEntiteitIDKolom: "locatie_id",
		Momentvoorkomen:           Enkelvoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Bereikbaarheid_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"NatuurlijkPersoon_PersoonsIdentificatie_Data": {
		Typenaam:               "NatuurlijkPersoon_PersoonsIdentificatie_Data",
		Description:            "Geversioned inhoud van NatuurlijkPersoon_PersoonsIdentificatie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_persoonsidentificatie_data",
		Padnaam:                "natuurlijkpersoon_persoonsidentificatie_data",
		Factory:                func() Representatie { return &NatuurlijkPersoon_PersoonsIdentificatie_Data{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_PersoonsIdentificatie_Data{} },
		Tabelnaam:              "natuurlijkpersoon_persoonsidentificatie_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_PersoonsIdentificatie_Data{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_PersoonsIdentificatie_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon_PersoonsIdentificatie",
	},
	"NatuurlijkPersoon_Naam_Data": {
		Typenaam:               "NatuurlijkPersoon_Naam_Data",
		Description:            "Geversioned inhoud van NatuurlijkPersoon_Naam.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_naam_data",
		Padnaam:                "natuurlijkpersoon_naam_data",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Naam_Data{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Naam_Data{} },
		Tabelnaam:              "natuurlijkpersoon_naam_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Naam_Data{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Naam_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon_Naam",
	},
	"NatuurlijkPersoon_Burgerschap_Data": {
		Typenaam:               "NatuurlijkPersoon_Burgerschap_Data",
		Description:            "Geversioned inhoud van NatuurlijkPersoon_Burgerschap.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_burgerschap_data",
		Padnaam:                "natuurlijkpersoon_burgerschap_data",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Burgerschap_Data{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Burgerschap_Data{} },
		Tabelnaam:              "natuurlijkpersoon_burgerschap_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Burgerschap_Data{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Burgerschap_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon_Burgerschap",
	},
	"Bereikbaarheid_Data": {
		Typenaam:               "Bereikbaarheid_Data",
		Description:            "Geversioned inhoud van Bereikbaarheid.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "bereikbaarheid_data",
		Padnaam:                "bereikbaarheid_data",
		Factory:                func() Representatie { return &Bereikbaarheid_Data{} },
		SliceFactory:           func() any { return &[]Bereikbaarheid_Data{} },
		Tabelnaam:              "bereikbaarheid_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Bereikbaarheid_Data{} },
		DBSliceFactory:         func() any { return &[]Bereikbaarheid_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Bereikbaarheid",
	},
	"NatuurlijkPersoon_Aanvang": {
		Typenaam:               "NatuurlijkPersoon_Aanvang",
		Description:            "Aanvangsdatum van NatuurlijkPersoon.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_aanvang",
		Padnaam:                "natuurlijkpersoon_aanvang",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Aanvang{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Aanvang{} },
		Tabelnaam:              "natuurlijkpersoon_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Aanvang{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon",
	},
	"NatuurlijkPersoon_Einde": {
		Typenaam:               "NatuurlijkPersoon_Einde",
		Description:            "Einddatum van NatuurlijkPersoon.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_einde",
		Padnaam:                "natuurlijkpersoon_einde",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Einde{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Einde{} },
		Tabelnaam:              "natuurlijkpersoon_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Einde{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon",
	},
	"NatuurlijkPersoon_Burgerschap_Aanvang": {
		Typenaam:               "NatuurlijkPersoon_Burgerschap_Aanvang",
		Description:            "Aanvangsdatum van NatuurlijkPersoon_Burgerschap.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_burgerschap_aanvang",
		Padnaam:                "natuurlijkpersoon_burgerschap_aanvang",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Burgerschap_Aanvang{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Burgerschap_Aanvang{} },
		Tabelnaam:              "natuurlijkpersoon_burgerschap_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Burgerschap_Aanvang{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Burgerschap_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon_Burgerschap",
	},
	"NatuurlijkPersoon_Burgerschap_Einde": {
		Typenaam:               "NatuurlijkPersoon_Burgerschap_Einde",
		Description:            "Einddatum van NatuurlijkPersoon_Burgerschap.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_burgerschap_einde",
		Padnaam:                "natuurlijkpersoon_burgerschap_einde",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Burgerschap_Einde{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Burgerschap_Einde{} },
		Tabelnaam:              "natuurlijkpersoon_burgerschap_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Burgerschap_Einde{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Burgerschap_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon_Burgerschap",
	},
	"Locatie": {
		Typenaam:    "Locatie",
		Description: "Entiteit B met materiële tijdlijn en onderliggende representaties X en Y.",
		Metatype:    MetatypeEntiteit,
		IsMaterieel: true,
		Kleur:       "#fecaca",
		Veldnaam:    "locatie",
		Padnaam:     "locaties",
		Factory:     func() Representatie { return &Locatie{} },
		SliceFactory: func() any { return &[]Locatie{} },
		Tabelnaam:      "locatie",
		IDKolom:        "id",
		DBFactory:      func() Representatie { return &Locatie{} },
		DBSliceFactory: func() any { return &[]Locatie{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Adress", JSONRolnaam: "adress", Doeltype: "Locatie_Adres", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "BAGlocaties", JSONRolnaam: "baglocaties", Doeltype: "Locatie_BAGlocatie", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Locatie_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Locatie_Einde", Momentvoorkomen: Enkelvoudig},
		},
	},
	"Locatie_Adres": {
		Typenaam:     "Locatie_Adres",
		Description:  "Enkelvoudig gegevenselement van B met twee tekstvelden.",
		Metatype:     MetatypeGegevenselement,
		IsMaterieel:  false,
		GESubtype:    GESubtypeHub,
		DataTypenaam: "Locatie_Adres_Data",
		Kleur:        "#fecaca",
		Veldnaam: "adres",
		Padnaam:  "locatie_adress",
		Factory:  func() Representatie { return &Locatie_Adres_Input{} },
		Tabelnaam:              "locatie_adres",
		IDKolom:               "rel_id",
		DBFactory:             func() Representatie { return &Locatie_Adres{} },
		DBSliceFactory:        func() any { return &[]Locatie_Adres{} },
		HeeftPFK:              true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:       "locatie_id",
		Momentvoorkomen:       Enkelvoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Locatie_Adres_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"Locatie_BAGlocatie": {
		Typenaam:     "Locatie_BAGlocatie",
		Description:  "Enkelvoudig gegevenselement van B met een tekstveld.",
		Metatype:     MetatypeGegevenselement,
		IsMaterieel:  false,
		GESubtype:    GESubtypeHub,
		DataTypenaam: "Locatie_BAGlocatie_Data",
		Kleur:        "#fecaca",
		Veldnaam: "baglocatie",
		Padnaam:  "locatie_baglocaties",
		Factory:  func() Representatie { return &Locatie_BAGlocatie_Input{} },
		Tabelnaam:              "locatie_baglocatie",
		IDKolom:               "rel_id",
		DBFactory:             func() Representatie { return &Locatie_BAGlocatie{} },
		DBSliceFactory:        func() any { return &[]Locatie_BAGlocatie{} },
		HeeftPFK:              true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:       "locatie_id",
		Momentvoorkomen:       Enkelvoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Locatie_BAGlocatie_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"Locatie_Adres_Data": {
		Typenaam:               "Locatie_Adres_Data",
		Description:            "Geversioned inhoud van Locatie_Adres.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fecaca",
		Veldnaam:               "locatie_adres_data",
		Padnaam:                "locatie_adres_data",
		Factory:                func() Representatie { return &Locatie_Adres_Data{} },
		SliceFactory:           func() any { return &[]Locatie_Adres_Data{} },
		Tabelnaam:              "locatie_adres_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Locatie_Adres_Data{} },
		DBSliceFactory:         func() any { return &[]Locatie_Adres_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "locatie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Locatie_Adres",
	},
	"Locatie_BAGlocatie_Data": {
		Typenaam:               "Locatie_BAGlocatie_Data",
		Description:            "Geversioned inhoud van Locatie_BAGlocatie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fecaca",
		Veldnaam:               "locatie_baglocatie_data",
		Padnaam:                "locatie_baglocatie_data",
		Factory:                func() Representatie { return &Locatie_BAGlocatie_Data{} },
		SliceFactory:           func() any { return &[]Locatie_BAGlocatie_Data{} },
		Tabelnaam:              "locatie_baglocatie_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Locatie_BAGlocatie_Data{} },
		DBSliceFactory:         func() any { return &[]Locatie_BAGlocatie_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "locatie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Locatie_BAGlocatie",
	},
	"Locatie_Aanvang": {
		Typenaam:               "Locatie_Aanvang",
		Description:            "Aanvangsdatum van Locatie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#fecaca",
		Veldnaam:               "locatie_aanvang",
		Padnaam:                "locatie_aanvang",
		Factory:                func() Representatie { return &Locatie_Aanvang{} },
		SliceFactory:           func() any { return &[]Locatie_Aanvang{} },
		Tabelnaam:              "locatie_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Locatie_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Locatie_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "locatie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Locatie",
	},
	"Locatie_Einde": {
		Typenaam:               "Locatie_Einde",
		Description:            "Einddatum van Locatie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#fecaca",
		Veldnaam:               "locatie_einde",
		Padnaam:                "locatie_einde",
		Factory:                func() Representatie { return &Locatie_Einde{} },
		SliceFactory:           func() any { return &[]Locatie_Einde{} },
		Tabelnaam:              "locatie_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Locatie_Einde{} },
		DBSliceFactory:         func() any { return &[]Locatie_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "locatie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Locatie",
	},
}
