package model

// MetaRegistry — de single source of truth voor alle type-metadata.
// Gegenereerd door cmd/codegen — niet handmatig bewerken.

// MetaRegistry is the hardcoded meta model registry.
var MetaRegistry = MetaRegistryType{
	"A": {
		Typenaam:               "A",
		Klassenaam:             "A",
		Description:            "Entiteit A met materiele tijdlijn en onderliggende representaties U, V, W en Rel_A_B.",
		Metatype:               MetatypeEntiteit,
		IsMaterieel:            true,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "a",
		Padnaam:                "as",
		Meervoud:               "as",
		Factory:                func() Representatie { return &A{} },
		SliceFactory:           func() any { return &[]A{} },
		Tabelnaam:              "a",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &A{} },
		DBSliceFactory:         func() any { return &[]A{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "AUs", JSONRolnaam: "a_us", Doeltype: "A_U", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "AVs", JSONRolnaam: "a_vs", Doeltype: "A_V", Momentvoorkomen: Meervoudig},
			{Rolnaam: "AWs", JSONRolnaam: "a_ws", Doeltype: "A_W", Momentvoorkomen: Meervoudig},
			{Rolnaam: "RelABs", JSONRolnaam: "rel_a_bs", Doeltype: "Rel_A_B", Momentvoorkomen: Meervoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "A_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "A_Einde", Momentvoorkomen: Enkelvoudig},
		},
		AfgeleideVelden: []AfgeleidVeld{
			{
				Naam:                "label",
				Description:         "Testafleiding over U.aaa, U.bbb en W.heel",
				GoType:              "string",
				AfleidingsregelTaal: "cel",
				Afleidingsregel:     "U.aaa + (U.bbb != null ? ' [bbb=ja]' : '') + (W.heel != null ? ' · heel=' + W.heel : '')",
				IsWeergaveVeld:      true,
			},
		},
	},
	"A_U": {
		Typenaam:               "A_U",
		Klassenaam:             "U",
		Description:            "Enkelvoudig gegevenselement van A met formele tijdlijn.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "A_U_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "u",
		Padnaam:                "a_us",
		Meervoud:               "a_us",
		Factory:                func() Representatie { return &A_U_Input{} },
		Tabelnaam:              "a_u",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &A_U{} },
		DBSliceFactory:         func() any { return &[]A_U{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "A_U_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"A_V": {
		Typenaam:               "A_V",
		Klassenaam:             "V",
		Description:            "Meervoudig gegevenselement van A met onder andere een datumveld.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "A_V_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "v",
		Padnaam:                "a_vs",
		Meervoud:               "a_vs",
		Factory:                func() Representatie { return &A_V_Input{} },
		Tabelnaam:              "a_v",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &A_V{} },
		DBSliceFactory:         func() any { return &[]A_V{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Meervoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "A_V_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"A_W": {
		Typenaam:               "A_W",
		Klassenaam:             "W",
		Description:            "Meervoudig gegevenselement van A met numerieke waarden.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            true,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "A_W_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "w",
		Padnaam:                "a_ws",
		Meervoud:               "a_ws",
		Factory:                func() Representatie { return &A_W_Input{} },
		Tabelnaam:              "a_w",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &A_W{} },
		DBSliceFactory:         func() any { return &[]A_W{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Meervoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "A_W_Data", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "A_W_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "A_W_Einde", Momentvoorkomen: Enkelvoudig},
		},
	},
	"Rel_A_B": {
		Typenaam:                  "Rel_A_B",
		Klassenaam:                "Rel_A_B",
		Description:               "Relatie tussen A en B, meervoudig voorkomend per A en met relatieve relatie-id.",
		Metatype:                  MetatypeRelatie,
		IsMaterieel:               true,
		GESubtype:                 GESubtypeHub,
		DataTypenaam:              "Rel_A_B_Data",
		Kleur:                     "",
		Veldnaam:                  "rel_a_b",
		Padnaam:                   "rel_a_bs",
		Meervoud:                  "rel_a_bs",
		Factory:                   func() Representatie { return &Rel_A_B_Input{} },
		Tabelnaam:                 "rel_a_b",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &Rel_A_B{} },
		DBSliceFactory:            func() any { return &[]Rel_A_B{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "a_id",
		SecondaireEntiteitIDKolom: "b_id",
		Momentvoorkomen:           Meervoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Rel_A_B_Data", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Rel_A_B_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Rel_A_B_Einde", Momentvoorkomen: Enkelvoudig},
		},
	},
	"A_U_Data": {
		Typenaam:               "A_U_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van A_U.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "a_u_data",
		Padnaam:                "a_u_data",
		Meervoud:               "a_u_data",
		Factory:                func() Representatie { return &A_U_Data{} },
		SliceFactory:           func() any { return &[]A_U_Data{} },
		Tabelnaam:              "a_u_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &A_U_Data{} },
		DBSliceFactory:         func() any { return &[]A_U_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "A_U",
	},
	"A_V_Data": {
		Typenaam:               "A_V_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van A_V.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "a_v_data",
		Padnaam:                "a_v_data",
		Meervoud:               "a_v_data",
		Factory:                func() Representatie { return &A_V_Data{} },
		SliceFactory:           func() any { return &[]A_V_Data{} },
		Tabelnaam:              "a_v_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &A_V_Data{} },
		DBSliceFactory:         func() any { return &[]A_V_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "A_V",
	},
	"A_W_Data": {
		Typenaam:               "A_W_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van A_W.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "a_w_data",
		Padnaam:                "a_w_data",
		Meervoud:               "a_w_data",
		Factory:                func() Representatie { return &A_W_Data{} },
		SliceFactory:           func() any { return &[]A_W_Data{} },
		Tabelnaam:              "a_w_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &A_W_Data{} },
		DBSliceFactory:         func() any { return &[]A_W_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "A_W",
	},
	"Rel_A_B_Data": {
		Typenaam:               "Rel_A_B_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Rel_A_B.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "rel_a_b_data",
		Padnaam:                "rel_a_b_data",
		Meervoud:               "rel_a_b_data",
		Factory:                func() Representatie { return &Rel_A_B_Data{} },
		SliceFactory:           func() any { return &[]Rel_A_B_Data{} },
		Tabelnaam:              "rel_a_b_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Rel_A_B_Data{} },
		DBSliceFactory:         func() any { return &[]Rel_A_B_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Rel_A_B",
	},
	"A_Aanvang": {
		Typenaam:               "A_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van A.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "a_aanvang",
		Padnaam:                "a_aanvang",
		Meervoud:               "a_aanvang",
		Factory:                func() Representatie { return &A_Aanvang{} },
		SliceFactory:           func() any { return &[]A_Aanvang{} },
		Tabelnaam:              "a_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &A_Aanvang{} },
		DBSliceFactory:         func() any { return &[]A_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "A",
	},
	"A_Einde": {
		Typenaam:               "A_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van A.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "a_einde",
		Padnaam:                "a_einde",
		Meervoud:               "a_einde",
		Factory:                func() Representatie { return &A_Einde{} },
		SliceFactory:           func() any { return &[]A_Einde{} },
		Tabelnaam:              "a_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &A_Einde{} },
		DBSliceFactory:         func() any { return &[]A_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "A",
	},
	"A_W_Aanvang": {
		Typenaam:               "A_W_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van A_W.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "a_w_aanvang",
		Padnaam:                "a_w_aanvang",
		Meervoud:               "a_w_aanvang",
		Factory:                func() Representatie { return &A_W_Aanvang{} },
		SliceFactory:           func() any { return &[]A_W_Aanvang{} },
		Tabelnaam:              "a_w_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &A_W_Aanvang{} },
		DBSliceFactory:         func() any { return &[]A_W_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "A_W",
	},
	"A_W_Einde": {
		Typenaam:               "A_W_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van A_W.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "a_w_einde",
		Padnaam:                "a_w_einde",
		Meervoud:               "a_w_einde",
		Factory:                func() Representatie { return &A_W_Einde{} },
		SliceFactory:           func() any { return &[]A_W_Einde{} },
		Tabelnaam:              "a_w_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &A_W_Einde{} },
		DBSliceFactory:         func() any { return &[]A_W_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "A_W",
	},
	"Rel_A_B_Aanvang": {
		Typenaam:               "Rel_A_B_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Rel_A_B.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "rel_a_b_aanvang",
		Padnaam:                "rel_a_b_aanvang",
		Meervoud:               "rel_a_b_aanvang",
		Factory:                func() Representatie { return &Rel_A_B_Aanvang{} },
		SliceFactory:           func() any { return &[]Rel_A_B_Aanvang{} },
		Tabelnaam:              "rel_a_b_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Rel_A_B_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Rel_A_B_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Rel_A_B",
	},
	"Rel_A_B_Einde": {
		Typenaam:               "Rel_A_B_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Rel_A_B.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "rel_a_b_einde",
		Padnaam:                "rel_a_b_einde",
		Meervoud:               "rel_a_b_einde",
		Factory:                func() Representatie { return &Rel_A_B_Einde{} },
		SliceFactory:           func() any { return &[]Rel_A_B_Einde{} },
		Tabelnaam:              "rel_a_b_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Rel_A_B_Einde{} },
		DBSliceFactory:         func() any { return &[]Rel_A_B_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Rel_A_B",
	},
	"AdellijkeTitel": {
		Typenaam:               "AdellijkeTitel",
		Klassenaam:             "AdellijkeTitel",
		Description:            "Referentielijst-item: adellijke titel.",
		Metatype:               MetatypeEntiteit,
		EntiteitSubtype:        EntiteitSubtypeReferentielijstItem,
		IsMaterieel:            false,
		Kleur:                  "#c4b5fd",
		Veldnaam:               "adellijketitel",
		Padnaam:                "adellijke_titels",
		Meervoud:               "adellijke titels",
		Factory:                func() Representatie { return &AdellijkeTitel{} },
		SliceFactory:           func() any { return &[]AdellijkeTitel{} },
		Tabelnaam:              "adellijketitel",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &AdellijkeTitel{} },
		DBSliceFactory:         func() any { return &[]AdellijkeTitel{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "AdellijkeTitelTitels", JSONRolnaam: "adellijke_titel_titels", Doeltype: "AdellijkeTitelTitel", Momentvoorkomen: Enkelvoudig},
		},
	},
	"AdellijkeTitelTitel": {
		Typenaam:               "AdellijkeTitelTitel",
		Klassenaam:             "AdellijkeTitelTitel",
		Description:            "Enkelvoudig gegevenselement titel van AdellijkeTitel.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "AdellijkeTitelTitel_Data",
		Kleur:                  "#c4b5fd",
		Veldnaam:               "adellijketiteltitel",
		Padnaam:                "adellijke_titel_titels",
		Meervoud:               "adellijke_titel_titels",
		Factory:                func() Representatie { return &AdellijkeTitelTitel_Input{} },
		Tabelnaam:              "adellijketiteltitel",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &AdellijkeTitelTitel{} },
		DBSliceFactory:         func() any { return &[]AdellijkeTitelTitel{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "adellijketitel_id",
		Momentvoorkomen:        Enkelvoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "AdellijkeTitelTitel_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"AdellijkeTitelTitel_Data": {
		Typenaam:               "AdellijkeTitelTitel_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van AdellijkeTitelTitel.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#c4b5fd",
		Veldnaam:               "adellijketiteltitel_data",
		Padnaam:                "adellijketiteltitel_data",
		Meervoud:               "adellijketiteltitel_data",
		Factory:                func() Representatie { return &AdellijkeTitelTitel_Data{} },
		SliceFactory:           func() any { return &[]AdellijkeTitelTitel_Data{} },
		Tabelnaam:              "adellijketiteltitel_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &AdellijkeTitelTitel_Data{} },
		DBSliceFactory:         func() any { return &[]AdellijkeTitelTitel_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "adellijketitel_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "AdellijkeTitelTitel",
	},
	"B": {
		Typenaam:               "B",
		Klassenaam:             "B",
		Description:            "Entiteit B met materiele tijdlijn en onderliggende representaties X en Y.",
		Metatype:               MetatypeEntiteit,
		IsMaterieel:            true,
		Kleur:                  "#fecaca",
		Veldnaam:               "b",
		Padnaam:                "bs",
		Meervoud:               "bs",
		Factory:                func() Representatie { return &B{} },
		SliceFactory:           func() any { return &[]B{} },
		Tabelnaam:              "b",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &B{} },
		DBSliceFactory:         func() any { return &[]B{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "BXs", JSONRolnaam: "b_xs", Doeltype: "B_X", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "BYs", JSONRolnaam: "b_ys", Doeltype: "B_Y", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "B_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "B_Einde", Momentvoorkomen: Enkelvoudig},
		},
	},
	"B_X": {
		Typenaam:               "B_X",
		Klassenaam:             "X",
		Description:            "Enkelvoudig gegevenselement van B met twee tekstvelden.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "B_X_Data",
		Kleur:                  "#fecaca",
		Veldnaam:               "x",
		Padnaam:                "b_xs",
		Meervoud:               "b_xs",
		Factory:                func() Representatie { return &B_X_Input{} },
		Tabelnaam:              "b_x",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &B_X{} },
		DBSliceFactory:         func() any { return &[]B_X{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "b_id",
		Momentvoorkomen:        Enkelvoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "B_X_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"B_Y": {
		Typenaam:               "B_Y",
		Klassenaam:             "Y",
		Description:            "Enkelvoudig gegevenselement van B met een tekstveld.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "B_Y_Data",
		Kleur:                  "#fecaca",
		Veldnaam:               "y",
		Padnaam:                "b_ys",
		Meervoud:               "b_ys",
		Factory:                func() Representatie { return &B_Y_Input{} },
		Tabelnaam:              "b_y",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &B_Y{} },
		DBSliceFactory:         func() any { return &[]B_Y{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "b_id",
		Momentvoorkomen:        Enkelvoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "B_Y_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"B_X_Data": {
		Typenaam:               "B_X_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van B_X.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fecaca",
		Veldnaam:               "b_x_data",
		Padnaam:                "b_x_data",
		Meervoud:               "b_x_data",
		Factory:                func() Representatie { return &B_X_Data{} },
		SliceFactory:           func() any { return &[]B_X_Data{} },
		Tabelnaam:              "b_x_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &B_X_Data{} },
		DBSliceFactory:         func() any { return &[]B_X_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "b_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "B_X",
	},
	"B_Y_Data": {
		Typenaam:               "B_Y_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van B_Y.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fecaca",
		Veldnaam:               "b_y_data",
		Padnaam:                "b_y_data",
		Meervoud:               "b_y_data",
		Factory:                func() Representatie { return &B_Y_Data{} },
		SliceFactory:           func() any { return &[]B_Y_Data{} },
		Tabelnaam:              "b_y_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &B_Y_Data{} },
		DBSliceFactory:         func() any { return &[]B_Y_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "b_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "B_Y",
	},
	"B_Aanvang": {
		Typenaam:               "B_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van B.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#fecaca",
		Veldnaam:               "b_aanvang",
		Padnaam:                "b_aanvang",
		Meervoud:               "b_aanvang",
		Factory:                func() Representatie { return &B_Aanvang{} },
		SliceFactory:           func() any { return &[]B_Aanvang{} },
		Tabelnaam:              "b_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &B_Aanvang{} },
		DBSliceFactory:         func() any { return &[]B_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "b_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "B",
	},
	"B_Einde": {
		Typenaam:               "B_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van B.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#fecaca",
		Veldnaam:               "b_einde",
		Padnaam:                "b_einde",
		Meervoud:               "b_einde",
		Factory:                func() Representatie { return &B_Einde{} },
		SliceFactory:           func() any { return &[]B_Einde{} },
		Tabelnaam:              "b_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &B_Einde{} },
		DBSliceFactory:         func() any { return &[]B_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "b_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "B",
	},
	"Land": {
		Typenaam:               "Land",
		Klassenaam:             "Land",
		Description:            "Referentielijst-item: individueel land.",
		Metatype:               MetatypeEntiteit,
		EntiteitSubtype:        EntiteitSubtypeReferentielijstItem,
		IsMaterieel:            true,
		Kleur:                  "#fde68a",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 1215, Y: 345}},
		Veldnaam:               "land",
		Padnaam:                "landen",
		Meervoud:               "landen",
		Factory:                func() Representatie { return &Land{} },
		SliceFactory:           func() any { return &[]Land{} },
		Tabelnaam:              "land",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &Land{} },
		DBSliceFactory:         func() any { return &[]Land{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Landcodes", JSONRolnaam: "landcodes", Doeltype: "Landcode", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Landnamen", JSONRolnaam: "landnamen", Doeltype: "Landnaam", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Land_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Land_Einde", Momentvoorkomen: Enkelvoudig},
		},
	},
	"Landcode": {
		Typenaam:               "Landcode",
		Klassenaam:             "Landcode",
		Description:            "Enkelvoudig gegevenselement landcode van Land.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Landcode_Data",
		Kleur:                  "#fde68a",
		Veldnaam:               "landcode",
		Padnaam:                "landcodes",
		Meervoud:               "landcodes",
		Factory:                func() Representatie { return &Landcode_Input{} },
		Tabelnaam:              "landcode",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Landcode{} },
		DBSliceFactory:         func() any { return &[]Landcode{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "land_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 1095, Y: 555}, EdgeID: "edge_1774646153149_10",
			SourceHandle: "bottom", TargetHandle: "top",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Landcode_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"Landnaam": {
		Typenaam:               "Landnaam",
		Klassenaam:             "Landnaam",
		Description:            "Enkelvoudig gegevenselement landnaam van Land.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Landnaam_Data",
		Kleur:                  "#fde68a",
		Veldnaam:               "landnaam",
		Padnaam:                "landnamen",
		Meervoud:               "landnamen",
		Factory:                func() Representatie { return &Landnaam_Input{} },
		Tabelnaam:              "landnaam",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Landnaam{} },
		DBSliceFactory:         func() any { return &[]Landnaam{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "land_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 1335, Y: 555}, EdgeID: "edge_1774646072605_7",
			SourceHandle: "bottom", TargetHandle: "top",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Landnaam_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"Landcode_Data": {
		Typenaam:               "Landcode_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Landcode.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fde68a",
		Veldnaam:               "landcode_data",
		Padnaam:                "landcode_data",
		Meervoud:               "landcode_data",
		Factory:                func() Representatie { return &Landcode_Data{} },
		SliceFactory:           func() any { return &[]Landcode_Data{} },
		Tabelnaam:              "landcode_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Landcode_Data{} },
		DBSliceFactory:         func() any { return &[]Landcode_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "land_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Landcode",
	},
	"Landnaam_Data": {
		Typenaam:               "Landnaam_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Landnaam.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fde68a",
		Veldnaam:               "landnaam_data",
		Padnaam:                "landnaam_data",
		Meervoud:               "landnaam_data",
		Factory:                func() Representatie { return &Landnaam_Data{} },
		SliceFactory:           func() any { return &[]Landnaam_Data{} },
		Tabelnaam:              "landnaam_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Landnaam_Data{} },
		DBSliceFactory:         func() any { return &[]Landnaam_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "land_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Landnaam",
	},
	"Land_Aanvang": {
		Typenaam:               "Land_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Land.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#fde68a",
		Veldnaam:               "land_aanvang",
		Padnaam:                "land_aanvang",
		Meervoud:               "land_aanvang",
		Factory:                func() Representatie { return &Land_Aanvang{} },
		SliceFactory:           func() any { return &[]Land_Aanvang{} },
		Tabelnaam:              "land_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Land_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Land_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "land_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Land",
	},
	"Land_Einde": {
		Typenaam:               "Land_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Land.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#fde68a",
		Veldnaam:               "land_einde",
		Padnaam:                "land_einde",
		Meervoud:               "land_einde",
		Factory:                func() Representatie { return &Land_Einde{} },
		SliceFactory:           func() any { return &[]Land_Einde{} },
		Tabelnaam:              "land_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Land_Einde{} },
		DBSliceFactory:         func() any { return &[]Land_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "land_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Land",
	},
	"Locatie": {
		Typenaam:               "Locatie",
		Klassenaam:             "Locatie",
		Description:            "Fysiek bezoekbare locatie gelegen op het aardoppervlak.",
		Metatype:               MetatypeEntiteit,
		IsMaterieel:            true,
		Kleur:                  "#fecaca",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 720, Y: -135}},
		Veldnaam:               "locatie",
		Padnaam:                "locaties",
		Meervoud:               "locaties",
		Factory:                func() Representatie { return &Locatie{} },
		SliceFactory:           func() any { return &[]Locatie{} },
		Tabelnaam:              "locatie",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &Locatie{} },
		DBSliceFactory:         func() any { return &[]Locatie{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Adressen", JSONRolnaam: "adressen", Doeltype: "Locatie_Adres", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Baglocaties", JSONRolnaam: "baglocaties", Doeltype: "Locatie_BAGlocatie", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Locatie_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Locatie_Einde", Momentvoorkomen: Enkelvoudig},
		},
		AfgeleideVelden: []AfgeleidVeld{
			{
				Naam:                "weergaveadres",
				Description:         "Samengesteld weergaveadres, afgeleid uit straatnaam, huisnummer, postcode en plaats.",
				GoType:              "string",
				AfleidingsregelTaal: "cel",
				Afleidingsregel:     "Adres.straatnaam + ' ' + Adres.huisnummer + ', ' + Adres.postcode + ' ' + Adres.plaats",
				IsWeergaveVeld:      true,
			},
		},
	},
	"Locatie_Adres": {
		Typenaam:               "Locatie_Adres",
		Klassenaam:             "Adres",
		Description:            "Binnenlands adres: een aanduiding van een binnenlandse locatie, uitgegeven door de gemeente en geregistreerd in de BAG.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Locatie_Adres_Data",
		Kleur:                  "#fecaca",
		Veldnaam:               "adres",
		Padnaam:                "adressen",
		Meervoud:               "adressen",
		Factory:                func() Representatie { return &Locatie_Adres_Input{} },
		Tabelnaam:              "locatie_adres",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Locatie_Adres{} },
		DBSliceFactory:         func() any { return &[]Locatie_Adres{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "locatie_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 780, Y: 60}, EdgeID: "Locatie->Locatie_Adres",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Locatie_Adres_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"Locatie_BAGlocatie": {
		Typenaam:               "Locatie_BAGlocatie",
		Klassenaam:             "BAGlocatie",
		Description:            "Unieke identificatie van het adresseerbaar object (verblijfsobject, stand- of ligplaats) uitgegeven door het bevoegd gemeentelijke orgaan.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Locatie_BAGlocatie_Data",
		Kleur:                  "#fecaca",
		Veldnaam:               "baglocatie",
		Padnaam:                "baglocaties",
		Meervoud:               "baglocaties",
		Factory:                func() Representatie { return &Locatie_BAGlocatie_Input{} },
		Tabelnaam:              "locatie_baglocatie",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Locatie_BAGlocatie{} },
		DBSliceFactory:         func() any { return &[]Locatie_BAGlocatie{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "locatie_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 585, Y: 90}, EdgeID: "Locatie->Locatie_BAG-locatie",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Locatie_BAGlocatie_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"Locatie_Adres_Data": {
		Typenaam:               "Locatie_Adres_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Locatie_Adres.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fecaca",
		Veldnaam:               "locatie_adres_data",
		Padnaam:                "locatie_adres_data",
		Meervoud:               "locatie_adres_data",
		Factory:                func() Representatie { return &Locatie_Adres_Data{} },
		SliceFactory:           func() any { return &[]Locatie_Adres_Data{} },
		Tabelnaam:              "locatie_adres_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Locatie_Adres_Data{} },
		DBSliceFactory:         func() any { return &[]Locatie_Adres_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "locatie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Locatie_Adres",
	},
	"Locatie_BAGlocatie_Data": {
		Typenaam:               "Locatie_BAGlocatie_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Locatie_BAGlocatie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fecaca",
		Veldnaam:               "locatie_baglocatie_data",
		Padnaam:                "locatie_baglocatie_data",
		Meervoud:               "locatie_baglocatie_data",
		Factory:                func() Representatie { return &Locatie_BAGlocatie_Data{} },
		SliceFactory:           func() any { return &[]Locatie_BAGlocatie_Data{} },
		Tabelnaam:              "locatie_baglocatie_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Locatie_BAGlocatie_Data{} },
		DBSliceFactory:         func() any { return &[]Locatie_BAGlocatie_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "locatie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Locatie_BAGlocatie",
	},
	"Locatie_Aanvang": {
		Typenaam:               "Locatie_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Locatie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#fecaca",
		Veldnaam:               "locatie_aanvang",
		Padnaam:                "locatie_aanvang",
		Meervoud:               "locatie_aanvang",
		Factory:                func() Representatie { return &Locatie_Aanvang{} },
		SliceFactory:           func() any { return &[]Locatie_Aanvang{} },
		Tabelnaam:              "locatie_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Locatie_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Locatie_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "locatie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Locatie",
	},
	"Locatie_Einde": {
		Typenaam:               "Locatie_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Locatie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#fecaca",
		Veldnaam:               "locatie_einde",
		Padnaam:                "locatie_einde",
		Meervoud:               "locatie_einde",
		Factory:                func() Representatie { return &Locatie_Einde{} },
		SliceFactory:           func() any { return &[]Locatie_Einde{} },
		Tabelnaam:              "locatie_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Locatie_Einde{} },
		DBSliceFactory:         func() any { return &[]Locatie_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "locatie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Locatie",
	},
	"NatuurlijkPersoon": {
		Typenaam:               "NatuurlijkPersoon",
		Klassenaam:             "NatuurlijkPersoon",
		Description:            "Een mens voor zover deze door Nederlandse wetgeving met rechten en plichten wordt bekleed.",
		Metatype:               MetatypeEntiteit,
		IsMaterieel:            true,
		Kleur:                  "#bfdbfe",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: -90, Y: -135}},
		Veldnaam:               "natuurlijkpersoon",
		Padnaam:                "natuurlijk_personen",
		Meervoud:               "natuurlijk personen",
		Factory:                func() Representatie { return &NatuurlijkPersoon{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon{} },
		Tabelnaam:              "natuurlijkpersoon",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Persoonsidentificaties", JSONRolnaam: "persoonsidentificaties", Doeltype: "NatuurlijkPersoon_Persoonsidentificatie", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Namen", JSONRolnaam: "namen", Doeltype: "NatuurlijkPersoon_Naam", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Burgerschappen", JSONRolnaam: "burgerschappen", Doeltype: "NatuurlijkPersoon_Burgerschap", Momentvoorkomen: Meervoudig},
			{Rolnaam: "Partnernamen", JSONRolnaam: "partnernamen", Doeltype: "NatuurlijkPersoon_Partnernaam", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Naamgebruiken", JSONRolnaam: "naamgebruiken", Doeltype: "NatuurlijkPersoon_Naamgebruik", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Bereikbaarheden", JSONRolnaam: "bereikbaarheden", Doeltype: "Bereikbaarheid", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "NatuurlijkPersoon_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "NatuurlijkPersoon_Einde", Momentvoorkomen: Enkelvoudig},
		},
		AfgeleideVelden: []AfgeleidVeld{
			{
				Naam:                "weergavenaam",
				Description:         "Samengestelde weergavenaam van de persoon, afgeleid uit voornaam/tussenvoegsel/achternaam.",
				GoType:              "string",
				AfleidingsregelTaal: "cel",
				Afleidingsregel:     "(Naam.roepnaam != null ? Naam.roepnaam : Naam.voorletters) + (Naam.tussenvoegsel != null ? ' ' + Naam.tussenvoegsel : '') + ' ' + Naam.achternaam",
				IsWeergaveVeld:      true,
			},
		},
	},
	"NatuurlijkPersoon_Persoonsidentificatie": {
		Typenaam:               "NatuurlijkPersoon_Persoonsidentificatie",
		Klassenaam:             "Persoonsidentificatie",
		Description:            "Identificerende gegevens van de natuurlijk persoon (BSN, ingezetene).",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "NatuurlijkPersoon_Persoonsidentificatie_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "persoonsidentificatie",
		Padnaam:                "persoonsidentificaties",
		Meervoud:               "persoonsidentificaties",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Persoonsidentificatie_Input{} },
		Tabelnaam:              "natuurlijkpersoon_persoonsidentificatie",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Persoonsidentificatie{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Persoonsidentificatie{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: -450, Y: -30}, EdgeID: "NatuurlijkPersoon->NatuurlijkPersoon_PersoonsIdentificatie",
			SourceHandle: "left",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "NatuurlijkPersoon_Persoonsidentificatie_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"NatuurlijkPersoon_Naam": {
		Typenaam:               "NatuurlijkPersoon_Naam",
		Klassenaam:             "Naam",
		Description:            "Naamgegevens van de natuurlijk persoon (voorletters, roepnaam, tussenvoegsel, achternaam).",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "NatuurlijkPersoon_Naam_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "naam",
		Padnaam:                "namen",
		Meervoud:               "namen",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Naam_Input{} },
		Tabelnaam:              "natuurlijkpersoon_naam",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Naam{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Naam{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: -105, Y: 255}, EdgeID: "NatuurlijkPersoon->NatuurlijkPersoon_Naam",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "NatuurlijkPersoon_Naam_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"NatuurlijkPersoon_Burgerschap": {
		Typenaam:               "NatuurlijkPersoon_Burgerschap",
		Klassenaam:             "Burgerschap",
		Description:            "Nationaliteitsgegevens (burgerschap) van de natuurlijk persoon.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            true,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "NatuurlijkPersoon_Burgerschap_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "burgerschap",
		Padnaam:                "burgerschappen",
		Meervoud:               "burgerschappen",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Burgerschap_Input{} },
		Tabelnaam:              "natuurlijkpersoon_burgerschap",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Burgerschap{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Burgerschap{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Meervoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: -285, Y: 450}, EdgeID: "NatuurlijkPersoon->NatuurlijkPersoon_Burgerschap",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "NatuurlijkPersoon_Burgerschap_Data", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "NatuurlijkPersoon_Burgerschap_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "NatuurlijkPersoon_Burgerschap_Einde", Momentvoorkomen: Enkelvoudig},
		},
		AfgeleideVelden: []AfgeleidVeld{
			{
				Naam:                "weergaveburgerschap",
				Description:         "Samengestelde weergave van nationaliteit en landcode.",
				GoType:              "string",
				AfleidingsregelTaal: "cel",
				Afleidingsregel:     "Burgerschap.nationaliteit + ' (' + Burgerschap.landcode + ')'",
				IsWeergaveVeld:      true,
			},
		},
	},
	"NatuurlijkPersoon_Partnernaam": {
		Typenaam:               "NatuurlijkPersoon_Partnernaam",
		Klassenaam:             "Partnernaam",
		Description:            "Achternaam van de partner van de natuurlijk persoon.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "NatuurlijkPersoon_Partnernaam_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "partnernaam",
		Padnaam:                "partnernamen",
		Meervoud:               "partnernamen",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Partnernaam_Input{} },
		Tabelnaam:              "natuurlijkpersoon_partnernaam",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Partnernaam{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Partnernaam{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 60, Y: 450}, EdgeID: "edge_1774209110136_2",
			SourceHandle: "bottom", TargetHandle: "top",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "NatuurlijkPersoon_Partnernaam_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"NatuurlijkPersoon_Naamgebruik": {
		Typenaam:               "NatuurlijkPersoon_Naamgebruik",
		Klassenaam:             "Naamgebruik",
		Description:            "Wijze waarop de geslachtsnaam wordt gebruikt.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "NatuurlijkPersoon_Naamgebruik_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "naamgebruik",
		Padnaam:                "naamgebruiken",
		Meervoud:               "naamgebruiken",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Naamgebruik_Input{} },
		Tabelnaam:              "natuurlijkpersoon_naamgebruik",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Naamgebruik{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Naamgebruik{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 195, Y: 255}, EdgeID: "edge_1774209240752_5",
			SourceHandle: "bottom", TargetHandle: "top",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "NatuurlijkPersoon_Naamgebruik_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"Bereikbaarheid": {
		Typenaam:                  "Bereikbaarheid",
		Klassenaam:                "Bereikbaarheid",
		Description:               "Koppeling van een natuurlijk persoon aan een locatie als bereikbaarheidsadres.",
		Metatype:                  MetatypeRelatie,
		IsMaterieel:               true,
		GESubtype:                 GESubtypeHub,
		DataTypenaam:              "Bereikbaarheid_Data",
		Kleur:                     "",
		Veldnaam:                  "bereikbaarheid",
		Padnaam:                   "bereikbaarheden",
		Meervoud:                  "bereikbaarheden",
		Factory:                   func() Representatie { return &Bereikbaarheid_Input{} },
		Tabelnaam:                 "bereikbaarheid",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &Bereikbaarheid{} },
		DBSliceFactory:            func() any { return &[]Bereikbaarheid{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "natuurlijkpersoon_id",
		SecondaireEntiteitIDKolom: "locatie_id",
		Momentvoorkomen:           Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 330, Y: -120}, EdgeID: "edge_1774201942583_1",
			SourceHandle: "right", TargetHandle: "left",
			DoelEdgeID: "edge_1774201991984_2", DoelSourceHandle: "right", DoelTargetHandle: "left",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Bereikbaarheid_Data", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Bereikbaarheid_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Bereikbaarheid_Einde", Momentvoorkomen: Enkelvoudig},
		},
	},
	"NatuurlijkPersoon_Persoonsidentificatie_Data": {
		Typenaam:               "NatuurlijkPersoon_Persoonsidentificatie_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van NatuurlijkPersoon_Persoonsidentificatie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_persoonsidentificatie_data",
		Padnaam:                "natuurlijkpersoon_persoonsidentificatie_data",
		Meervoud:               "natuurlijkpersoon_persoonsidentificatie_data",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Persoonsidentificatie_Data{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Persoonsidentificatie_Data{} },
		Tabelnaam:              "natuurlijkpersoon_persoonsidentificatie_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Persoonsidentificatie_Data{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Persoonsidentificatie_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon_Persoonsidentificatie",
	},
	"NatuurlijkPersoon_Naam_Data": {
		Typenaam:               "NatuurlijkPersoon_Naam_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van NatuurlijkPersoon_Naam.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_naam_data",
		Padnaam:                "natuurlijkpersoon_naam_data",
		Meervoud:               "natuurlijkpersoon_naam_data",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Naam_Data{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Naam_Data{} },
		Tabelnaam:              "natuurlijkpersoon_naam_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Naam_Data{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Naam_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon_Naam",
	},
	"NatuurlijkPersoon_Burgerschap_Data": {
		Typenaam:               "NatuurlijkPersoon_Burgerschap_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van NatuurlijkPersoon_Burgerschap.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_burgerschap_data",
		Padnaam:                "natuurlijkpersoon_burgerschap_data",
		Meervoud:               "natuurlijkpersoon_burgerschap_data",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Burgerschap_Data{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Burgerschap_Data{} },
		Tabelnaam:              "natuurlijkpersoon_burgerschap_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Burgerschap_Data{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Burgerschap_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon_Burgerschap",
	},
	"NatuurlijkPersoon_Partnernaam_Data": {
		Typenaam:               "NatuurlijkPersoon_Partnernaam_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van NatuurlijkPersoon_Partnernaam.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_partnernaam_data",
		Padnaam:                "natuurlijkpersoon_partnernaam_data",
		Meervoud:               "natuurlijkpersoon_partnernaam_data",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Partnernaam_Data{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Partnernaam_Data{} },
		Tabelnaam:              "natuurlijkpersoon_partnernaam_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Partnernaam_Data{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Partnernaam_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon_Partnernaam",
	},
	"NatuurlijkPersoon_Naamgebruik_Data": {
		Typenaam:               "NatuurlijkPersoon_Naamgebruik_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van NatuurlijkPersoon_Naamgebruik.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_naamgebruik_data",
		Padnaam:                "natuurlijkpersoon_naamgebruik_data",
		Meervoud:               "natuurlijkpersoon_naamgebruik_data",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Naamgebruik_Data{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Naamgebruik_Data{} },
		Tabelnaam:              "natuurlijkpersoon_naamgebruik_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Naamgebruik_Data{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Naamgebruik_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon_Naamgebruik",
	},
	"Bereikbaarheid_Data": {
		Typenaam:               "Bereikbaarheid_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Bereikbaarheid.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "bereikbaarheid_data",
		Padnaam:                "bereikbaarheid_data",
		Meervoud:               "bereikbaarheid_data",
		Factory:                func() Representatie { return &Bereikbaarheid_Data{} },
		SliceFactory:           func() any { return &[]Bereikbaarheid_Data{} },
		Tabelnaam:              "bereikbaarheid_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Bereikbaarheid_Data{} },
		DBSliceFactory:         func() any { return &[]Bereikbaarheid_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Bereikbaarheid",
	},
	"NatuurlijkPersoon_Aanvang": {
		Typenaam:               "NatuurlijkPersoon_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van NatuurlijkPersoon.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_aanvang",
		Padnaam:                "natuurlijkpersoon_aanvang",
		Meervoud:               "natuurlijkpersoon_aanvang",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Aanvang{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Aanvang{} },
		Tabelnaam:              "natuurlijkpersoon_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Aanvang{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon",
	},
	"NatuurlijkPersoon_Einde": {
		Typenaam:               "NatuurlijkPersoon_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van NatuurlijkPersoon.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_einde",
		Padnaam:                "natuurlijkpersoon_einde",
		Meervoud:               "natuurlijkpersoon_einde",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Einde{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Einde{} },
		Tabelnaam:              "natuurlijkpersoon_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Einde{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon",
	},
	"NatuurlijkPersoon_Burgerschap_Aanvang": {
		Typenaam:               "NatuurlijkPersoon_Burgerschap_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van NatuurlijkPersoon_Burgerschap.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_burgerschap_aanvang",
		Padnaam:                "natuurlijkpersoon_burgerschap_aanvang",
		Meervoud:               "natuurlijkpersoon_burgerschap_aanvang",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Burgerschap_Aanvang{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Burgerschap_Aanvang{} },
		Tabelnaam:              "natuurlijkpersoon_burgerschap_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Burgerschap_Aanvang{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Burgerschap_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon_Burgerschap",
	},
	"NatuurlijkPersoon_Burgerschap_Einde": {
		Typenaam:               "NatuurlijkPersoon_Burgerschap_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van NatuurlijkPersoon_Burgerschap.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_burgerschap_einde",
		Padnaam:                "natuurlijkpersoon_burgerschap_einde",
		Meervoud:               "natuurlijkpersoon_burgerschap_einde",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Burgerschap_Einde{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Burgerschap_Einde{} },
		Tabelnaam:              "natuurlijkpersoon_burgerschap_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Burgerschap_Einde{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Burgerschap_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon_Burgerschap",
	},
	"Bereikbaarheid_Aanvang": {
		Typenaam:               "Bereikbaarheid_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Bereikbaarheid.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "bereikbaarheid_aanvang",
		Padnaam:                "bereikbaarheid_aanvang",
		Meervoud:               "bereikbaarheid_aanvang",
		Factory:                func() Representatie { return &Bereikbaarheid_Aanvang{} },
		SliceFactory:           func() any { return &[]Bereikbaarheid_Aanvang{} },
		Tabelnaam:              "bereikbaarheid_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Bereikbaarheid_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Bereikbaarheid_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Bereikbaarheid",
	},
	"Bereikbaarheid_Einde": {
		Typenaam:               "Bereikbaarheid_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Bereikbaarheid.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "bereikbaarheid_einde",
		Padnaam:                "bereikbaarheid_einde",
		Meervoud:               "bereikbaarheid_einde",
		Factory:                func() Representatie { return &Bereikbaarheid_Einde{} },
		SliceFactory:           func() any { return &[]Bereikbaarheid_Einde{} },
		Tabelnaam:              "bereikbaarheid_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Bereikbaarheid_Einde{} },
		DBSliceFactory:         func() any { return &[]Bereikbaarheid_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Bereikbaarheid",
	},
	"Referentielijst": {
		Typenaam:               "Referentielijst",
		Klassenaam:             "Referentielijst",
		Description:            "Generieke referentielijst-entiteit. Individuele lijsten (Landenlijst, EULidstaten, etc.) zijn records.",
		Metatype:               MetatypeEntiteit,
		EntiteitSubtype:        EntiteitSubtypeReferentielijst,
		IsMaterieel:            true,
		Kleur:                  "#fef3c7",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 1260, Y: -240}},
		Veldnaam:               "referentielijst",
		Padnaam:                "referentielijsten",
		Meervoud:               "referentielijsten",
		Factory:                func() Representatie { return &Referentielijst{} },
		SliceFactory:           func() any { return &[]Referentielijst{} },
		Tabelnaam:              "referentielijst",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &Referentielijst{} },
		DBSliceFactory:         func() any { return &[]Referentielijst{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Referentielijstnamen", JSONRolnaam: "referentielijstnamen", Doeltype: "Referentielijstnaam", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Referentielijstomschrijvingen", JSONRolnaam: "referentielijstomschrijvingen", Doeltype: "Referentielijstomschrijving", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Visibilities", JSONRolnaam: "visibilities", Doeltype: "ReferentielijstVisibility", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Internetadressen", JSONRolnaam: "internetadressen", Doeltype: "ReferentielijstInternetadres", Momentvoorkomen: Meervoudig},
			{Rolnaam: "LandenlijstLanden", JSONRolnaam: "landenlijst_landen", Doeltype: "LandenlijstLand", Momentvoorkomen: Meervoudig},
			{Rolnaam: "AdellijkeTitelsTitels", JSONRolnaam: "adellijke_titels_titels", Doeltype: "AdellijkeTitelsTitel", Momentvoorkomen: Meervoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Referentielijst_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Referentielijst_Einde", Momentvoorkomen: Enkelvoudig},
		},
	},
	"Referentielijstnaam": {
		Typenaam:               "Referentielijstnaam",
		Klassenaam:             "Referentielijstnaam",
		Description:            "Leesbare naam van een referentielijst.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Referentielijstnaam_Data",
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstnaam",
		Padnaam:                "referentielijstnamen",
		Meervoud:               "referentielijstnamen",
		Factory:                func() Representatie { return &Referentielijstnaam_Input{} },
		Tabelnaam:              "referentielijstnaam",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Referentielijstnaam{} },
		DBSliceFactory:         func() any { return &[]Referentielijstnaam{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 1590, Y: -255}, EdgeID: "Referentielijst->Referentielijst_Referentielijstnaam",
			SourceHandle: "right", TargetHandle: "left",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Referentielijstnaam_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"Referentielijstomschrijving": {
		Typenaam:               "Referentielijstomschrijving",
		Klassenaam:             "Referentielijstomschrijving",
		Description:            "Omschrijving van een referentielijst.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Referentielijstomschrijving_Data",
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstomschrijving",
		Padnaam:                "referentielijstomschrijvingen",
		Meervoud:               "referentielijstomschrijvingen",
		Factory:                func() Representatie { return &Referentielijstomschrijving_Input{} },
		Tabelnaam:              "referentielijstomschrijving",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Referentielijstomschrijving{} },
		DBSliceFactory:         func() any { return &[]Referentielijstomschrijving{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 1590, Y: -135}, EdgeID: "Referentielijst->Referentielijst_Referentielijstomschrijving",
			SourceHandle: "right", TargetHandle: "left",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Referentielijstomschrijving_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"ReferentielijstVisibility": {
		Typenaam:               "ReferentielijstVisibility",
		Klassenaam:             "ReferentielijstVisibility",
		Description:            "Domeinzichtbaarheid van een referentielijst (register, modelspecifiek, extern).",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "ReferentielijstVisibility_Data",
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstvisibility",
		Padnaam:                "visibilities",
		Meervoud:               "visibilities",
		Factory:                func() Representatie { return &ReferentielijstVisibility_Input{} },
		Tabelnaam:              "referentielijstvisibility",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &ReferentielijstVisibility{} },
		DBSliceFactory:         func() any { return &[]ReferentielijstVisibility{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 1590, Y: -15}, EdgeID: "Referentielijst->Referentielijst_ReferentielijstVisibility",
			SourceHandle: "right", TargetHandle: "left",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "ReferentielijstVisibility_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"ReferentielijstInternetadres": {
		Typenaam:               "ReferentielijstInternetadres",
		Klassenaam:             "ReferentielijstInternetadres",
		Description:            "Internetadres (URL/URN) van een referentielijst.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "ReferentielijstInternetadres_Data",
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstinternetadres",
		Padnaam:                "internetadressen",
		Meervoud:               "internetadressen",
		Factory:                func() Representatie { return &ReferentielijstInternetadres_Input{} },
		Tabelnaam:              "referentielijstinternetadres",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &ReferentielijstInternetadres{} },
		DBSliceFactory:         func() any { return &[]ReferentielijstInternetadres{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Meervoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 1590, Y: 85}, EdgeID: "Referentielijst->Referentielijst_ReferentielijstInternetadres",
			SourceHandle: "right", TargetHandle: "left",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "ReferentielijstInternetadres_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"LandenlijstLand": {
		Typenaam:                  "LandenlijstLand",
		Klassenaam:                "LandenlijstLand",
		Description:               "Koppeling van een land aan referentielijst-instantie Landenlijst (referentielijst-items relatie).",
		Metatype:                  MetatypeRelatie,
		RelatieSubtype:            RelatieSubtypeReferentielijstItems,
		ReferentielijstInstantie:  "Landenlijst",
		IsMaterieel:               false,
		GESubtype:                 GESubtypeHub,
		DataTypenaam:              "LandenlijstLand_Data",
		Kleur:                     "",
		Veldnaam:                  "landenlijstland",
		Padnaam:                   "landenlijst_landen",
		Meervoud:                  "landenlijst_landen",
		Factory:                   func() Representatie { return &LandenlijstLand_Input{} },
		Tabelnaam:                 "landenlijstland",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &LandenlijstLand{} },
		DBSliceFactory:            func() any { return &[]LandenlijstLand{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "referentielijst_id",
		SecondaireEntiteitIDKolom: "land_id",
		Momentvoorkomen:           Meervoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 1215, Y: 165}, EdgeID: "Referentielijst->LandenlijstLand",
			DoelEdgeID: "LandenlijstLand->Land",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "LandenlijstLand_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"AdellijkeTitelsTitel": {
		Typenaam:                  "AdellijkeTitelsTitel",
		Klassenaam:                "AdellijkeTitelsTitel",
		Description:               "Koppeling van een adellijke titel aan referentielijst-instantie AdellijkeTitels (referentielijst-items relatie).",
		Metatype:                  MetatypeRelatie,
		RelatieSubtype:            RelatieSubtypeReferentielijstItems,
		ReferentielijstInstantie:  "AdellijkeTitels",
		IsMaterieel:               false,
		GESubtype:                 GESubtypeHub,
		DataTypenaam:              "AdellijkeTitelsTitel_Data",
		Kleur:                     "",
		Veldnaam:                  "adellijketitelstitel",
		Padnaam:                   "adellijke_titels_titels",
		Meervoud:                  "adellijke_titels_titels",
		Factory:                   func() Representatie { return &AdellijkeTitelsTitel_Input{} },
		Tabelnaam:                 "adellijketitelstitel",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &AdellijkeTitelsTitel{} },
		DBSliceFactory:            func() any { return &[]AdellijkeTitelsTitel{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "referentielijst_id",
		SecondaireEntiteitIDKolom: "adellijketitel_id",
		Momentvoorkomen:           Meervoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "AdellijkeTitelsTitel_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"Referentielijstnaam_Data": {
		Typenaam:               "Referentielijstnaam_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Referentielijstnaam.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstnaam_data",
		Padnaam:                "referentielijstnaam_data",
		Meervoud:               "referentielijstnaam_data",
		Factory:                func() Representatie { return &Referentielijstnaam_Data{} },
		SliceFactory:           func() any { return &[]Referentielijstnaam_Data{} },
		Tabelnaam:              "referentielijstnaam_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Referentielijstnaam_Data{} },
		DBSliceFactory:         func() any { return &[]Referentielijstnaam_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijstnaam",
	},
	"Referentielijstomschrijving_Data": {
		Typenaam:               "Referentielijstomschrijving_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Referentielijstomschrijving.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstomschrijving_data",
		Padnaam:                "referentielijstomschrijving_data",
		Meervoud:               "referentielijstomschrijving_data",
		Factory:                func() Representatie { return &Referentielijstomschrijving_Data{} },
		SliceFactory:           func() any { return &[]Referentielijstomschrijving_Data{} },
		Tabelnaam:              "referentielijstomschrijving_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Referentielijstomschrijving_Data{} },
		DBSliceFactory:         func() any { return &[]Referentielijstomschrijving_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijstomschrijving",
	},
	"ReferentielijstVisibility_Data": {
		Typenaam:               "ReferentielijstVisibility_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van ReferentielijstVisibility.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstvisibility_data",
		Padnaam:                "referentielijstvisibility_data",
		Meervoud:               "referentielijstvisibility_data",
		Factory:                func() Representatie { return &ReferentielijstVisibility_Data{} },
		SliceFactory:           func() any { return &[]ReferentielijstVisibility_Data{} },
		Tabelnaam:              "referentielijstvisibility_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &ReferentielijstVisibility_Data{} },
		DBSliceFactory:         func() any { return &[]ReferentielijstVisibility_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "ReferentielijstVisibility",
	},
	"ReferentielijstInternetadres_Data": {
		Typenaam:               "ReferentielijstInternetadres_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van ReferentielijstInternetadres.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstinternetadres_data",
		Padnaam:                "referentielijstinternetadres_data",
		Meervoud:               "referentielijstinternetadres_data",
		Factory:                func() Representatie { return &ReferentielijstInternetadres_Data{} },
		SliceFactory:           func() any { return &[]ReferentielijstInternetadres_Data{} },
		Tabelnaam:              "referentielijstinternetadres_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &ReferentielijstInternetadres_Data{} },
		DBSliceFactory:         func() any { return &[]ReferentielijstInternetadres_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "ReferentielijstInternetadres",
	},
	"LandenlijstLand_Data": {
		Typenaam:               "LandenlijstLand_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van LandenlijstLand.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fef3c7",
		Veldnaam:               "landenlijstland_data",
		Padnaam:                "landenlijstland_data",
		Meervoud:               "landenlijstland_data",
		Factory:                func() Representatie { return &LandenlijstLand_Data{} },
		SliceFactory:           func() any { return &[]LandenlijstLand_Data{} },
		Tabelnaam:              "landenlijstland_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &LandenlijstLand_Data{} },
		DBSliceFactory:         func() any { return &[]LandenlijstLand_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "LandenlijstLand",
	},
	"AdellijkeTitelsTitel_Data": {
		Typenaam:               "AdellijkeTitelsTitel_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van AdellijkeTitelsTitel.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fef3c7",
		Veldnaam:               "adellijketitelstitel_data",
		Padnaam:                "adellijketitelstitel_data",
		Meervoud:               "adellijketitelstitel_data",
		Factory:                func() Representatie { return &AdellijkeTitelsTitel_Data{} },
		SliceFactory:           func() any { return &[]AdellijkeTitelsTitel_Data{} },
		Tabelnaam:              "adellijketitelstitel_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &AdellijkeTitelsTitel_Data{} },
		DBSliceFactory:         func() any { return &[]AdellijkeTitelsTitel_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "AdellijkeTitelsTitel",
	},
	"Referentielijst_Aanvang": {
		Typenaam:               "Referentielijst_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Referentielijst.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijst_aanvang",
		Padnaam:                "referentielijst_aanvang",
		Meervoud:               "referentielijst_aanvang",
		Factory:                func() Representatie { return &Referentielijst_Aanvang{} },
		SliceFactory:           func() any { return &[]Referentielijst_Aanvang{} },
		Tabelnaam:              "referentielijst_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Referentielijst_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Referentielijst_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijst",
	},
	"Referentielijst_Einde": {
		Typenaam:               "Referentielijst_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Referentielijst.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijst_einde",
		Padnaam:                "referentielijst_einde",
		Meervoud:               "referentielijst_einde",
		Factory:                func() Representatie { return &Referentielijst_Einde{} },
		SliceFactory:           func() any { return &[]Referentielijst_Einde{} },
		Tabelnaam:              "referentielijst_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Referentielijst_Einde{} },
		DBSliceFactory:         func() any { return &[]Referentielijst_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijst",
	},
}
