package model

// Additieve MetaRegistry-entries — voegt types toe aan de bestaande MetaRegistry.
// Gegenereerd door cmd/codegen — niet handmatig bewerken.

func initAbuvwxyMetaRegistry() {
	MetaRegistry["A"] = TypeMeta{
		Typenaam:               "A",
		Klassenaam:             "A",
		Description:            "Entiteit A met materiele tijdlijn en onderliggende representaties U, V, W en Rel_A_B.",
		Metatype:               MetatypeEntiteit,
		IsMaterieel:            true,
		Domein:                 "abuvwxy",
		Kleur:                  "#bfdbfe",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: -555, Y: 450}},
		Veldnaam:               "a",
		Padnaam:                "as",
		Meervoud:               "as",
		Factory:                func() Representatie { return &A{} },
		SliceFactory:           func() any { return &[]A{} },
		Tabelnaam:              "a",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &A{} },
		DBSliceFactory:         func() any { return &[]A{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Us", JSONRolnaam: "us", Doeltype: "A_U", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Vs", JSONRolnaam: "vs", Doeltype: "A_V", Momentvoorkomen: Meervoudig},
			{Rolnaam: "Ws", JSONRolnaam: "ws", Doeltype: "A_W", Momentvoorkomen: Meervoudig},
			{Rolnaam: "RelABs", JSONRolnaam: "rel_a_bs", Doeltype: "Rel_A_B", Momentvoorkomen: Meervoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "A_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "A_Einde", Momentvoorkomen: Enkelvoudig},
		},
		AfgeleideVelden: []AfgeleidVeld{
			{
				Naam:                "label",
				Description:         "Testafleiding over U.aaa, U.bbb en W.heel",
				GoType:              "string",
				AfleidingsregelTaal: "cel",
				Afleidingsregel:     "U.aaa + (U.bbb != null ? ' [bbb=ja]' : '') + (W.heel != null ? ' · heel=' + W.heel : '')",
				IsWeergaveVeld:      true,
			},
		},
	}
	MetaRegistry["A_U"] = TypeMeta{
		Typenaam:               "A_U",
		Klassenaam:             "U",
		Description:            "Enkelvoudig gegevenselement van A met formele tijdlijn.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "abuvwxy",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "A_U_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "u",
		Padnaam:                "us",
		Meervoud:               "us",
		Factory:                func() Representatie { return &A_U_Input{} },
		Tabelnaam:              "a_u",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &A_U{} },
		DBSliceFactory:         func() any { return &[]A_U{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie:      &V3Positie{X: -780, Y: 855},
			SourceHandle: "source-bottom",
			TargetHandle: "target-top",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "A_U_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["A_V"] = TypeMeta{
		Typenaam:               "A_V",
		Klassenaam:             "V",
		Description:            "Meervoudig gegevenselement van A met onder andere een datumveld.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "abuvwxy",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "A_V_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "v",
		Padnaam:                "vs",
		Meervoud:               "vs",
		Factory:                func() Representatie { return &A_V_Input{} },
		Tabelnaam:              "a_v",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &A_V{} },
		DBSliceFactory:         func() any { return &[]A_V{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Meervoudig,
		Layout: &EditorLayout{
			Positie:      &V3Positie{X: -570, Y: 795},
			SourceHandle: "source-bottom",
			TargetHandle: "target-top",
			UseEdges: []V3UseEdge{
				{Doel: "ABCEnum", ID: "A_V-->ABCEnum", SourceHandle: "source-bottom", TargetHandle: "target-top"},
			},
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "A_V_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["A_W"] = TypeMeta{
		Typenaam:               "A_W",
		Klassenaam:             "W",
		Description:            "Meervoudig gegevenselement van A met numerieke waarden.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            true,
		Domein:                 "abuvwxy",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "A_W_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "w",
		Padnaam:                "ws",
		Meervoud:               "ws",
		Factory:                func() Representatie { return &A_W_Input{} },
		Tabelnaam:              "a_w",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &A_W{} },
		DBSliceFactory:         func() any { return &[]A_W{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Meervoudig,
		Layout: &EditorLayout{
			Positie:      &V3Positie{X: -360, Y: 825},
			SourceHandle: "source-bottom",
			TargetHandle: "target-top",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "A_W_Data", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "A_W_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "A_W_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Rel_A_B"] = TypeMeta{
		Typenaam:                  "Rel_A_B",
		Klassenaam:                "Rel_A_B",
		Description:               "Relatie tussen A en B, meervoudig voorkomend per A en met relatieve relatie-id.",
		Metatype:                  MetatypeRelatie,
		IsMaterieel:               true,
		Domein:                    "abuvwxy",
		GESubtype:                 GESubtypeHub,
		DataTypenaam:              "Rel_A_B_Data",
		Kleur:                     "",
		Veldnaam:                  "rel_a_b",
		Padnaam:                   "rel_a_bs",
		Meervoud:                  "rel_a_bs",
		Factory:                   func() Representatie { return &Rel_A_B_Input{} },
		Tabelnaam:                 "rel_a_b",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &Rel_A_B{} },
		DBSliceFactory:            func() any { return &[]Rel_A_B{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "a_id",
		SecondaireEntiteitIDKolom: "b_id",
		Momentvoorkomen:           Meervoudig,
		Layout: &EditorLayout{
			Positie:      &V3Positie{X: -165, Y: 540},
			SourceHandle: "source-right",
			TargetHandle: "target-left",
			UseEdges: []V3UseEdge{
				{Doel: "RelABSoort", ID: "Rel_A_B-->RelABSoort", SourceHandle: "source-bottom", TargetHandle: "target-top"},
			},
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Rel_A_B_Data", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Rel_A_B_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Rel_A_B_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["A_U_Data"] = TypeMeta{
		Typenaam:               "A_U_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van A_U.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "a_u_data",
		Padnaam:                "a_u_data",
		Meervoud:               "a_u_data",
		Factory:                func() Representatie { return &A_U_Data{} },
		SliceFactory:           func() any { return &[]A_U_Data{} },
		Tabelnaam:              "a_u_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &A_U_Data{} },
		DBSliceFactory:         func() any { return &[]A_U_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "A_U",
	}
	MetaRegistry["A_V_Data"] = TypeMeta{
		Typenaam:               "A_V_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van A_V.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "a_v_data",
		Padnaam:                "a_v_data",
		Meervoud:               "a_v_data",
		Factory:                func() Representatie { return &A_V_Data{} },
		SliceFactory:           func() any { return &[]A_V_Data{} },
		Tabelnaam:              "a_v_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &A_V_Data{} },
		DBSliceFactory:         func() any { return &[]A_V_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "A_V",
	}
	MetaRegistry["A_W_Data"] = TypeMeta{
		Typenaam:               "A_W_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van A_W.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "a_w_data",
		Padnaam:                "a_w_data",
		Meervoud:               "a_w_data",
		Factory:                func() Representatie { return &A_W_Data{} },
		SliceFactory:           func() any { return &[]A_W_Data{} },
		Tabelnaam:              "a_w_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &A_W_Data{} },
		DBSliceFactory:         func() any { return &[]A_W_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "A_W",
	}
	MetaRegistry["Rel_A_B_Data"] = TypeMeta{
		Typenaam:               "Rel_A_B_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Rel_A_B.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "rel_a_b_data",
		Padnaam:                "rel_a_b_data",
		Meervoud:               "rel_a_b_data",
		Factory:                func() Representatie { return &Rel_A_B_Data{} },
		SliceFactory:           func() any { return &[]Rel_A_B_Data{} },
		Tabelnaam:              "rel_a_b_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Rel_A_B_Data{} },
		DBSliceFactory:         func() any { return &[]Rel_A_B_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Rel_A_B",
	}
	MetaRegistry["A_Aanvang"] = TypeMeta{
		Typenaam:               "A_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van A.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "a_aanvang",
		Padnaam:                "a_aanvang",
		Meervoud:               "a_aanvang",
		Factory:                func() Representatie { return &A_Aanvang{} },
		SliceFactory:           func() any { return &[]A_Aanvang{} },
		Tabelnaam:              "a_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &A_Aanvang{} },
		DBSliceFactory:         func() any { return &[]A_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "A",
	}
	MetaRegistry["A_Einde"] = TypeMeta{
		Typenaam:               "A_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van A.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "a_einde",
		Padnaam:                "a_einde",
		Meervoud:               "a_einde",
		Factory:                func() Representatie { return &A_Einde{} },
		SliceFactory:           func() any { return &[]A_Einde{} },
		Tabelnaam:              "a_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &A_Einde{} },
		DBSliceFactory:         func() any { return &[]A_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "A",
	}
	MetaRegistry["A_W_Aanvang"] = TypeMeta{
		Typenaam:               "A_W_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van A_W.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "a_w_aanvang",
		Padnaam:                "a_w_aanvang",
		Meervoud:               "a_w_aanvang",
		Factory:                func() Representatie { return &A_W_Aanvang{} },
		SliceFactory:           func() any { return &[]A_W_Aanvang{} },
		Tabelnaam:              "a_w_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &A_W_Aanvang{} },
		DBSliceFactory:         func() any { return &[]A_W_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "A_W",
	}
	MetaRegistry["A_W_Einde"] = TypeMeta{
		Typenaam:               "A_W_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van A_W.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "a_w_einde",
		Padnaam:                "a_w_einde",
		Meervoud:               "a_w_einde",
		Factory:                func() Representatie { return &A_W_Einde{} },
		SliceFactory:           func() any { return &[]A_W_Einde{} },
		Tabelnaam:              "a_w_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &A_W_Einde{} },
		DBSliceFactory:         func() any { return &[]A_W_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "A_W",
	}
	MetaRegistry["Rel_A_B_Aanvang"] = TypeMeta{
		Typenaam:               "Rel_A_B_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Rel_A_B.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "rel_a_b_aanvang",
		Padnaam:                "rel_a_b_aanvang",
		Meervoud:               "rel_a_b_aanvang",
		Factory:                func() Representatie { return &Rel_A_B_Aanvang{} },
		SliceFactory:           func() any { return &[]Rel_A_B_Aanvang{} },
		Tabelnaam:              "rel_a_b_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Rel_A_B_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Rel_A_B_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Rel_A_B",
	}
	MetaRegistry["Rel_A_B_Einde"] = TypeMeta{
		Typenaam:               "Rel_A_B_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Rel_A_B.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "rel_a_b_einde",
		Padnaam:                "rel_a_b_einde",
		Meervoud:               "rel_a_b_einde",
		Factory:                func() Representatie { return &Rel_A_B_Einde{} },
		SliceFactory:           func() any { return &[]Rel_A_B_Einde{} },
		Tabelnaam:              "rel_a_b_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Rel_A_B_Einde{} },
		DBSliceFactory:         func() any { return &[]Rel_A_B_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Rel_A_B",
	}
	MetaRegistry["B"] = TypeMeta{
		Typenaam:               "B",
		Klassenaam:             "B",
		Description:            "Entiteit B met materiele tijdlijn en onderliggende representaties X en Y.",
		Metatype:               MetatypeEntiteit,
		IsMaterieel:            true,
		Domein:                 "abuvwxy",
		Kleur:                  "#fecaca",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 210, Y: 435}},
		Veldnaam:               "b",
		Padnaam:                "bs",
		Meervoud:               "bs",
		Factory:                func() Representatie { return &B{} },
		SliceFactory:           func() any { return &[]B{} },
		Tabelnaam:              "b",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &B{} },
		DBSliceFactory:         func() any { return &[]B{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Xs", JSONRolnaam: "xs", Doeltype: "B_X", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Ys", JSONRolnaam: "ys", Doeltype: "B_Y", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "B_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "B_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["B_X"] = TypeMeta{
		Typenaam:               "B_X",
		Klassenaam:             "X",
		Description:            "Enkelvoudig gegevenselement van B met twee tekstvelden.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "abuvwxy",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "B_X_Data",
		Kleur:                  "#fecaca",
		Veldnaam:               "x",
		Padnaam:                "xs",
		Meervoud:               "xs",
		Factory:                func() Representatie { return &B_X_Input{} },
		Tabelnaam:              "b_x",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &B_X{} },
		DBSliceFactory:         func() any { return &[]B_X{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "b_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie:      &V3Positie{X: 105, Y: 840},
			SourceHandle: "source-bottom",
			TargetHandle: "target-top",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "B_X_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["B_Y"] = TypeMeta{
		Typenaam:               "B_Y",
		Klassenaam:             "Y",
		Description:            "Enkelvoudig gegevenselement van B met een tekstveld.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "abuvwxy",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "B_Y_Data",
		Kleur:                  "#fecaca",
		Veldnaam:               "y",
		Padnaam:                "ys",
		Meervoud:               "ys",
		Factory:                func() Representatie { return &B_Y_Input{} },
		Tabelnaam:              "b_y",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &B_Y{} },
		DBSliceFactory:         func() any { return &[]B_Y{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "b_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie:      &V3Positie{X: 360, Y: 855},
			SourceHandle: "source-bottom",
			TargetHandle: "target-top",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "B_Y_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["B_X_Data"] = TypeMeta{
		Typenaam:               "B_X_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van B_X.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fecaca",
		Veldnaam:               "b_x_data",
		Padnaam:                "b_x_data",
		Meervoud:               "b_x_data",
		Factory:                func() Representatie { return &B_X_Data{} },
		SliceFactory:           func() any { return &[]B_X_Data{} },
		Tabelnaam:              "b_x_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &B_X_Data{} },
		DBSliceFactory:         func() any { return &[]B_X_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "b_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "B_X",
	}
	MetaRegistry["B_Y_Data"] = TypeMeta{
		Typenaam:               "B_Y_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van B_Y.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fecaca",
		Veldnaam:               "b_y_data",
		Padnaam:                "b_y_data",
		Meervoud:               "b_y_data",
		Factory:                func() Representatie { return &B_Y_Data{} },
		SliceFactory:           func() any { return &[]B_Y_Data{} },
		Tabelnaam:              "b_y_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &B_Y_Data{} },
		DBSliceFactory:         func() any { return &[]B_Y_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "b_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "B_Y",
	}
	MetaRegistry["B_Aanvang"] = TypeMeta{
		Typenaam:               "B_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van B.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#fecaca",
		Veldnaam:               "b_aanvang",
		Padnaam:                "b_aanvang",
		Meervoud:               "b_aanvang",
		Factory:                func() Representatie { return &B_Aanvang{} },
		SliceFactory:           func() any { return &[]B_Aanvang{} },
		Tabelnaam:              "b_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &B_Aanvang{} },
		DBSliceFactory:         func() any { return &[]B_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "b_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "B",
	}
	MetaRegistry["B_Einde"] = TypeMeta{
		Typenaam:               "B_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van B.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#fecaca",
		Veldnaam:               "b_einde",
		Padnaam:                "b_einde",
		Meervoud:               "b_einde",
		Factory:                func() Representatie { return &B_Einde{} },
		SliceFactory:           func() any { return &[]B_Einde{} },
		Tabelnaam:              "b_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &B_Einde{} },
		DBSliceFactory:         func() any { return &[]B_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "b_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "B",
	}
	MetaRegistry["C"] = TypeMeta{
		Typenaam:               "C",
		Klassenaam:             "C",
		Description:            "",
		Metatype:               MetatypeEntiteit,
		IsMaterieel:            false,
		Domein:                 "abuvwxy",
		Kleur:                  "#e298ec",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 795, Y: 420}},
		Veldnaam:               "c",
		Padnaam:                "cs",
		Meervoud:               "cs",
		Factory:                func() Representatie { return &C{} },
		SliceFactory:           func() any { return &[]C{} },
		Tabelnaam:              "c",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &C{} },
		DBSliceFactory:         func() any { return &[]C{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "CGes", JSONRolnaam: "c_ges", Doeltype: "C_C_GE", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "RelCBs", JSONRolnaam: "rel_c_bs", Doeltype: "Rel_C_B", Momentvoorkomen: Meervoudig},
		},
		AfgeleideVelden: []AfgeleidVeld{
			{
				Naam:                "relveldTest",
				GoType:              "string",
				AfleidingsregelTaal: "cel",
				Afleidingsregel:     "Rel_C_B.relveld",
				IsWeergaveVeld:      true,
			},
		},
	}
	MetaRegistry["C_C_GE"] = TypeMeta{
		Typenaam:               "C_C_GE",
		Klassenaam:             "GE",
		Description:            "",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "abuvwxy",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "C_C_GE_Data",
		Kleur:                  "#e298ec",
		Veldnaam:               "ge",
		Padnaam:                "c_ges",
		Meervoud:               "c_ges",
		Factory:                func() Representatie { return &C_C_GE_Input{} },
		Tabelnaam:              "c_c_ge",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &C_C_GE{} },
		DBSliceFactory:         func() any { return &[]C_C_GE{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "c_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie:      &V3Positie{X: 1095, Y: 585},
			SourceHandle: "source-right",
			TargetHandle: "target-left",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "C_C_GE_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Rel_C_B"] = TypeMeta{
		Typenaam:                  "Rel_C_B",
		Klassenaam:                "Rel_C_B",
		Description:               "",
		Metatype:                  MetatypeRelatie,
		IsMaterieel:               false,
		Domein:                    "abuvwxy",
		GESubtype:                 GESubtypeHub,
		DataTypenaam:              "Rel_C_B_Data",
		Kleur:                     "",
		Veldnaam:                  "rel_c_b",
		Padnaam:                   "rel_c_bs",
		Meervoud:                  "rel_c_bs",
		Factory:                   func() Representatie { return &Rel_C_B_Input{} },
		Tabelnaam:                 "rel_c_b",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &Rel_C_B{} },
		DBSliceFactory:            func() any { return &[]Rel_C_B{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "c_id",
		SecondaireEntiteitIDKolom: "b_id",
		Momentvoorkomen:           Meervoudig,
		Layout:                    &EditorLayout{Positie: &V3Positie{X: 510, Y: 495}},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Rel_C_B_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["C_C_GE_Data"] = TypeMeta{
		Typenaam:               "C_C_GE_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van C_C_GE.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#e298ec",
		Veldnaam:               "c_c_ge_data",
		Padnaam:                "c_c_ge_data",
		Meervoud:               "c_c_ge_data",
		Factory:                func() Representatie { return &C_C_GE_Data{} },
		SliceFactory:           func() any { return &[]C_C_GE_Data{} },
		Tabelnaam:              "c_c_ge_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &C_C_GE_Data{} },
		DBSliceFactory:         func() any { return &[]C_C_GE_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "c_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "C_C_GE",
	}
	MetaRegistry["Rel_C_B_Data"] = TypeMeta{
		Typenaam:               "Rel_C_B_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Rel_C_B.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#e298ec",
		Veldnaam:               "rel_c_b_data",
		Padnaam:                "rel_c_b_data",
		Meervoud:               "rel_c_b_data",
		Factory:                func() Representatie { return &Rel_C_B_Data{} },
		SliceFactory:           func() any { return &[]Rel_C_B_Data{} },
		Tabelnaam:              "rel_c_b_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Rel_C_B_Data{} },
		DBSliceFactory:         func() any { return &[]Rel_C_B_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "c_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Rel_C_B",
	}
	MetaRegistry["C_sub"] = TypeMeta{
		Typenaam:                       "C_sub",
		Klassenaam:                     "C_sub",
		Description:                    "",
		Metatype:                       MetatypeEntiteit,
		IsMaterieel:                    false,
		Domein:                         "abuvwxy",
		Kleur:                          "#d2c1fb",
		Layout:                         &EditorLayout{Positie: &V3Positie{X: 795, Y: 600}},
		Veldnaam:                       "c_sub",
		Padnaam:                        "c_subs",
		Meervoud:                       "c subs",
		Factory:                        func() Representatie { return &C_sub{} },
		SliceFactory:                   func() any { return &[]C_sub{} },
		Tabelnaam:                      "c_sub",
		IDKolom:                        "id",
		DBFactory:                      func() Representatie { return &C_sub{} },
		DBSliceFactory:                 func() any { return &[]C_sub{} },
		HeeftPFK:                       false,
		RelatieveAutoincrement:         false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{},
		AfgeleideVelden: []AfgeleidVeld{
			{
				Naam:                "superveld",
				GoType:              "string",
				AfleidingsregelTaal: "cel",
				Afleidingsregel:     "C.C_GE.superveld",
				IsWeergaveVeld:      true,
			},
		},
	}

	// Referentielijst-instantie metadata + editor-posities
	ReferentielijstInstantieRegistry["AdellijkeTitels"] = ReferentielijstInstantieInfo{
		Naam:   "",
		Layout: &EditorLayout{Positie: &V3Positie{X: 1920, Y: -330}},
	}
	ReferentielijstInstantieRegistry["Landenlijst"] = ReferentielijstInstantieInfo{
		Naam:   "",
		Layout: &EditorLayout{Positie: &V3Positie{X: 1005, Y: -319.5}},
	}
}
