package model

// Additieve MetaRegistry-entries — voegt types toe aan de bestaande MetaRegistry.
// Gegenereerd door cmd/codegen — niet handmatig bewerken.

func initConfiguratieMetaRegistry() {
	MetaRegistry["FormulierDefinitie"] = TypeMeta{
		Typenaam:               "FormulierDefinitie",
		Klassenaam:             "FormulierDefinitie",
		Description:            "Formulierdefinitie voor custom layouts van entiteitsformulieren. Bevat metadata (naam, status, doeltype) en een JSON layout-boom. Bitemporeel: wijzigingen zijn traceerbaar en corrigeerbaar via registraties.",
		Metatype:               MetatypeEntiteit,
		IsMaterieel:            true,
		Domein:                 "configuratie",
		Kleur:                  "#c4b5fd",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 2650, Y: 80}},
		Veldnaam:               "formulierdefinitie",
		Padnaam:                "formulier_definities",
		Meervoud:               "formulier definities",
		Factory:                func() Representatie { return &FormulierDefinitie{} },
		SliceFactory:           func() any { return &[]FormulierDefinitie{} },
		Tabelnaam:              "formulierdefinitie",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &FormulierDefinitie{} },
		DBSliceFactory:         func() any { return &[]FormulierDefinitie{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "FormulierDefinitieMetas", JSONRolnaam: "formulier_definitie_metas", Doeltype: "FormulierDefinitie_Meta", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "FormulierDefinitieLayouts", JSONRolnaam: "formulier_definitie_layouts", Doeltype: "FormulierDefinitie_Layout", Momentvoorkomen: Meervoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "FormulierDefinitie_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "FormulierDefinitie_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["FormulierDefinitie_Meta"] = TypeMeta{
		Typenaam:               "FormulierDefinitie_Meta",
		Klassenaam:             "Meta",
		Description:            "Metadata van de formulierdefinitie: naam, beschrijving, doeltype en status.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "configuratie",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "FormulierDefinitie_Meta_Data",
		Kleur:                  "#c4b5fd",
		Veldnaam:               "formulierdefinitie_meta",
		Padnaam:                "formulier_definitie_metas",
		Meervoud:               "formulier_definitie_metas",
		Factory:                func() Representatie { return &FormulierDefinitie_Meta_Input{} },
		Tabelnaam:              "formulierdefinitie_meta",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &FormulierDefinitie_Meta{} },
		DBSliceFactory:         func() any { return &[]FormulierDefinitie_Meta{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "formulierdefinitie_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 2500, Y: 330},
			EdgeID:  "FormulierDefinitie->FormulierDefinitie_Meta",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "FormulierDefinitie_Meta_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["FormulierDefinitie_Layout"] = TypeMeta{
		Typenaam:               "FormulierDefinitie_Layout",
		Klassenaam:             "Layout",
		Description:            "De layout-boom van het formulier als JSON-structuur. Bevat groepen, rijen, velden en conditionele elementen.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "configuratie",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "FormulierDefinitie_Layout_Data",
		Kleur:                  "#c4b5fd",
		Veldnaam:               "layout",
		Padnaam:                "formulier_definitie_layouts",
		Meervoud:               "formulier_definitie_layouts",
		Factory:                func() Representatie { return &FormulierDefinitie_Layout_Input{} },
		Tabelnaam:              "formulierdefinitie_layout",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &FormulierDefinitie_Layout{} },
		DBSliceFactory:         func() any { return &[]FormulierDefinitie_Layout{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "formulierdefinitie_id",
		Momentvoorkomen:        Meervoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 2750, Y: 330},
			EdgeID:  "FormulierDefinitie->FormulierDefinitie_Layout",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "FormulierDefinitie_Layout_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["FormulierDefinitie_Meta_Data"] = TypeMeta{
		Typenaam:               "FormulierDefinitie_Meta_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van FormulierDefinitie_Meta.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#c4b5fd",
		Veldnaam:               "formulierdefinitie_meta_data",
		Padnaam:                "formulierdefinitie_meta_data",
		Meervoud:               "formulierdefinitie_meta_data",
		Factory:                func() Representatie { return &FormulierDefinitie_Meta_Data{} },
		SliceFactory:           func() any { return &[]FormulierDefinitie_Meta_Data{} },
		Tabelnaam:              "formulierdefinitie_meta_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &FormulierDefinitie_Meta_Data{} },
		DBSliceFactory:         func() any { return &[]FormulierDefinitie_Meta_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "formulierdefinitie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "FormulierDefinitie_Meta",
	}
	MetaRegistry["FormulierDefinitie_Layout_Data"] = TypeMeta{
		Typenaam:               "FormulierDefinitie_Layout_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van FormulierDefinitie_Layout.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#c4b5fd",
		Veldnaam:               "formulierdefinitie_layout_data",
		Padnaam:                "formulierdefinitie_layout_data",
		Meervoud:               "formulierdefinitie_layout_data",
		Factory:                func() Representatie { return &FormulierDefinitie_Layout_Data{} },
		SliceFactory:           func() any { return &[]FormulierDefinitie_Layout_Data{} },
		Tabelnaam:              "formulierdefinitie_layout_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &FormulierDefinitie_Layout_Data{} },
		DBSliceFactory:         func() any { return &[]FormulierDefinitie_Layout_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "formulierdefinitie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "FormulierDefinitie_Layout",
	}
	MetaRegistry["FormulierDefinitie_Aanvang"] = TypeMeta{
		Typenaam:               "FormulierDefinitie_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van FormulierDefinitie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#c4b5fd",
		Veldnaam:               "formulierdefinitie_aanvang",
		Padnaam:                "formulierdefinitie_aanvang",
		Meervoud:               "formulierdefinitie_aanvang",
		Factory:                func() Representatie { return &FormulierDefinitie_Aanvang{} },
		SliceFactory:           func() any { return &[]FormulierDefinitie_Aanvang{} },
		Tabelnaam:              "formulierdefinitie_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &FormulierDefinitie_Aanvang{} },
		DBSliceFactory:         func() any { return &[]FormulierDefinitie_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "formulierdefinitie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "FormulierDefinitie",
	}
	MetaRegistry["FormulierDefinitie_Einde"] = TypeMeta{
		Typenaam:               "FormulierDefinitie_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van FormulierDefinitie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#c4b5fd",
		Veldnaam:               "formulierdefinitie_einde",
		Padnaam:                "formulierdefinitie_einde",
		Meervoud:               "formulierdefinitie_einde",
		Factory:                func() Representatie { return &FormulierDefinitie_Einde{} },
		SliceFactory:           func() any { return &[]FormulierDefinitie_Einde{} },
		Tabelnaam:              "formulierdefinitie_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &FormulierDefinitie_Einde{} },
		DBSliceFactory:         func() any { return &[]FormulierDefinitie_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "formulierdefinitie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "FormulierDefinitie",
	}
	MetaRegistry["WeergaveDefinitie"] = TypeMeta{
		Typenaam:               "WeergaveDefinitie",
		Klassenaam:             "WeergaveDefinitie",
		Description:            "Weergavedefinitie voor publicatie-views op entiteitsdata. Bevat metadata (naam, doeltype, status), een tabelconfiguratie (kolommen, sortering) en een detail-template met veldpad-inserts. Bitemporeel: wijzigingen zijn traceerbaar en corrigeerbaar via registraties.",
		Metatype:               MetatypeEntiteit,
		IsMaterieel:            true,
		Domein:                 "configuratie",
		Kleur:                  "#a5f3fc",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 3270, Y: 75}},
		Veldnaam:               "weergavedefinitie",
		Padnaam:                "weergave_definities",
		Meervoud:               "weergave definities",
		Factory:                func() Representatie { return &WeergaveDefinitie{} },
		SliceFactory:           func() any { return &[]WeergaveDefinitie{} },
		Tabelnaam:              "weergavedefinitie",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &WeergaveDefinitie{} },
		DBSliceFactory:         func() any { return &[]WeergaveDefinitie{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "WeergaveDefinitieMetas", JSONRolnaam: "weergave_definitie_metas", Doeltype: "WeergaveDefinitie_Meta", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "WeergaveDefinitieTabelConfigs", JSONRolnaam: "weergave_definitie_tabel_configs", Doeltype: "WeergaveDefinitie_TabelConfig", Momentvoorkomen: Meervoudig},
			{Rolnaam: "WeergaveDefinitieDetailTemplates", JSONRolnaam: "weergave_definitie_detail_templates", Doeltype: "WeergaveDefinitie_DetailTemplate", Momentvoorkomen: Meervoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "WeergaveDefinitie_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "WeergaveDefinitie_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["WeergaveDefinitie_Meta"] = TypeMeta{
		Typenaam:               "WeergaveDefinitie_Meta",
		Klassenaam:             "Meta",
		Description:            "Metadata van de weergavedefinitie: naam, beschrijving, doeltype en status.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "configuratie",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "WeergaveDefinitie_Meta_Data",
		Kleur:                  "#a5f3fc",
		Veldnaam:               "weergavedefinitie_meta",
		Padnaam:                "weergave_definitie_metas",
		Meervoud:               "weergave_definitie_metas",
		Factory:                func() Representatie { return &WeergaveDefinitie_Meta_Input{} },
		Tabelnaam:              "weergavedefinitie_meta",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &WeergaveDefinitie_Meta{} },
		DBSliceFactory:         func() any { return &[]WeergaveDefinitie_Meta{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "weergavedefinitie_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 3120, Y: 325},
			EdgeID:  "WeergaveDefinitie->WeergaveDefinitie_Meta",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "WeergaveDefinitie_Meta_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["WeergaveDefinitie_TabelConfig"] = TypeMeta{
		Typenaam:               "WeergaveDefinitie_TabelConfig",
		Klassenaam:             "TabelConfig",
		Description:            "Configuratie van de tabelweergave: kolomdefinities (veldpad, label, breedte, sorteerbaar, filterbaar), standaardsortering en aantal rijen per pagina.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "configuratie",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "WeergaveDefinitie_TabelConfig_Data",
		Kleur:                  "#a5f3fc",
		Veldnaam:               "tabelconfig",
		Padnaam:                "weergave_definitie_tabel_configs",
		Meervoud:               "weergave_definitie_tabel_configs",
		Factory:                func() Representatie { return &WeergaveDefinitie_TabelConfig_Input{} },
		Tabelnaam:              "weergavedefinitie_tabelconfig",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &WeergaveDefinitie_TabelConfig{} },
		DBSliceFactory:         func() any { return &[]WeergaveDefinitie_TabelConfig{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "weergavedefinitie_id",
		Momentvoorkomen:        Meervoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 3370, Y: 325},
			EdgeID:  "WeergaveDefinitie->WeergaveDefinitie_TabelConfig",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "WeergaveDefinitie_TabelConfig_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["WeergaveDefinitie_DetailTemplate"] = TypeMeta{
		Typenaam:               "WeergaveDefinitie_DetailTemplate",
		Klassenaam:             "DetailTemplate",
		Description:            "Template voor de detail-pagina met {{veldpad}} inserts. Wordt gerenderd als read-only publicatieweergave.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "configuratie",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "WeergaveDefinitie_DetailTemplate_Data",
		Kleur:                  "#a5f3fc",
		Veldnaam:               "detailtemplate",
		Padnaam:                "weergave_definitie_detail_templates",
		Meervoud:               "weergave_definitie_detail_templates",
		Factory:                func() Representatie { return &WeergaveDefinitie_DetailTemplate_Input{} },
		Tabelnaam:              "weergavedefinitie_detailtemplate",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &WeergaveDefinitie_DetailTemplate{} },
		DBSliceFactory:         func() any { return &[]WeergaveDefinitie_DetailTemplate{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "weergavedefinitie_id",
		Momentvoorkomen:        Meervoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 3620, Y: 325},
			EdgeID:  "WeergaveDefinitie->WeergaveDefinitie_DetailTemplate",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "WeergaveDefinitie_DetailTemplate_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["WeergaveDefinitie_Meta_Data"] = TypeMeta{
		Typenaam:               "WeergaveDefinitie_Meta_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van WeergaveDefinitie_Meta.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#a5f3fc",
		Veldnaam:               "weergavedefinitie_meta_data",
		Padnaam:                "weergavedefinitie_meta_data",
		Meervoud:               "weergavedefinitie_meta_data",
		Factory:                func() Representatie { return &WeergaveDefinitie_Meta_Data{} },
		SliceFactory:           func() any { return &[]WeergaveDefinitie_Meta_Data{} },
		Tabelnaam:              "weergavedefinitie_meta_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &WeergaveDefinitie_Meta_Data{} },
		DBSliceFactory:         func() any { return &[]WeergaveDefinitie_Meta_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "weergavedefinitie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "WeergaveDefinitie_Meta",
	}
	MetaRegistry["WeergaveDefinitie_TabelConfig_Data"] = TypeMeta{
		Typenaam:               "WeergaveDefinitie_TabelConfig_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van WeergaveDefinitie_TabelConfig.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#a5f3fc",
		Veldnaam:               "weergavedefinitie_tabelconfig_data",
		Padnaam:                "weergavedefinitie_tabelconfig_data",
		Meervoud:               "weergavedefinitie_tabelconfig_data",
		Factory:                func() Representatie { return &WeergaveDefinitie_TabelConfig_Data{} },
		SliceFactory:           func() any { return &[]WeergaveDefinitie_TabelConfig_Data{} },
		Tabelnaam:              "weergavedefinitie_tabelconfig_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &WeergaveDefinitie_TabelConfig_Data{} },
		DBSliceFactory:         func() any { return &[]WeergaveDefinitie_TabelConfig_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "weergavedefinitie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "WeergaveDefinitie_TabelConfig",
	}
	MetaRegistry["WeergaveDefinitie_DetailTemplate_Data"] = TypeMeta{
		Typenaam:               "WeergaveDefinitie_DetailTemplate_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van WeergaveDefinitie_DetailTemplate.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#a5f3fc",
		Veldnaam:               "weergavedefinitie_detailtemplate_data",
		Padnaam:                "weergavedefinitie_detailtemplate_data",
		Meervoud:               "weergavedefinitie_detailtemplate_data",
		Factory:                func() Representatie { return &WeergaveDefinitie_DetailTemplate_Data{} },
		SliceFactory:           func() any { return &[]WeergaveDefinitie_DetailTemplate_Data{} },
		Tabelnaam:              "weergavedefinitie_detailtemplate_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &WeergaveDefinitie_DetailTemplate_Data{} },
		DBSliceFactory:         func() any { return &[]WeergaveDefinitie_DetailTemplate_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "weergavedefinitie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "WeergaveDefinitie_DetailTemplate",
	}
	MetaRegistry["WeergaveDefinitie_Aanvang"] = TypeMeta{
		Typenaam:               "WeergaveDefinitie_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van WeergaveDefinitie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#a5f3fc",
		Veldnaam:               "weergavedefinitie_aanvang",
		Padnaam:                "weergavedefinitie_aanvang",
		Meervoud:               "weergavedefinitie_aanvang",
		Factory:                func() Representatie { return &WeergaveDefinitie_Aanvang{} },
		SliceFactory:           func() any { return &[]WeergaveDefinitie_Aanvang{} },
		Tabelnaam:              "weergavedefinitie_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &WeergaveDefinitie_Aanvang{} },
		DBSliceFactory:         func() any { return &[]WeergaveDefinitie_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "weergavedefinitie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "WeergaveDefinitie",
	}
	MetaRegistry["WeergaveDefinitie_Einde"] = TypeMeta{
		Typenaam:               "WeergaveDefinitie_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van WeergaveDefinitie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#a5f3fc",
		Veldnaam:               "weergavedefinitie_einde",
		Padnaam:                "weergavedefinitie_einde",
		Meervoud:               "weergavedefinitie_einde",
		Factory:                func() Representatie { return &WeergaveDefinitie_Einde{} },
		SliceFactory:           func() any { return &[]WeergaveDefinitie_Einde{} },
		Tabelnaam:              "weergavedefinitie_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &WeergaveDefinitie_Einde{} },
		DBSliceFactory:         func() any { return &[]WeergaveDefinitie_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "weergavedefinitie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "WeergaveDefinitie",
	}

	// Referentielijst-instantie metadata + editor-posities
	ReferentielijstInstantieRegistry["AdellijkeTitels"] = ReferentielijstInstantieInfo{
		Naam:   "",
		Layout: &EditorLayout{Positie: &V3Positie{X: 1920, Y: -330}},
	}
	ReferentielijstInstantieRegistry["Landenlijst"] = ReferentielijstInstantieInfo{
		Naam:   "",
		Layout: &EditorLayout{Positie: &V3Positie{X: 1005, Y: -319.5}},
	}
}
