package model

// Additieve MetaRegistry-entries — voegt types toe aan de bestaande MetaRegistry.
// Gegenereerd door cmd/codegen — niet handmatig bewerken.

func initRegisterMetaRegistry() {
	MetaRegistry["Land"] = TypeMeta{
		Typenaam:               "Land",
		Klassenaam:             "Land",
		Description:            "Referentielijst-item: individueel land.",
		Metatype:               MetatypeEntiteit,
		EntiteitSubtype:        EntiteitSubtypeReferentielijstItem,
		IsMaterieel:            true,
		Domein:                 "register",
		Kleur:                  "#fde68a",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 1290, Y: -135}},
		Veldnaam:               "land",
		Padnaam:                "landen",
		Meervoud:               "landen",
		Factory:                func() Representatie { return &Land{} },
		SliceFactory:           func() any { return &[]Land{} },
		Tabelnaam:              "land",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &Land{} },
		DBSliceFactory:         func() any { return &[]Land{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Landcodes", JSONRolnaam: "landcodes", Doeltype: "Land_Landcode", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Landnamen", JSONRolnaam: "landnamen", Doeltype: "Land_Landnaam", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Land_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Land_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Land_Landcode"] = TypeMeta{
		Typenaam:               "Land_Landcode",
		Klassenaam:             "Landcode",
		Description:            "Enkelvoudig gegevenselement landcode van Land.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "register",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Land_Landcode_Data",
		Kleur:                  "#fde68a",
		Veldnaam:               "landcode",
		Padnaam:                "landcodes",
		Meervoud:               "landcodes",
		Factory:                func() Representatie { return &Land_Landcode_Input{} },
		Tabelnaam:              "land_landcode",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Land_Landcode{} },
		DBSliceFactory:         func() any { return &[]Land_Landcode{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "land_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie:      &V3Positie{X: 1170, Y: 75},
			EdgeID:       "edge_1774646153149_10",
			SourceHandle: "bottom",
			TargetHandle: "top",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Land_Landcode_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Land_Landnaam"] = TypeMeta{
		Typenaam:               "Land_Landnaam",
		Klassenaam:             "Landnaam",
		Description:            "Enkelvoudig gegevenselement landnaam van Land.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "register",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Land_Landnaam_Data",
		Kleur:                  "#fde68a",
		Veldnaam:               "landnaam",
		Padnaam:                "landnamen",
		Meervoud:               "landnamen",
		Factory:                func() Representatie { return &Land_Landnaam_Input{} },
		Tabelnaam:              "land_landnaam",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Land_Landnaam{} },
		DBSliceFactory:         func() any { return &[]Land_Landnaam{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "land_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie:      &V3Positie{X: 1418, Y: 75},
			EdgeID:       "edge_1774646072605_7",
			SourceHandle: "bottom",
			TargetHandle: "top",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Land_Landnaam_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Land_Landcode_Data"] = TypeMeta{
		Typenaam:               "Land_Landcode_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Land_Landcode.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fde68a",
		Veldnaam:               "land_landcode_data",
		Padnaam:                "land_landcode_data",
		Meervoud:               "land_landcode_data",
		Factory:                func() Representatie { return &Land_Landcode_Data{} },
		SliceFactory:           func() any { return &[]Land_Landcode_Data{} },
		Tabelnaam:              "land_landcode_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Land_Landcode_Data{} },
		DBSliceFactory:         func() any { return &[]Land_Landcode_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "land_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Land_Landcode",
	}
	MetaRegistry["Land_Landnaam_Data"] = TypeMeta{
		Typenaam:               "Land_Landnaam_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Land_Landnaam.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fde68a",
		Veldnaam:               "land_landnaam_data",
		Padnaam:                "land_landnaam_data",
		Meervoud:               "land_landnaam_data",
		Factory:                func() Representatie { return &Land_Landnaam_Data{} },
		SliceFactory:           func() any { return &[]Land_Landnaam_Data{} },
		Tabelnaam:              "land_landnaam_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Land_Landnaam_Data{} },
		DBSliceFactory:         func() any { return &[]Land_Landnaam_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "land_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Land_Landnaam",
	}
	MetaRegistry["Land_Aanvang"] = TypeMeta{
		Typenaam:               "Land_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Land.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#fde68a",
		Veldnaam:               "land_aanvang",
		Padnaam:                "land_aanvang",
		Meervoud:               "land_aanvang",
		Factory:                func() Representatie { return &Land_Aanvang{} },
		SliceFactory:           func() any { return &[]Land_Aanvang{} },
		Tabelnaam:              "land_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Land_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Land_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "land_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Land",
	}
	MetaRegistry["Land_Einde"] = TypeMeta{
		Typenaam:               "Land_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Land.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#fde68a",
		Veldnaam:               "land_einde",
		Padnaam:                "land_einde",
		Meervoud:               "land_einde",
		Factory:                func() Representatie { return &Land_Einde{} },
		SliceFactory:           func() any { return &[]Land_Einde{} },
		Tabelnaam:              "land_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Land_Einde{} },
		DBSliceFactory:         func() any { return &[]Land_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "land_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Land",
	}
	MetaRegistry["Referentielijst"] = TypeMeta{
		Typenaam:               "Referentielijst",
		Klassenaam:             "Referentielijst",
		Description:            "Generieke referentielijst-entiteit. Individuele lijsten (Landenlijst, EULidstaten, etc.) zijn records.",
		Metatype:               MetatypeEntiteit,
		EntiteitSubtype:        EntiteitSubtypeReferentielijst,
		IsMaterieel:            true,
		Domein:                 "register",
		Kleur:                  "#fef3c7",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 1440, Y: -720}},
		Veldnaam:               "referentielijst",
		Padnaam:                "referentielijsten",
		Meervoud:               "referentielijsten",
		Factory:                func() Representatie { return &Referentielijst{} },
		SliceFactory:           func() any { return &[]Referentielijst{} },
		Tabelnaam:              "referentielijst",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &Referentielijst{} },
		DBSliceFactory:         func() any { return &[]Referentielijst{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Referentielijstnamen", JSONRolnaam: "referentielijstnamen", Doeltype: "Referentielijst_Referentielijstnaam", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Referentielijstomschrijvingen", JSONRolnaam: "referentielijstomschrijvingen", Doeltype: "Referentielijst_Referentielijstomschrijving", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Visibilities", JSONRolnaam: "visibilities", Doeltype: "Referentielijst_ReferentielijstVisibility", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Internetadressen", JSONRolnaam: "internetadressen", Doeltype: "Referentielijst_ReferentielijstInternetadres", Momentvoorkomen: Meervoudig},
			{Rolnaam: "LandenlijstLanden", JSONRolnaam: "landenlijst_landen", Doeltype: "LandenlijstLand", Momentvoorkomen: Meervoudig},
			{Rolnaam: "AdellijkeTitelsTitels", JSONRolnaam: "adellijke_titels_titels", Doeltype: "AdellijkeTitelsTitel", Momentvoorkomen: Meervoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Referentielijst_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Referentielijst_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Referentielijst_Referentielijstnaam"] = TypeMeta{
		Typenaam:               "Referentielijst_Referentielijstnaam",
		Klassenaam:             "Referentielijstnaam",
		Description:            "Leesbare naam van een referentielijst.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "register",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Referentielijst_Referentielijstnaam_Data",
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstnaam",
		Padnaam:                "referentielijstnamen",
		Meervoud:               "referentielijstnamen",
		Factory:                func() Representatie { return &Referentielijst_Referentielijstnaam_Input{} },
		Tabelnaam:              "referentielijst_referentielijstnaam",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Referentielijst_Referentielijstnaam{} },
		DBSliceFactory:         func() any { return &[]Referentielijst_Referentielijstnaam{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie:      &V3Positie{X: 1815, Y: -975},
			EdgeID:       "Referentielijst->Referentielijst_Referentielijstnaam",
			SourceHandle: "right",
			TargetHandle: "left",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Referentielijst_Referentielijstnaam_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Referentielijst_Referentielijstomschrijving"] = TypeMeta{
		Typenaam:               "Referentielijst_Referentielijstomschrijving",
		Klassenaam:             "Referentielijstomschrijving",
		Description:            "Omschrijving van een referentielijst.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "register",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Referentielijst_Referentielijstomschrijving_Data",
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstomschrijving",
		Padnaam:                "referentielijstomschrijvingen",
		Meervoud:               "referentielijstomschrijvingen",
		Factory:                func() Representatie { return &Referentielijst_Referentielijstomschrijving_Input{} },
		Tabelnaam:              "referentielijst_referentielijstomschrijving",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Referentielijst_Referentielijstomschrijving{} },
		DBSliceFactory:         func() any { return &[]Referentielijst_Referentielijstomschrijving{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie:      &V3Positie{X: 1815, Y: -860.5},
			EdgeID:       "Referentielijst->Referentielijst_Referentielijstomschrijving",
			SourceHandle: "right",
			TargetHandle: "left",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Referentielijst_Referentielijstomschrijving_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Referentielijst_ReferentielijstVisibility"] = TypeMeta{
		Typenaam:               "Referentielijst_ReferentielijstVisibility",
		Klassenaam:             "ReferentielijstVisibility",
		Description:            "Domeinzichtbaarheid van een referentielijst (register, modelspecifiek, extern).",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "register",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Referentielijst_ReferentielijstVisibility_Data",
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstvisibility",
		Padnaam:                "visibilities",
		Meervoud:               "visibilities",
		Factory:                func() Representatie { return &Referentielijst_ReferentielijstVisibility_Input{} },
		Tabelnaam:              "referentielijst_referentielijstvisibility",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Referentielijst_ReferentielijstVisibility{} },
		DBSliceFactory:         func() any { return &[]Referentielijst_ReferentielijstVisibility{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie:      &V3Positie{X: 1815, Y: -746},
			EdgeID:       "Referentielijst->Referentielijst_ReferentielijstVisibility",
			SourceHandle: "right",
			TargetHandle: "left",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Referentielijst_ReferentielijstVisibility_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Referentielijst_ReferentielijstInternetadres"] = TypeMeta{
		Typenaam:               "Referentielijst_ReferentielijstInternetadres",
		Klassenaam:             "ReferentielijstInternetadres",
		Description:            "Internetadres (URL/URN) van een referentielijst.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "register",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Referentielijst_ReferentielijstInternetadres_Data",
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstinternetadres",
		Padnaam:                "internetadressen",
		Meervoud:               "internetadressen",
		Factory:                func() Representatie { return &Referentielijst_ReferentielijstInternetadres_Input{} },
		Tabelnaam:              "referentielijst_referentielijstinternetadres",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Referentielijst_ReferentielijstInternetadres{} },
		DBSliceFactory:         func() any { return &[]Referentielijst_ReferentielijstInternetadres{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Meervoudig,
		Layout: &EditorLayout{
			Positie:      &V3Positie{X: 1815, Y: -631.5},
			EdgeID:       "Referentielijst->Referentielijst_ReferentielijstInternetadres",
			SourceHandle: "right",
			TargetHandle: "left",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Referentielijst_ReferentielijstInternetadres_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["LandenlijstLand"] = TypeMeta{
		Typenaam:                  "LandenlijstLand",
		Klassenaam:                "LandenlijstLand",
		Description:               "Koppeling van een land aan referentielijst-instantie Landenlijst (referentielijst-items relatie).",
		Metatype:                  MetatypeRelatie,
		RelatieSubtype:            RelatieSubtypeReferentielijstItems,
		ReferentielijstInstantie:  "Landenlijst",
		IsMaterieel:               false,
		Domein:                    "register",
		GESubtype:                 GESubtypeHub,
		DataTypenaam:              "LandenlijstLand_Data",
		Kleur:                     "",
		Veldnaam:                  "landenlijstland",
		Padnaam:                   "landenlijst_landen",
		Meervoud:                  "landenlijst_landen",
		Factory:                   func() Representatie { return &LandenlijstLand_Input{} },
		Tabelnaam:                 "landenlijstland",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &LandenlijstLand{} },
		DBSliceFactory:            func() any { return &[]LandenlijstLand{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "referentielijst_id",
		SecondaireEntiteitIDKolom: "land_id",
		Momentvoorkomen:           Meervoudig,
		Layout: &EditorLayout{
			Positie:    &V3Positie{X: 1290, Y: -310.5},
			EdgeID:     "Referentielijst->LandenlijstLand",
			DoelEdgeID: "LandenlijstLand->Land",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "LandenlijstLand_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["AdellijkeTitelsTitel"] = TypeMeta{
		Typenaam:                  "AdellijkeTitelsTitel",
		Klassenaam:                "AdellijkeTitelsTitel",
		Description:               "Koppeling van een adellijke titel aan referentielijst-instantie AdellijkeTitels (referentielijst-items relatie).",
		Metatype:                  MetatypeRelatie,
		RelatieSubtype:            RelatieSubtypeReferentielijstItems,
		ReferentielijstInstantie:  "AdellijkeTitels",
		IsMaterieel:               false,
		Domein:                    "register",
		GESubtype:                 GESubtypeHub,
		DataTypenaam:              "AdellijkeTitelsTitel_Data",
		Kleur:                     "",
		Veldnaam:                  "adellijketitelstitel",
		Padnaam:                   "adellijke_titels_titels",
		Meervoud:                  "adellijke_titels_titels",
		Factory:                   func() Representatie { return &AdellijkeTitelsTitel_Input{} },
		Tabelnaam:                 "adellijketitelstitel",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &AdellijkeTitelsTitel{} },
		DBSliceFactory:            func() any { return &[]AdellijkeTitelsTitel{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "referentielijst_id",
		SecondaireEntiteitIDKolom: "adellijketitel_id",
		Momentvoorkomen:           Meervoudig,
		Layout: &EditorLayout{
			Positie:    &V3Positie{X: 1665, Y: -315},
			EdgeID:     "Referentielijst->AdellijkeTitelsTitel",
			DoelEdgeID: "AdellijkeTitelsTitel->AdellijkeTitel",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "AdellijkeTitelsTitel_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Referentielijst_Referentielijstnaam_Data"] = TypeMeta{
		Typenaam:               "Referentielijst_Referentielijstnaam_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Referentielijst_Referentielijstnaam.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijst_referentielijstnaam_data",
		Padnaam:                "referentielijst_referentielijstnaam_data",
		Meervoud:               "referentielijst_referentielijstnaam_data",
		Factory:                func() Representatie { return &Referentielijst_Referentielijstnaam_Data{} },
		SliceFactory:           func() any { return &[]Referentielijst_Referentielijstnaam_Data{} },
		Tabelnaam:              "referentielijst_referentielijstnaam_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Referentielijst_Referentielijstnaam_Data{} },
		DBSliceFactory:         func() any { return &[]Referentielijst_Referentielijstnaam_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijst_Referentielijstnaam",
	}
	MetaRegistry["Referentielijst_Referentielijstomschrijving_Data"] = TypeMeta{
		Typenaam:               "Referentielijst_Referentielijstomschrijving_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Referentielijst_Referentielijstomschrijving.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijst_referentielijstomschrijving_data",
		Padnaam:                "referentielijst_referentielijstomschrijving_data",
		Meervoud:               "referentielijst_referentielijstomschrijving_data",
		Factory:                func() Representatie { return &Referentielijst_Referentielijstomschrijving_Data{} },
		SliceFactory:           func() any { return &[]Referentielijst_Referentielijstomschrijving_Data{} },
		Tabelnaam:              "referentielijst_referentielijstomschrijving_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Referentielijst_Referentielijstomschrijving_Data{} },
		DBSliceFactory:         func() any { return &[]Referentielijst_Referentielijstomschrijving_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijst_Referentielijstomschrijving",
	}
	MetaRegistry["Referentielijst_ReferentielijstVisibility_Data"] = TypeMeta{
		Typenaam:               "Referentielijst_ReferentielijstVisibility_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Referentielijst_ReferentielijstVisibility.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijst_referentielijstvisibility_data",
		Padnaam:                "referentielijst_referentielijstvisibility_data",
		Meervoud:               "referentielijst_referentielijstvisibility_data",
		Factory:                func() Representatie { return &Referentielijst_ReferentielijstVisibility_Data{} },
		SliceFactory:           func() any { return &[]Referentielijst_ReferentielijstVisibility_Data{} },
		Tabelnaam:              "referentielijst_referentielijstvisibility_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Referentielijst_ReferentielijstVisibility_Data{} },
		DBSliceFactory:         func() any { return &[]Referentielijst_ReferentielijstVisibility_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijst_ReferentielijstVisibility",
	}
	MetaRegistry["Referentielijst_ReferentielijstInternetadres_Data"] = TypeMeta{
		Typenaam:               "Referentielijst_ReferentielijstInternetadres_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Referentielijst_ReferentielijstInternetadres.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijst_referentielijstinternetadres_data",
		Padnaam:                "referentielijst_referentielijstinternetadres_data",
		Meervoud:               "referentielijst_referentielijstinternetadres_data",
		Factory:                func() Representatie { return &Referentielijst_ReferentielijstInternetadres_Data{} },
		SliceFactory:           func() any { return &[]Referentielijst_ReferentielijstInternetadres_Data{} },
		Tabelnaam:              "referentielijst_referentielijstinternetadres_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Referentielijst_ReferentielijstInternetadres_Data{} },
		DBSliceFactory:         func() any { return &[]Referentielijst_ReferentielijstInternetadres_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijst_ReferentielijstInternetadres",
	}
	MetaRegistry["LandenlijstLand_Data"] = TypeMeta{
		Typenaam:               "LandenlijstLand_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van LandenlijstLand.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fef3c7",
		Veldnaam:               "landenlijstland_data",
		Padnaam:                "landenlijstland_data",
		Meervoud:               "landenlijstland_data",
		Factory:                func() Representatie { return &LandenlijstLand_Data{} },
		SliceFactory:           func() any { return &[]LandenlijstLand_Data{} },
		Tabelnaam:              "landenlijstland_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &LandenlijstLand_Data{} },
		DBSliceFactory:         func() any { return &[]LandenlijstLand_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "LandenlijstLand",
	}
	MetaRegistry["AdellijkeTitelsTitel_Data"] = TypeMeta{
		Typenaam:               "AdellijkeTitelsTitel_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van AdellijkeTitelsTitel.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fef3c7",
		Veldnaam:               "adellijketitelstitel_data",
		Padnaam:                "adellijketitelstitel_data",
		Meervoud:               "adellijketitelstitel_data",
		Factory:                func() Representatie { return &AdellijkeTitelsTitel_Data{} },
		SliceFactory:           func() any { return &[]AdellijkeTitelsTitel_Data{} },
		Tabelnaam:              "adellijketitelstitel_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &AdellijkeTitelsTitel_Data{} },
		DBSliceFactory:         func() any { return &[]AdellijkeTitelsTitel_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "AdellijkeTitelsTitel",
	}
	MetaRegistry["Referentielijst_Aanvang"] = TypeMeta{
		Typenaam:               "Referentielijst_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Referentielijst.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijst_aanvang",
		Padnaam:                "referentielijst_aanvang",
		Meervoud:               "referentielijst_aanvang",
		Factory:                func() Representatie { return &Referentielijst_Aanvang{} },
		SliceFactory:           func() any { return &[]Referentielijst_Aanvang{} },
		Tabelnaam:              "referentielijst_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Referentielijst_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Referentielijst_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijst",
	}
	MetaRegistry["Referentielijst_Einde"] = TypeMeta{
		Typenaam:               "Referentielijst_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Referentielijst.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijst_einde",
		Padnaam:                "referentielijst_einde",
		Meervoud:               "referentielijst_einde",
		Factory:                func() Representatie { return &Referentielijst_Einde{} },
		SliceFactory:           func() any { return &[]Referentielijst_Einde{} },
		Tabelnaam:              "referentielijst_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Referentielijst_Einde{} },
		DBSliceFactory:         func() any { return &[]Referentielijst_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijst",
	}

	// Referentielijst-instantie metadata + editor-posities
	ReferentielijstInstantieRegistry["AdellijkeTitels"] = ReferentielijstInstantieInfo{
		Naam:   "",
		Layout: &EditorLayout{Positie: &V3Positie{X: 1920, Y: -330}},
	}
	ReferentielijstInstantieRegistry["Landenlijst"] = ReferentielijstInstantieInfo{
		Naam:   "",
		Layout: &EditorLayout{Positie: &V3Positie{X: 1005, Y: -319.5}},
	}
}
