/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 */
/*  Created On : 30-jan-2018 12:06:00 */
/*  DBMS       : SQLite */
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS x
;

DROP TABLE IF EXISTS wijziging
;

DROP TABLE IF EXISTS registratie
;

DROP TABLE IF EXISTS opgave
;

DROP TABLE IF EXISTS o
;

DROP TABLE IF EXISTS gebeurtenis
;

/* Create Tables with Primary and Foreign Keys, Check and Unique Constraints */

-- nietnodig NOG
CREATE TABLE gebeurtenis
(
naam 
varchar(200) NOT NULL,
datum 
date NOT NULL,
opmerking 
varchar(200) NOT NULL,
gebeurtenis_id INTEGER NOT NULL PRIMARY KEY 
)
;

-- GewoneOpgave AmbtshalveOpgave
CREATE TABLE opgave
(
opgave_type VARCHAR(50) NOT NULL, -- Dit is een gegenereerde _Type kolom voor het STI-patroon (een base klasse met specialisaties in 1 tabel). De volgende typen zijn hierin opgenomen: - GewoneOpgave- AmbtshalveOpgave
opgave_id NUMERIC NOT NULL PRIMARY KEY ,
gebeurtenis_id NUMERIC,
CONSTRAINT FK_opgave_gebeurtenis FOREIGN KEY (gebeurtenis_id) REFERENCES gebeurtenis (gebeurtenis_id) ON DELETE No Action ON UPDATE No Action,
CHECK(opgave_type IN ('GewoneOpgave', 'AmbtshalveOpgave'))
)
;

-- =============VANAFHIER===============

CREATE TABLE x
(
waarde_van_x 
varchar(200) NOT NULL,
x_id INTEGER NOT NULL PRIMARY KEY 
)
;



CREATE TABLE o
(
waarde 
varchar NOT NULL,
o_id INTEGER NOT NULL PRIMARY KEY ,
x_id INTEGER,
CONSTRAINT FK_o_x FOREIGN KEY (x_id) REFERENCES x (x_id) ON DELETE No Action ON UPDATE No Action
)
;


CREATE TABLE registratie
(
registratie_id INTEGER NOT NULL PRIMARY KEY ,
registratie_type TEXT NOT NULL CHECK (registratie_type in ('Registratie', 'Correctie', 'Ongedaanmaking')),
tijdstip 
char(26) NOT NULL,
opmerking 
varchar(200) NOT NULL,
opgave_id INTEGER,
corrigeert_registratie_id INTEGER,
maakt_ongedaan_registratie_id INTEGER,
CONSTRAINT FK_corrigeert FOREIGN KEY (corrigeert_registratie_id) REFERENCES registratie (registratie_id) ON DELETE No Action ON UPDATE No Action,
CONSTRAINT FK_maakt_ongedaan FOREIGN KEY (maakt_ongedaan_registratie_id) REFERENCES registratie (registratie_id) ON DELETE No Action ON UPDATE No Action,
CONSTRAINT registreert_volgens FOREIGN KEY (opgave_id) REFERENCES opgave (opgave_id) ON DELETE No Action ON UPDATE No Action
);


-- Opvoer Afvoer
CREATE TABLE wijziging
(
wijziging_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
wijziging_type VARCHAR CHECK (wijziging_type IN ('Opvoer', 'Afvoer')), 
registratie_id INTEGER,
representatienaam 
varchar NOT NULL, --  de naam van de {Representatie} die gewijzigd is geworden.
representatie_id INTEGER NOT NULL,
tijdstip 
char(26) NOT NULL, -- - Afgeleide kolom! Het tijdstip van de Registratie.
CONSTRAINT FK_wijziging_registratie FOREIGN KEY (registratie_id) REFERENCES registratie (registratie_id) ON DELETE No Action ON UPDATE No Action
)
;


CREATE TABLE param (peiltijdstip,peildatum, p1,p2,p3,p4,p5); 
INSERT INTO param VALUES ('tz','mz', null, null,null,null,null);