package model

// Additieve MetaRegistry-entries — voegt types toe aan de bestaande MetaRegistry.
// Gegenereerd door cmd/codegen — niet handmatig bewerken.

func initIdeBestandenMetaRegistry() {
	MetaRegistry["IdeBestand"] = TypeMeta{
		Typenaam:               "IdeBestand",
		Klassenaam:             "IdeBestand",
		Description:            "Bestand beheerd vanuit de IDE: model-snapshots, imports, exports, gegenereerde code of documentatie. Bitemporeel: wijzigingen zijn traceerbaar en corrigeerbaar via registraties.",
		Metatype:               MetatypeEntiteit,
		IsMaterieel:            true,
		Domein:                 "ide-bestanden",
		Kleur:                  "#fbbf24",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 4605, Y: -880}},
		Veldnaam:               "idebestand",
		Padnaam:                "ide_bestanden",
		Meervoud:               "ide bestanden",
		Factory:                func() Representatie { return &IdeBestand{} },
		SliceFactory:           func() any { return &[]IdeBestand{} },
		Tabelnaam:              "idebestand",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &IdeBestand{} },
		DBSliceFactory:         func() any { return &[]IdeBestand{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "IdeBestandMetas", JSONRolnaam: "ide_bestand_metas", Doeltype: "IdeBestand_Meta", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "IdeBestandInhouds", JSONRolnaam: "ide_bestand_inhouds", Doeltype: "IdeBestand_Inhoud", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "IdeBestand_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "IdeBestand_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["IdeBestand_Meta"] = TypeMeta{
		Typenaam:               "IdeBestand_Meta",
		Klassenaam:             "Meta",
		Description:            "Metadata van het bestand: naam, beschrijving, categorie, formaat en domein.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "ide-bestanden",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "IdeBestand_Meta_Data",
		Kleur:                  "#fbbf24",
		Veldnaam:               "meta",
		Padnaam:                "ide_bestand_metas",
		Meervoud:               "ide_bestand_metas",
		Factory:                func() Representatie { return &IdeBestand_Meta_Input{} },
		Tabelnaam:              "idebestand_meta",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &IdeBestand_Meta{} },
		DBSliceFactory:         func() any { return &[]IdeBestand_Meta{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "idebestand_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 4455, Y: -630}},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "IdeBestand_Meta_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["IdeBestand_Inhoud"] = TypeMeta{
		Typenaam:               "IdeBestand_Inhoud",
		Klassenaam:             "Inhoud",
		Description:            "Inhoud en opslaginformatie van het bestand. Kleine tekstbestanden staan inline in de database, grotere of binaire bestanden worden opgeslagen in MinIO.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "ide-bestanden",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "IdeBestand_Inhoud_Data",
		Kleur:                  "#fbbf24",
		Veldnaam:               "inhoud",
		Padnaam:                "ide_bestand_inhouds",
		Meervoud:               "ide_bestand_inhouds",
		Factory:                func() Representatie { return &IdeBestand_Inhoud_Input{} },
		Tabelnaam:              "idebestand_inhoud",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &IdeBestand_Inhoud{} },
		DBSliceFactory:         func() any { return &[]IdeBestand_Inhoud{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "idebestand_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 4705, Y: -630}},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "IdeBestand_Inhoud_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["IdeBestand_Meta_Data"] = TypeMeta{
		Typenaam:               "IdeBestand_Meta_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van IdeBestand_Meta.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fbbf24",
		Veldnaam:               "idebestand_meta_data",
		Padnaam:                "idebestand_meta_data",
		Meervoud:               "idebestand_meta_data",
		Factory:                func() Representatie { return &IdeBestand_Meta_Data{} },
		SliceFactory:           func() any { return &[]IdeBestand_Meta_Data{} },
		Tabelnaam:              "idebestand_meta_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &IdeBestand_Meta_Data{} },
		DBSliceFactory:         func() any { return &[]IdeBestand_Meta_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "idebestand_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "IdeBestand_Meta",
	}
	MetaRegistry["IdeBestand_Inhoud_Data"] = TypeMeta{
		Typenaam:               "IdeBestand_Inhoud_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van IdeBestand_Inhoud.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fbbf24",
		Veldnaam:               "idebestand_inhoud_data",
		Padnaam:                "idebestand_inhoud_data",
		Meervoud:               "idebestand_inhoud_data",
		Factory:                func() Representatie { return &IdeBestand_Inhoud_Data{} },
		SliceFactory:           func() any { return &[]IdeBestand_Inhoud_Data{} },
		Tabelnaam:              "idebestand_inhoud_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &IdeBestand_Inhoud_Data{} },
		DBSliceFactory:         func() any { return &[]IdeBestand_Inhoud_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "idebestand_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "IdeBestand_Inhoud",
	}
	MetaRegistry["IdeBestand_Aanvang"] = TypeMeta{
		Typenaam:               "IdeBestand_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van IdeBestand.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#fbbf24",
		Veldnaam:               "idebestand_aanvang",
		Padnaam:                "idebestand_aanvang",
		Meervoud:               "idebestand_aanvang",
		Factory:                func() Representatie { return &IdeBestand_Aanvang{} },
		SliceFactory:           func() any { return &[]IdeBestand_Aanvang{} },
		Tabelnaam:              "idebestand_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &IdeBestand_Aanvang{} },
		DBSliceFactory:         func() any { return &[]IdeBestand_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "idebestand_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "IdeBestand",
	}
	MetaRegistry["IdeBestand_Einde"] = TypeMeta{
		Typenaam:               "IdeBestand_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van IdeBestand.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#fbbf24",
		Veldnaam:               "idebestand_einde",
		Padnaam:                "idebestand_einde",
		Meervoud:               "idebestand_einde",
		Factory:                func() Representatie { return &IdeBestand_Einde{} },
		SliceFactory:           func() any { return &[]IdeBestand_Einde{} },
		Tabelnaam:              "idebestand_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &IdeBestand_Einde{} },
		DBSliceFactory:         func() any { return &[]IdeBestand_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "idebestand_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "IdeBestand",
	}
}
