package model

// Additieve MetaRegistry-entries — voegt types toe aan de bestaande MetaRegistry.
// Gegenereerd door cmd/codegen — niet handmatig bewerken.

func initBeheerMetaRegistry() {
	MetaRegistry["Gebruiker"] = TypeMeta{
		Typenaam:               "Gebruiker",
		Klassenaam:             "Gebruiker",
		Description:            "Een persoon die kan inloggen op Omnium (Studio, register, publicatie). Bitemporeel: je ziet wie wanneer welke rol had en sinds wanneer een account geblokkeerd is. De levensduur van de entiteit is die van het account: afvoer = account beëindigd (geen hard delete). Wachtwoord-hash en laatste login staan NIET hier maar in de plumbing-tabel gebruiker_inlog, zodat ze nooit in de geschiedenis of de gegenereerde API belanden.",
		Metatype:               MetatypeEntiteit,
		IsMaterieel:            true,
		Domein:                 "beheer",
		Kleur:                  "#bae6fd",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 450, Y: 0}},
		Veldnaam:               "gebruiker",
		Padnaam:                "gebruikers",
		Meervoud:               "gebruikers",
		Factory:                func() Representatie { return &Gebruiker{} },
		SliceFactory:           func() any { return &[]Gebruiker{} },
		Tabelnaam:              "gebruiker",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &Gebruiker{} },
		DBSliceFactory:         func() any { return &[]Gebruiker{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "GebruikerIdentiteiten", JSONRolnaam: "gebruiker_identiteiten", Doeltype: "Gebruiker_GebruikerIdentiteit", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "GebruikerStatussen", JSONRolnaam: "gebruiker_statussen", Doeltype: "Gebruiker_GebruikerStatus", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "GebruikerRoltoewijzingen", JSONRolnaam: "gebruiker_roltoewijzingen", Doeltype: "Gebruiker_GebruikerRoltoewijzing", Momentvoorkomen: Meervoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Gebruiker_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Gebruiker_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Gebruiker_GebruikerIdentiteit"] = TypeMeta{
		Typenaam:               "Gebruiker_GebruikerIdentiteit",
		Klassenaam:             "GebruikerIdentiteit",
		Description:            "Wie het account is: de inlognaam en hoe iemand getoond wordt. Formeel: een correctie (typfout in de e-mail) heeft geen materiële betekenis. Bewust weinig persoonsgegevens (AVG).",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "beheer",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Gebruiker_GebruikerIdentiteit_Data",
		Kleur:                  "#bae6fd",
		Veldnaam:               "gebruikeridentiteit",
		Padnaam:                "gebruiker_identiteiten",
		Meervoud:               "gebruiker_identiteiten",
		Factory:                func() Representatie { return &Gebruiker_GebruikerIdentiteit_Input{} },
		Tabelnaam:              "gebruiker_gebruikeridentiteit",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Gebruiker_GebruikerIdentiteit{} },
		DBSliceFactory:         func() any { return &[]Gebruiker_GebruikerIdentiteit{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "gebruiker_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 0, Y: 250}},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Gebruiker_GebruikerIdentiteit_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Gebruiker_GebruikerStatus"] = TypeMeta{
		Typenaam:               "Gebruiker_GebruikerStatus",
		Klassenaam:             "GebruikerStatus",
		Description:            "Of het account mag inloggen. Materieel: 'geblokkeerd vanaf …' is vooruit in te plannen en weer op te heffen. Ontbreekt dit GE, dan geldt actief.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            true,
		Domein:                 "beheer",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Gebruiker_GebruikerStatus_Data",
		Kleur:                  "#bae6fd",
		Veldnaam:               "gebruikerstatus",
		Padnaam:                "gebruiker_statussen",
		Meervoud:               "gebruiker_statussen",
		Factory:                func() Representatie { return &Gebruiker_GebruikerStatus_Input{} },
		Tabelnaam:              "gebruiker_gebruikerstatus",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Gebruiker_GebruikerStatus{} },
		DBSliceFactory:         func() any { return &[]Gebruiker_GebruikerStatus{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "gebruiker_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 300, Y: 250}},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Gebruiker_GebruikerStatus_Data", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Gebruiker_GebruikerStatus_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Gebruiker_GebruikerStatus_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Gebruiker_GebruikerRoltoewijzing"] = TypeMeta{
		Typenaam:               "Gebruiker_GebruikerRoltoewijzing",
		Klassenaam:             "GebruikerRoltoewijzing",
		Description:            "Een rol die de gebruiker heeft. Meervoudig en materieel: met een geldigheidsperiode verloopt een proefaccount vanzelf ('editor tot 15-10'), en je kunt terugvragen wie op een datum admin was. Zonder geldige toewijzing heeft de gebruiker geen rechten.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            true,
		Domein:                 "beheer",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Gebruiker_GebruikerRoltoewijzing_Data",
		Kleur:                  "#bae6fd",
		Veldnaam:               "gebruikerroltoewijzing",
		Padnaam:                "gebruiker_roltoewijzingen",
		Meervoud:               "gebruiker_roltoewijzingen",
		Factory:                func() Representatie { return &Gebruiker_GebruikerRoltoewijzing_Input{} },
		Tabelnaam:              "gebruiker_gebruikerroltoewijzing",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Gebruiker_GebruikerRoltoewijzing{} },
		DBSliceFactory:         func() any { return &[]Gebruiker_GebruikerRoltoewijzing{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "gebruiker_id",
		Momentvoorkomen:        Meervoudig,
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 600, Y: 250}},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Gebruiker_GebruikerRoltoewijzing_Data", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Gebruiker_GebruikerRoltoewijzing_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Gebruiker_GebruikerRoltoewijzing_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Gebruiker_GebruikerIdentiteit_Data"] = TypeMeta{
		Typenaam:               "Gebruiker_GebruikerIdentiteit_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Gebruiker_GebruikerIdentiteit.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bae6fd",
		Veldnaam:               "gebruiker_gebruikeridentiteit_data",
		Padnaam:                "gebruiker_gebruikeridentiteit_data",
		Meervoud:               "gebruiker_gebruikeridentiteit_data",
		Factory:                func() Representatie { return &Gebruiker_GebruikerIdentiteit_Data{} },
		SliceFactory:           func() any { return &[]Gebruiker_GebruikerIdentiteit_Data{} },
		Tabelnaam:              "gebruiker_gebruikeridentiteit_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Gebruiker_GebruikerIdentiteit_Data{} },
		DBSliceFactory:         func() any { return &[]Gebruiker_GebruikerIdentiteit_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "gebruiker_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Gebruiker_GebruikerIdentiteit",
	}
	MetaRegistry["Gebruiker_GebruikerStatus_Data"] = TypeMeta{
		Typenaam:               "Gebruiker_GebruikerStatus_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Gebruiker_GebruikerStatus.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bae6fd",
		Veldnaam:               "gebruiker_gebruikerstatus_data",
		Padnaam:                "gebruiker_gebruikerstatus_data",
		Meervoud:               "gebruiker_gebruikerstatus_data",
		Factory:                func() Representatie { return &Gebruiker_GebruikerStatus_Data{} },
		SliceFactory:           func() any { return &[]Gebruiker_GebruikerStatus_Data{} },
		Tabelnaam:              "gebruiker_gebruikerstatus_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Gebruiker_GebruikerStatus_Data{} },
		DBSliceFactory:         func() any { return &[]Gebruiker_GebruikerStatus_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "gebruiker_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Gebruiker_GebruikerStatus",
	}
	MetaRegistry["Gebruiker_GebruikerRoltoewijzing_Data"] = TypeMeta{
		Typenaam:               "Gebruiker_GebruikerRoltoewijzing_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Gebruiker_GebruikerRoltoewijzing.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bae6fd",
		Veldnaam:               "gebruiker_gebruikerroltoewijzing_data",
		Padnaam:                "gebruiker_gebruikerroltoewijzing_data",
		Meervoud:               "gebruiker_gebruikerroltoewijzing_data",
		Factory:                func() Representatie { return &Gebruiker_GebruikerRoltoewijzing_Data{} },
		SliceFactory:           func() any { return &[]Gebruiker_GebruikerRoltoewijzing_Data{} },
		Tabelnaam:              "gebruiker_gebruikerroltoewijzing_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Gebruiker_GebruikerRoltoewijzing_Data{} },
		DBSliceFactory:         func() any { return &[]Gebruiker_GebruikerRoltoewijzing_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "gebruiker_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Gebruiker_GebruikerRoltoewijzing",
	}
	MetaRegistry["Gebruiker_Aanvang"] = TypeMeta{
		Typenaam:               "Gebruiker_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Gebruiker.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bae6fd",
		Veldnaam:               "gebruiker_aanvang",
		Padnaam:                "gebruiker_aanvang",
		Meervoud:               "gebruiker_aanvang",
		Factory:                func() Representatie { return &Gebruiker_Aanvang{} },
		SliceFactory:           func() any { return &[]Gebruiker_Aanvang{} },
		Tabelnaam:              "gebruiker_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Gebruiker_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Gebruiker_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "gebruiker_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Gebruiker",
	}
	MetaRegistry["Gebruiker_Einde"] = TypeMeta{
		Typenaam:               "Gebruiker_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Gebruiker.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bae6fd",
		Veldnaam:               "gebruiker_einde",
		Padnaam:                "gebruiker_einde",
		Meervoud:               "gebruiker_einde",
		Factory:                func() Representatie { return &Gebruiker_Einde{} },
		SliceFactory:           func() any { return &[]Gebruiker_Einde{} },
		Tabelnaam:              "gebruiker_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Gebruiker_Einde{} },
		DBSliceFactory:         func() any { return &[]Gebruiker_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "gebruiker_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Gebruiker",
	}
	MetaRegistry["Gebruiker_GebruikerStatus_Aanvang"] = TypeMeta{
		Typenaam:               "Gebruiker_GebruikerStatus_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Gebruiker_GebruikerStatus.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bae6fd",
		Veldnaam:               "gebruiker_gebruikerstatus_aanvang",
		Padnaam:                "gebruiker_gebruikerstatus_aanvang",
		Meervoud:               "gebruiker_gebruikerstatus_aanvang",
		Factory:                func() Representatie { return &Gebruiker_GebruikerStatus_Aanvang{} },
		SliceFactory:           func() any { return &[]Gebruiker_GebruikerStatus_Aanvang{} },
		Tabelnaam:              "gebruiker_gebruikerstatus_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Gebruiker_GebruikerStatus_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Gebruiker_GebruikerStatus_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "gebruiker_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Gebruiker_GebruikerStatus",
	}
	MetaRegistry["Gebruiker_GebruikerStatus_Einde"] = TypeMeta{
		Typenaam:               "Gebruiker_GebruikerStatus_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Gebruiker_GebruikerStatus.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bae6fd",
		Veldnaam:               "gebruiker_gebruikerstatus_einde",
		Padnaam:                "gebruiker_gebruikerstatus_einde",
		Meervoud:               "gebruiker_gebruikerstatus_einde",
		Factory:                func() Representatie { return &Gebruiker_GebruikerStatus_Einde{} },
		SliceFactory:           func() any { return &[]Gebruiker_GebruikerStatus_Einde{} },
		Tabelnaam:              "gebruiker_gebruikerstatus_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Gebruiker_GebruikerStatus_Einde{} },
		DBSliceFactory:         func() any { return &[]Gebruiker_GebruikerStatus_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "gebruiker_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Gebruiker_GebruikerStatus",
	}
	MetaRegistry["Gebruiker_GebruikerRoltoewijzing_Aanvang"] = TypeMeta{
		Typenaam:               "Gebruiker_GebruikerRoltoewijzing_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Gebruiker_GebruikerRoltoewijzing.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bae6fd",
		Veldnaam:               "gebruiker_gebruikerroltoewijzing_aanvang",
		Padnaam:                "gebruiker_gebruikerroltoewijzing_aanvang",
		Meervoud:               "gebruiker_gebruikerroltoewijzing_aanvang",
		Factory:                func() Representatie { return &Gebruiker_GebruikerRoltoewijzing_Aanvang{} },
		SliceFactory:           func() any { return &[]Gebruiker_GebruikerRoltoewijzing_Aanvang{} },
		Tabelnaam:              "gebruiker_gebruikerroltoewijzing_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Gebruiker_GebruikerRoltoewijzing_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Gebruiker_GebruikerRoltoewijzing_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "gebruiker_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Gebruiker_GebruikerRoltoewijzing",
	}
	MetaRegistry["Gebruiker_GebruikerRoltoewijzing_Einde"] = TypeMeta{
		Typenaam:               "Gebruiker_GebruikerRoltoewijzing_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Gebruiker_GebruikerRoltoewijzing.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bae6fd",
		Veldnaam:               "gebruiker_gebruikerroltoewijzing_einde",
		Padnaam:                "gebruiker_gebruikerroltoewijzing_einde",
		Meervoud:               "gebruiker_gebruikerroltoewijzing_einde",
		Factory:                func() Representatie { return &Gebruiker_GebruikerRoltoewijzing_Einde{} },
		SliceFactory:           func() any { return &[]Gebruiker_GebruikerRoltoewijzing_Einde{} },
		Tabelnaam:              "gebruiker_gebruikerroltoewijzing_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Gebruiker_GebruikerRoltoewijzing_Einde{} },
		DBSliceFactory:         func() any { return &[]Gebruiker_GebruikerRoltoewijzing_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "gebruiker_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Gebruiker_GebruikerRoltoewijzing",
	}
}
