package model

// Additieve MetaRegistry-entries — voegt types toe aan de bestaande MetaRegistry.
// Gegenereerd door cmd/codegen — niet handmatig bewerken.

func initCgMetaRegistry() {
	MetaRegistry["ApiStandaard"] = TypeMeta{
		Typenaam:               "ApiStandaard",
		Klassenaam:             "ApiStandaard",
		Description:            "",
		Metatype:               MetatypeEntiteit,
		EntiteitSubtype:        EntiteitSubtypeReferentielijstItem,
		IsMaterieel:            false,
		Domein:                 "CG",
		Kleur:                  "#fde68a",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 1410, Y: -2310}},
		Veldnaam:               "apistandaard",
		Padnaam:                "api_standaarden",
		Meervoud:               "api standaarden",
		Factory:                func() Representatie { return &ApiStandaard{} },
		SliceFactory:           func() any { return &[]ApiStandaard{} },
		Tabelnaam:              "apistandaard",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &ApiStandaard{} },
		DBSliceFactory:         func() any { return &[]ApiStandaard{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "ApiStandaardNamen", JSONRolnaam: "api_standaard_namen", Doeltype: "ApiStandaard_Naam", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["ApiStandaard_Naam"] = TypeMeta{
		Typenaam:               "ApiStandaard_Naam",
		Klassenaam:             "Naam",
		Description:            "",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "CG",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "ApiStandaard_Naam_Data",
		Kleur:                  "#fde68a",
		Veldnaam:               "naam",
		Padnaam:                "api_standaard_namen",
		Meervoud:               "api_standaard_namen",
		Factory:                func() Representatie { return &ApiStandaard_Naam_Input{} },
		Tabelnaam:              "apistandaard_naam",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &ApiStandaard_Naam{} },
		DBSliceFactory:         func() any { return &[]ApiStandaard_Naam{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "apistandaard_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie:      &V3Positie{X: 1740, Y: -2310},
			EdgeID:       "edge_1775567207805_5",
			SourceHandle: "right",
			TargetHandle: "left",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "ApiStandaard_Naam_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["ApiStandaard_Naam_Data"] = TypeMeta{
		Typenaam:               "ApiStandaard_Naam_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van ApiStandaard_Naam.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fde68a",
		Veldnaam:               "apistandaard_naam_data",
		Padnaam:                "apistandaard_naam_data",
		Meervoud:               "apistandaard_naam_data",
		Factory:                func() Representatie { return &ApiStandaard_Naam_Data{} },
		SliceFactory:           func() any { return &[]ApiStandaard_Naam_Data{} },
		Tabelnaam:              "apistandaard_naam_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &ApiStandaard_Naam_Data{} },
		DBSliceFactory:         func() any { return &[]ApiStandaard_Naam_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "apistandaard_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "ApiStandaard_Naam",
	}
	MetaRegistry["Domein"] = TypeMeta{
		Typenaam:               "Domein",
		Klassenaam:             "Domein",
		Description:            "Referentielijst-item voor domeinen.",
		Metatype:               MetatypeEntiteit,
		EntiteitSubtype:        EntiteitSubtypeReferentielijstItem,
		IsMaterieel:            false,
		Domein:                 "CG",
		Kleur:                  "#a7f3d0",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 1410, Y: -2535}},
		Veldnaam:               "domein",
		Padnaam:                "domeinen",
		Meervoud:               "domeinen",
		Factory:                func() Representatie { return &Domein{} },
		SliceFactory:           func() any { return &[]Domein{} },
		Tabelnaam:              "domein",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &Domein{} },
		DBSliceFactory:         func() any { return &[]Domein{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Domeingegevens", JSONRolnaam: "domeingegevens", Doeltype: "Domein_DomeinGegevens", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Domein_DomeinGegevens"] = TypeMeta{
		Typenaam:               "Domein_DomeinGegevens",
		Klassenaam:             "DomeinGegevens",
		Description:            "Basisgegevens van een domein.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "CG",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Domein_DomeinGegevens_Data",
		Kleur:                  "#a7f3d0",
		Veldnaam:               "domeingegevens",
		Padnaam:                "domeingegevens",
		Meervoud:               "domeingegevens",
		Factory:                func() Representatie { return &Domein_DomeinGegevens_Input{} },
		Tabelnaam:              "domein_domeingegevens",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Domein_DomeinGegevens{} },
		DBSliceFactory:         func() any { return &[]Domein_DomeinGegevens{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "domein_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie:      &V3Positie{X: 1740, Y: -2535},
			EdgeID:       "Domein->Domein_DomeinGegevens",
			SourceHandle: "right",
			TargetHandle: "left",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Domein_DomeinGegevens_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Domein_DomeinGegevens_Data"] = TypeMeta{
		Typenaam:               "Domein_DomeinGegevens_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Domein_DomeinGegevens.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#a7f3d0",
		Veldnaam:               "domein_domeingegevens_data",
		Padnaam:                "domein_domeingegevens_data",
		Meervoud:               "domein_domeingegevens_data",
		Factory:                func() Representatie { return &Domein_DomeinGegevens_Data{} },
		SliceFactory:           func() any { return &[]Domein_DomeinGegevens_Data{} },
		Tabelnaam:              "domein_domeingegevens_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Domein_DomeinGegevens_Data{} },
		DBSliceFactory:         func() any { return &[]Domein_DomeinGegevens_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "domein_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Domein_DomeinGegevens",
	}
	MetaRegistry["Gemeente"] = TypeMeta{
		Typenaam:               "Gemeente",
		Klassenaam:             "Gemeente",
		Description:            "Referentielijst-item voor gemeenten.",
		Metatype:               MetatypeEntiteit,
		EntiteitSubtype:        EntiteitSubtypeReferentielijstItem,
		IsMaterieel:            false,
		Domein:                 "CG",
		Kleur:                  "#c4b5fd",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 1410, Y: -2789}},
		Veldnaam:               "gemeente",
		Padnaam:                "gemeenten",
		Meervoud:               "gemeenten",
		Factory:                func() Representatie { return &Gemeente{} },
		SliceFactory:           func() any { return &[]Gemeente{} },
		Tabelnaam:              "gemeente",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &Gemeente{} },
		DBSliceFactory:         func() any { return &[]Gemeente{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Gemeentegegevens", JSONRolnaam: "gemeentegegevens", Doeltype: "Gemeente_GemeenteGegevens", Momentvoorkomen: Enkelvoudig},
		},
		AfgeleideVelden: []AfgeleidVeld{
			{
				Naam:                "weergavenaam",
				GoType:              "string",
				AfleidingsregelTaal: "cel",
				Afleidingsregel:     "naam + \" (\" + code + \")\"",
				IsWeergaveVeld:      true,
			},
		},
	}
	MetaRegistry["Gemeente_GemeenteGegevens"] = TypeMeta{
		Typenaam:               "Gemeente_GemeenteGegevens",
		Klassenaam:             "GemeenteGegevens",
		Description:            "Basisgegevens van een gemeente.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "CG",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Gemeente_GemeenteGegevens_Data",
		Kleur:                  "#c4b5fd",
		Veldnaam:               "gemeentegegevens",
		Padnaam:                "gemeentegegevens",
		Meervoud:               "gemeentegegevens",
		Factory:                func() Representatie { return &Gemeente_GemeenteGegevens_Input{} },
		Tabelnaam:              "gemeente_gemeentegegevens",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Gemeente_GemeenteGegevens{} },
		DBSliceFactory:         func() any { return &[]Gemeente_GemeenteGegevens{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "gemeente_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie:      &V3Positie{X: 1740, Y: -2779},
			EdgeID:       "Gemeente->Gemeente_GemeenteGegevens",
			SourceHandle: "right",
			TargetHandle: "left",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Gemeente_GemeenteGegevens_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Gemeente_GemeenteGegevens_Data"] = TypeMeta{
		Typenaam:               "Gemeente_GemeenteGegevens_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Gemeente_GemeenteGegevens.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#c4b5fd",
		Veldnaam:               "gemeente_gemeentegegevens_data",
		Padnaam:                "gemeente_gemeentegegevens_data",
		Meervoud:               "gemeente_gemeentegegevens_data",
		Factory:                func() Representatie { return &Gemeente_GemeenteGegevens_Data{} },
		SliceFactory:           func() any { return &[]Gemeente_GemeenteGegevens_Data{} },
		Tabelnaam:              "gemeente_gemeentegegevens_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Gemeente_GemeenteGegevens_Data{} },
		DBSliceFactory:         func() any { return &[]Gemeente_GemeenteGegevens_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "gemeente_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Gemeente_GemeenteGegevens",
	}
	MetaRegistry["Initiatief"] = TypeMeta{
		Typenaam:               "Initiatief",
		Klassenaam:             "Initiatief",
		Description:            "Portfolio-initiatief met planning, productinformatie en bijdragen.",
		Metatype:               MetatypeEntiteit,
		IsMaterieel:            true,
		Domein:                 "CG",
		Kleur:                  "#bfdbfe",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 720, Y: -2505}},
		Veldnaam:               "initiatief",
		Padnaam:                "initiatieven",
		Meervoud:               "initiatieven",
		Factory:                func() Representatie { return &Initiatief{} },
		SliceFactory:           func() any { return &[]Initiatief{} },
		Tabelnaam:              "initiatief",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &Initiatief{} },
		DBSliceFactory:         func() any { return &[]Initiatief{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Planningen", JSONRolnaam: "planningen", Doeltype: "Initiatief_Planning", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Producten", JSONRolnaam: "producten", Doeltype: "Initiatief_Product", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Bijdragen", JSONRolnaam: "bijdragen", Doeltype: "Initiatief_Bijdrage", Momentvoorkomen: Meervoudig},
			{Rolnaam: "AndereDomeinen", JSONRolnaam: "andere_domeinen", Doeltype: "Initiatief_AnderDomein", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "AndersDanGemeenten", JSONRolnaam: "anders_dan_gemeenten", Doeltype: "Initiatief_AndersDanGemeente", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "AndereApiStandaarden", JSONRolnaam: "andere_api_standaarden", Doeltype: "Initiatief_AndereAPIStandaard", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "InitiatiefGemeenten", JSONRolnaam: "initiatief_gemeenten", Doeltype: "InitiatiefGemeente", Momentvoorkomen: Meervoudig},
			{Rolnaam: "InitiatiefDomeinen", JSONRolnaam: "initiatief_domeinen", Doeltype: "InitiatiefDomein", Momentvoorkomen: Meervoudig},
			{Rolnaam: "InitiatiefApiStandaarden", JSONRolnaam: "initiatief_api_standaarden", Doeltype: "InitiatiefAPIStandaard", Momentvoorkomen: Meervoudig},
			{Rolnaam: "InitiatiefOrganisaties", JSONRolnaam: "initiatief_organisaties", Doeltype: "InitiatiefOrganisatie", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Initiatief_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Initiatief_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Initiatief_Planning"] = TypeMeta{
		Typenaam:               "Initiatief_Planning",
		Klassenaam:             "Planning",
		Description:            "Planning en voortgang van het initiatief.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            true,
		Domein:                 "CG",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Initiatief_Planning_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "planning",
		Padnaam:                "planningen",
		Meervoud:               "planningen",
		Factory:                func() Representatie { return &Initiatief_Planning_Input{} },
		Tabelnaam:              "initiatief_planning",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Initiatief_Planning{} },
		DBSliceFactory:         func() any { return &[]Initiatief_Planning{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "initiatief_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 495, Y: -1950},
			EdgeID:  "Initiatief->Initiatief_Planning",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Initiatief_Planning_Data", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Initiatief_Planning_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Initiatief_Planning_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Initiatief_Product"] = TypeMeta{
		Typenaam:               "Initiatief_Product",
		Klassenaam:             "Product",
		Description:            "Beschrijving van het product dat bij het initiatief hoort.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            true,
		Domein:                 "CG",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Initiatief_Product_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "product",
		Padnaam:                "producten",
		Meervoud:               "producten",
		Factory:                func() Representatie { return &Initiatief_Product_Input{} },
		Tabelnaam:              "initiatief_product",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Initiatief_Product{} },
		DBSliceFactory:         func() any { return &[]Initiatief_Product{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "initiatief_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 750, Y: -1980},
			EdgeID:  "Initiatief->Initiatief_Product",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Initiatief_Product_Data", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Initiatief_Product_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Initiatief_Product_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Initiatief_Bijdrage"] = TypeMeta{
		Typenaam:               "Initiatief_Bijdrage",
		Klassenaam:             "Bijdrage",
		Description:            "Bijdrage van het initiatief aan bredere doelen.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            true,
		Domein:                 "CG",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Initiatief_Bijdrage_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "bijdrage",
		Padnaam:                "bijdragen",
		Meervoud:               "bijdragen",
		Factory:                func() Representatie { return &Initiatief_Bijdrage_Input{} },
		Tabelnaam:              "initiatief_bijdrage",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Initiatief_Bijdrage{} },
		DBSliceFactory:         func() any { return &[]Initiatief_Bijdrage{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "initiatief_id",
		Momentvoorkomen:        Meervoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 1035, Y: -1935},
			EdgeID:  "Initiatief->Initiatief_Bijdrage",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Initiatief_Bijdrage_Data", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Initiatief_Bijdrage_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Initiatief_Bijdrage_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Initiatief_AnderDomein"] = TypeMeta{
		Typenaam:               "Initiatief_AnderDomein",
		Klassenaam:             "AnderDomein",
		Description:            "",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "CG",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Initiatief_AnderDomein_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "anderdomein",
		Padnaam:                "andere_domeinen",
		Meervoud:               "andere_domeinen",
		Factory:                func() Representatie { return &Initiatief_AnderDomein_Input{} },
		Tabelnaam:              "initiatief_anderdomein",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Initiatief_AnderDomein{} },
		DBSliceFactory:         func() any { return &[]Initiatief_AnderDomein{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "initiatief_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie:      &V3Positie{X: 1080, Y: -2424},
			EdgeID:       "edge_1775592769882_12",
			SourceHandle: "right",
			TargetHandle: "left",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Initiatief_AnderDomein_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Initiatief_AndersDanGemeente"] = TypeMeta{
		Typenaam:               "Initiatief_AndersDanGemeente",
		Klassenaam:             "AndersDanGemeente",
		Description:            "",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "CG",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Initiatief_AndersDanGemeente_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "andersdangemeente",
		Padnaam:                "anders_dan_gemeenten",
		Meervoud:               "anders_dan_gemeenten",
		Factory:                func() Representatie { return &Initiatief_AndersDanGemeente_Input{} },
		Tabelnaam:              "initiatief_andersdangemeente",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Initiatief_AndersDanGemeente{} },
		DBSliceFactory:         func() any { return &[]Initiatief_AndersDanGemeente{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "initiatief_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie:      &V3Positie{X: 1080, Y: -2658},
			EdgeID:       "edge_1775592790634_14",
			SourceHandle: "right",
			TargetHandle: "left",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Initiatief_AndersDanGemeente_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Initiatief_AndereAPIStandaard"] = TypeMeta{
		Typenaam:               "Initiatief_AndereAPIStandaard",
		Klassenaam:             "AndereAPIStandaard",
		Description:            "",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "CG",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Initiatief_AndereAPIStandaard_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "andereapistandaard",
		Padnaam:                "andere_api_standaarden",
		Meervoud:               "andere_api_standaarden",
		Factory:                func() Representatie { return &Initiatief_AndereAPIStandaard_Input{} },
		Tabelnaam:              "initiatief_andereapistandaard",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Initiatief_AndereAPIStandaard{} },
		DBSliceFactory:         func() any { return &[]Initiatief_AndereAPIStandaard{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "initiatief_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie:      &V3Positie{X: 1080, Y: -2190},
			EdgeID:       "edge_1775592938018_17",
			SourceHandle: "right",
			TargetHandle: "left",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Initiatief_AndereAPIStandaard_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["InitiatiefGemeente"] = TypeMeta{
		Typenaam:                  "InitiatiefGemeente",
		Klassenaam:                "InitiatiefGemeente",
		Description:               "",
		Metatype:                  MetatypeRelatie,
		IsMaterieel:               false,
		Domein:                    "CG",
		GESubtype:                 GESubtypeHub,
		DataTypenaam:              "InitiatiefGemeente_Data",
		Kleur:                     "",
		Veldnaam:                  "initiatiefgemeente",
		Padnaam:                   "initiatief_gemeenten",
		Meervoud:                  "initiatief_gemeenten",
		Factory:                   func() Representatie { return &InitiatiefGemeente_Input{} },
		Tabelnaam:                 "initiatiefgemeente",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &InitiatiefGemeente{} },
		DBSliceFactory:            func() any { return &[]InitiatiefGemeente{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "initiatief_id",
		SecondaireEntiteitIDKolom: "gemeente_id",
		Momentvoorkomen:           Meervoudig,
		Layout: &EditorLayout{
			Positie:          &V3Positie{X: 1080, Y: -2775},
			EdgeID:           "edge_1775567300131_7",
			SourceHandle:     "right",
			TargetHandle:     "left",
			DoelEdgeID:       "edge_1775567335493_8",
			DoelSourceHandle: "right",
			DoelTargetHandle: "left",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "InitiatiefGemeente_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["InitiatiefDomein"] = TypeMeta{
		Typenaam:                  "InitiatiefDomein",
		Klassenaam:                "InitiatiefDomein",
		Description:               "",
		Metatype:                  MetatypeRelatie,
		IsMaterieel:               false,
		Domein:                    "CG",
		GESubtype:                 GESubtypeHub,
		DataTypenaam:              "InitiatiefDomein_Data",
		Kleur:                     "",
		Veldnaam:                  "initiatiefdomein",
		Padnaam:                   "initiatief_domeinen",
		Meervoud:                  "initiatief_domeinen",
		Factory:                   func() Representatie { return &InitiatiefDomein_Input{} },
		Tabelnaam:                 "initiatiefdomein",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &InitiatiefDomein{} },
		DBSliceFactory:            func() any { return &[]InitiatiefDomein{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "initiatief_id",
		SecondaireEntiteitIDKolom: "domein_id",
		Momentvoorkomen:           Meervoudig,
		Layout: &EditorLayout{
			Positie:          &V3Positie{X: 1080, Y: -2541},
			EdgeID:           "edge_1775567392935_11",
			SourceHandle:     "right",
			TargetHandle:     "left",
			DoelEdgeID:       "edge_1775567422077_13",
			DoelSourceHandle: "left",
			DoelTargetHandle: "right",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "InitiatiefDomein_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["InitiatiefAPIStandaard"] = TypeMeta{
		Typenaam:                  "InitiatiefAPIStandaard",
		Klassenaam:                "InitiatiefAPIStandaard",
		Description:               "",
		Metatype:                  MetatypeRelatie,
		IsMaterieel:               false,
		Domein:                    "CG",
		GESubtype:                 GESubtypeHub,
		DataTypenaam:              "InitiatiefAPIStandaard_Data",
		Kleur:                     "",
		Veldnaam:                  "initiatiefapistandaard",
		Padnaam:                   "initiatief_api_standaarden",
		Meervoud:                  "initiatief_api_standaarden",
		Factory:                   func() Representatie { return &InitiatiefAPIStandaard_Input{} },
		Tabelnaam:                 "initiatiefapistandaard",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &InitiatiefAPIStandaard{} },
		DBSliceFactory:            func() any { return &[]InitiatiefAPIStandaard{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "initiatief_id",
		SecondaireEntiteitIDKolom: "apistandaard_id",
		Momentvoorkomen:           Meervoudig,
		Layout: &EditorLayout{
			Positie:          &V3Positie{X: 1080, Y: -2307},
			EdgeID:           "edge_1775569530678_15",
			SourceHandle:     "right",
			TargetHandle:     "left",
			DoelEdgeID:       "edge_1775570229289_20",
			DoelSourceHandle: "left",
			DoelTargetHandle: "right",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "InitiatiefAPIStandaard_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["InitiatiefOrganisatie"] = TypeMeta{
		Typenaam:                  "InitiatiefOrganisatie",
		Klassenaam:                "InitiatiefOrganisatie",
		Description:               "de organisaties bij een initiatief",
		Metatype:                  MetatypeRelatie,
		IsMaterieel:               false,
		Domein:                    "CG",
		GESubtype:                 GESubtypeHub,
		DataTypenaam:              "InitiatiefOrganisatie_Data",
		Kleur:                     "",
		Veldnaam:                  "initiatieforganisatie",
		Padnaam:                   "initiatief_organisaties",
		Meervoud:                  "initiatief_organisaties",
		Factory:                   func() Representatie { return &InitiatiefOrganisatie_Input{} },
		Tabelnaam:                 "initiatieforganisatie",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &InitiatiefOrganisatie{} },
		DBSliceFactory:            func() any { return &[]InitiatiefOrganisatie{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "initiatief_id",
		SecondaireEntiteitIDKolom: "organisatie_id",
		Momentvoorkomen:           Enkelvoudig,
		Layout: &EditorLayout{
			Positie:          &V3Positie{X: 420, Y: -2340},
			EdgeID:           "edge_1775591842339_3",
			SourceHandle:     "left",
			TargetHandle:     "right",
			DoelEdgeID:       "edge_1775591886387_4",
			DoelSourceHandle: "left",
			DoelTargetHandle: "right",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "InitiatiefOrganisatie_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Initiatief_Planning_Data"] = TypeMeta{
		Typenaam:               "Initiatief_Planning_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Initiatief_Planning.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "initiatief_planning_data",
		Padnaam:                "initiatief_planning_data",
		Meervoud:               "initiatief_planning_data",
		Factory:                func() Representatie { return &Initiatief_Planning_Data{} },
		SliceFactory:           func() any { return &[]Initiatief_Planning_Data{} },
		Tabelnaam:              "initiatief_planning_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Initiatief_Planning_Data{} },
		DBSliceFactory:         func() any { return &[]Initiatief_Planning_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "initiatief_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Initiatief_Planning",
	}
	MetaRegistry["Initiatief_Product_Data"] = TypeMeta{
		Typenaam:               "Initiatief_Product_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Initiatief_Product.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "initiatief_product_data",
		Padnaam:                "initiatief_product_data",
		Meervoud:               "initiatief_product_data",
		Factory:                func() Representatie { return &Initiatief_Product_Data{} },
		SliceFactory:           func() any { return &[]Initiatief_Product_Data{} },
		Tabelnaam:              "initiatief_product_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Initiatief_Product_Data{} },
		DBSliceFactory:         func() any { return &[]Initiatief_Product_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "initiatief_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Initiatief_Product",
	}
	MetaRegistry["Initiatief_Bijdrage_Data"] = TypeMeta{
		Typenaam:               "Initiatief_Bijdrage_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Initiatief_Bijdrage.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "initiatief_bijdrage_data",
		Padnaam:                "initiatief_bijdrage_data",
		Meervoud:               "initiatief_bijdrage_data",
		Factory:                func() Representatie { return &Initiatief_Bijdrage_Data{} },
		SliceFactory:           func() any { return &[]Initiatief_Bijdrage_Data{} },
		Tabelnaam:              "initiatief_bijdrage_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Initiatief_Bijdrage_Data{} },
		DBSliceFactory:         func() any { return &[]Initiatief_Bijdrage_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "initiatief_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Initiatief_Bijdrage",
	}
	MetaRegistry["Initiatief_AnderDomein_Data"] = TypeMeta{
		Typenaam:               "Initiatief_AnderDomein_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Initiatief_AnderDomein.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "initiatief_anderdomein_data",
		Padnaam:                "initiatief_anderdomein_data",
		Meervoud:               "initiatief_anderdomein_data",
		Factory:                func() Representatie { return &Initiatief_AnderDomein_Data{} },
		SliceFactory:           func() any { return &[]Initiatief_AnderDomein_Data{} },
		Tabelnaam:              "initiatief_anderdomein_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Initiatief_AnderDomein_Data{} },
		DBSliceFactory:         func() any { return &[]Initiatief_AnderDomein_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "initiatief_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Initiatief_AnderDomein",
	}
	MetaRegistry["Initiatief_AndersDanGemeente_Data"] = TypeMeta{
		Typenaam:               "Initiatief_AndersDanGemeente_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Initiatief_AndersDanGemeente.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "initiatief_andersdangemeente_data",
		Padnaam:                "initiatief_andersdangemeente_data",
		Meervoud:               "initiatief_andersdangemeente_data",
		Factory:                func() Representatie { return &Initiatief_AndersDanGemeente_Data{} },
		SliceFactory:           func() any { return &[]Initiatief_AndersDanGemeente_Data{} },
		Tabelnaam:              "initiatief_andersdangemeente_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Initiatief_AndersDanGemeente_Data{} },
		DBSliceFactory:         func() any { return &[]Initiatief_AndersDanGemeente_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "initiatief_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Initiatief_AndersDanGemeente",
	}
	MetaRegistry["Initiatief_AndereAPIStandaard_Data"] = TypeMeta{
		Typenaam:               "Initiatief_AndereAPIStandaard_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Initiatief_AndereAPIStandaard.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "initiatief_andereapistandaard_data",
		Padnaam:                "initiatief_andereapistandaard_data",
		Meervoud:               "initiatief_andereapistandaard_data",
		Factory:                func() Representatie { return &Initiatief_AndereAPIStandaard_Data{} },
		SliceFactory:           func() any { return &[]Initiatief_AndereAPIStandaard_Data{} },
		Tabelnaam:              "initiatief_andereapistandaard_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Initiatief_AndereAPIStandaard_Data{} },
		DBSliceFactory:         func() any { return &[]Initiatief_AndereAPIStandaard_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "initiatief_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Initiatief_AndereAPIStandaard",
	}
	MetaRegistry["InitiatiefGemeente_Data"] = TypeMeta{
		Typenaam:               "InitiatiefGemeente_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van InitiatiefGemeente.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "initiatiefgemeente_data",
		Padnaam:                "initiatiefgemeente_data",
		Meervoud:               "initiatiefgemeente_data",
		Factory:                func() Representatie { return &InitiatiefGemeente_Data{} },
		SliceFactory:           func() any { return &[]InitiatiefGemeente_Data{} },
		Tabelnaam:              "initiatiefgemeente_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &InitiatiefGemeente_Data{} },
		DBSliceFactory:         func() any { return &[]InitiatiefGemeente_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "initiatief_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "InitiatiefGemeente",
	}
	MetaRegistry["InitiatiefDomein_Data"] = TypeMeta{
		Typenaam:               "InitiatiefDomein_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van InitiatiefDomein.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "initiatiefdomein_data",
		Padnaam:                "initiatiefdomein_data",
		Meervoud:               "initiatiefdomein_data",
		Factory:                func() Representatie { return &InitiatiefDomein_Data{} },
		SliceFactory:           func() any { return &[]InitiatiefDomein_Data{} },
		Tabelnaam:              "initiatiefdomein_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &InitiatiefDomein_Data{} },
		DBSliceFactory:         func() any { return &[]InitiatiefDomein_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "initiatief_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "InitiatiefDomein",
	}
	MetaRegistry["InitiatiefAPIStandaard_Data"] = TypeMeta{
		Typenaam:               "InitiatiefAPIStandaard_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van InitiatiefAPIStandaard.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "initiatiefapistandaard_data",
		Padnaam:                "initiatiefapistandaard_data",
		Meervoud:               "initiatiefapistandaard_data",
		Factory:                func() Representatie { return &InitiatiefAPIStandaard_Data{} },
		SliceFactory:           func() any { return &[]InitiatiefAPIStandaard_Data{} },
		Tabelnaam:              "initiatiefapistandaard_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &InitiatiefAPIStandaard_Data{} },
		DBSliceFactory:         func() any { return &[]InitiatiefAPIStandaard_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "initiatief_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "InitiatiefAPIStandaard",
	}
	MetaRegistry["InitiatiefOrganisatie_Data"] = TypeMeta{
		Typenaam:               "InitiatiefOrganisatie_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van InitiatiefOrganisatie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "initiatieforganisatie_data",
		Padnaam:                "initiatieforganisatie_data",
		Meervoud:               "initiatieforganisatie_data",
		Factory:                func() Representatie { return &InitiatiefOrganisatie_Data{} },
		SliceFactory:           func() any { return &[]InitiatiefOrganisatie_Data{} },
		Tabelnaam:              "initiatieforganisatie_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &InitiatiefOrganisatie_Data{} },
		DBSliceFactory:         func() any { return &[]InitiatiefOrganisatie_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "initiatief_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "InitiatiefOrganisatie",
	}
	MetaRegistry["Initiatief_Aanvang"] = TypeMeta{
		Typenaam:               "Initiatief_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Initiatief.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "initiatief_aanvang",
		Padnaam:                "initiatief_aanvang",
		Meervoud:               "initiatief_aanvang",
		Factory:                func() Representatie { return &Initiatief_Aanvang{} },
		SliceFactory:           func() any { return &[]Initiatief_Aanvang{} },
		Tabelnaam:              "initiatief_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Initiatief_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Initiatief_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "initiatief_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Initiatief",
	}
	MetaRegistry["Initiatief_Einde"] = TypeMeta{
		Typenaam:               "Initiatief_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Initiatief.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "initiatief_einde",
		Padnaam:                "initiatief_einde",
		Meervoud:               "initiatief_einde",
		Factory:                func() Representatie { return &Initiatief_Einde{} },
		SliceFactory:           func() any { return &[]Initiatief_Einde{} },
		Tabelnaam:              "initiatief_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Initiatief_Einde{} },
		DBSliceFactory:         func() any { return &[]Initiatief_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "initiatief_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Initiatief",
	}
	MetaRegistry["Initiatief_Planning_Aanvang"] = TypeMeta{
		Typenaam:               "Initiatief_Planning_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Initiatief_Planning.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "initiatief_planning_aanvang",
		Padnaam:                "initiatief_planning_aanvang",
		Meervoud:               "initiatief_planning_aanvang",
		Factory:                func() Representatie { return &Initiatief_Planning_Aanvang{} },
		SliceFactory:           func() any { return &[]Initiatief_Planning_Aanvang{} },
		Tabelnaam:              "initiatief_planning_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Initiatief_Planning_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Initiatief_Planning_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "initiatief_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Initiatief_Planning",
	}
	MetaRegistry["Initiatief_Planning_Einde"] = TypeMeta{
		Typenaam:               "Initiatief_Planning_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Initiatief_Planning.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "initiatief_planning_einde",
		Padnaam:                "initiatief_planning_einde",
		Meervoud:               "initiatief_planning_einde",
		Factory:                func() Representatie { return &Initiatief_Planning_Einde{} },
		SliceFactory:           func() any { return &[]Initiatief_Planning_Einde{} },
		Tabelnaam:              "initiatief_planning_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Initiatief_Planning_Einde{} },
		DBSliceFactory:         func() any { return &[]Initiatief_Planning_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "initiatief_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Initiatief_Planning",
	}
	MetaRegistry["Initiatief_Product_Aanvang"] = TypeMeta{
		Typenaam:               "Initiatief_Product_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Initiatief_Product.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "initiatief_product_aanvang",
		Padnaam:                "initiatief_product_aanvang",
		Meervoud:               "initiatief_product_aanvang",
		Factory:                func() Representatie { return &Initiatief_Product_Aanvang{} },
		SliceFactory:           func() any { return &[]Initiatief_Product_Aanvang{} },
		Tabelnaam:              "initiatief_product_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Initiatief_Product_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Initiatief_Product_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "initiatief_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Initiatief_Product",
	}
	MetaRegistry["Initiatief_Product_Einde"] = TypeMeta{
		Typenaam:               "Initiatief_Product_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Initiatief_Product.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "initiatief_product_einde",
		Padnaam:                "initiatief_product_einde",
		Meervoud:               "initiatief_product_einde",
		Factory:                func() Representatie { return &Initiatief_Product_Einde{} },
		SliceFactory:           func() any { return &[]Initiatief_Product_Einde{} },
		Tabelnaam:              "initiatief_product_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Initiatief_Product_Einde{} },
		DBSliceFactory:         func() any { return &[]Initiatief_Product_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "initiatief_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Initiatief_Product",
	}
	MetaRegistry["Initiatief_Bijdrage_Aanvang"] = TypeMeta{
		Typenaam:               "Initiatief_Bijdrage_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Initiatief_Bijdrage.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "initiatief_bijdrage_aanvang",
		Padnaam:                "initiatief_bijdrage_aanvang",
		Meervoud:               "initiatief_bijdrage_aanvang",
		Factory:                func() Representatie { return &Initiatief_Bijdrage_Aanvang{} },
		SliceFactory:           func() any { return &[]Initiatief_Bijdrage_Aanvang{} },
		Tabelnaam:              "initiatief_bijdrage_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Initiatief_Bijdrage_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Initiatief_Bijdrage_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "initiatief_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Initiatief_Bijdrage",
	}
	MetaRegistry["Initiatief_Bijdrage_Einde"] = TypeMeta{
		Typenaam:               "Initiatief_Bijdrage_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Initiatief_Bijdrage.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "initiatief_bijdrage_einde",
		Padnaam:                "initiatief_bijdrage_einde",
		Meervoud:               "initiatief_bijdrage_einde",
		Factory:                func() Representatie { return &Initiatief_Bijdrage_Einde{} },
		SliceFactory:           func() any { return &[]Initiatief_Bijdrage_Einde{} },
		Tabelnaam:              "initiatief_bijdrage_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Initiatief_Bijdrage_Einde{} },
		DBSliceFactory:         func() any { return &[]Initiatief_Bijdrage_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "initiatief_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Initiatief_Bijdrage",
	}
	MetaRegistry["Organisatie"] = TypeMeta{
		Typenaam:               "Organisatie",
		Klassenaam:             "Organisatie",
		Description:            "Organisatie die betrokken is bij initiatieven in het portfolio.",
		Metatype:               MetatypeEntiteit,
		IsMaterieel:            true,
		Domein:                 "CG",
		Kleur:                  "#fde68a",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 60, Y: -2295}},
		Veldnaam:               "organisatie",
		Padnaam:                "organisaties",
		Meervoud:               "organisaties",
		Factory:                func() Representatie { return &Organisatie{} },
		SliceFactory:           func() any { return &[]Organisatie{} },
		Tabelnaam:              "organisatie",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &Organisatie{} },
		DBSliceFactory:         func() any { return &[]Organisatie{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "OrganisatieContactgegevens", JSONRolnaam: "organisatie_contactgegevens", Doeltype: "Organisatie_Contactgegevens", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Organisatienamen", JSONRolnaam: "organisatienamen", Doeltype: "Organisatie_Organisatienaam", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "BetrokkenOrganisatietypen", JSONRolnaam: "betrokken_organisatietypen", Doeltype: "Organisatie_BetrokkenOrganisatietype", Momentvoorkomen: Meervoudig},
			{Rolnaam: "Contactpersonen", JSONRolnaam: "contactpersonen", Doeltype: "Contactpersoon", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Organisatie_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Organisatie_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Organisatie_Contactgegevens"] = TypeMeta{
		Typenaam:               "Organisatie_Contactgegevens",
		Klassenaam:             "Contactgegevens",
		Description:            "Contactgegevens van de organisatie.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "CG",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Organisatie_Contactgegevens_Data",
		Kleur:                  "#fde68a",
		Veldnaam:               "contactgegevens",
		Padnaam:                "organisatie_contactgegevens",
		Meervoud:               "organisatie_contactgegevens",
		Factory:                func() Representatie { return &Organisatie_Contactgegevens_Input{} },
		Tabelnaam:              "organisatie_contactgegevens",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Organisatie_Contactgegevens{} },
		DBSliceFactory:         func() any { return &[]Organisatie_Contactgegevens{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "organisatie_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie:      &V3Positie{X: -300, Y: -2175},
			EdgeID:       "Organisatie->Organisatie_Contactgegevens",
			SourceHandle: "left",
			TargetHandle: "right",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Organisatie_Contactgegevens_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Organisatie_Organisatienaam"] = TypeMeta{
		Typenaam:               "Organisatie_Organisatienaam",
		Klassenaam:             "Organisatienaam",
		Description:            "Naam van de organisatie.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "CG",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Organisatie_Organisatienaam_Data",
		Kleur:                  "#fde68a",
		Veldnaam:               "organisatienaam",
		Padnaam:                "organisatienamen",
		Meervoud:               "organisatienamen",
		Factory:                func() Representatie { return &Organisatie_Organisatienaam_Input{} },
		Tabelnaam:              "organisatie_organisatienaam",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Organisatie_Organisatienaam{} },
		DBSliceFactory:         func() any { return &[]Organisatie_Organisatienaam{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "organisatie_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie:      &V3Positie{X: -300, Y: -2295},
			EdgeID:       "edge_1775569590393_16",
			SourceHandle: "left",
			TargetHandle: "right",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Organisatie_Organisatienaam_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Organisatie_BetrokkenOrganisatietype"] = TypeMeta{
		Typenaam:               "Organisatie_BetrokkenOrganisatietype",
		Klassenaam:             "BetrokkenOrganisatietype",
		Description:            "",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "CG",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Organisatie_BetrokkenOrganisatietype_Data",
		Kleur:                  "#fde68a",
		Veldnaam:               "betrokkenorganisatietype",
		Padnaam:                "betrokken_organisatietypen",
		Meervoud:               "betrokken_organisatietypen",
		Factory:                func() Representatie { return &Organisatie_BetrokkenOrganisatietype_Input{} },
		Tabelnaam:              "organisatie_betrokkenorganisatietype",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Organisatie_BetrokkenOrganisatietype{} },
		DBSliceFactory:         func() any { return &[]Organisatie_BetrokkenOrganisatietype{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "organisatie_id",
		Momentvoorkomen:        Meervoudig,
		Layout: &EditorLayout{
			Positie:      &V3Positie{X: 210, Y: -2100},
			EdgeID:       "edge_1775592464082_9",
			SourceHandle: "bottom",
			TargetHandle: "top",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Organisatie_BetrokkenOrganisatietype_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Contactpersoon"] = TypeMeta{
		Typenaam:                  "Contactpersoon",
		Klassenaam:                "Contactpersoon",
		Description:               "",
		Metatype:                  MetatypeRelatie,
		IsMaterieel:               false,
		Domein:                    "CG",
		GESubtype:                 GESubtypeHub,
		DataTypenaam:              "Contactpersoon_Data",
		Kleur:                     "",
		Veldnaam:                  "contactpersoon",
		Padnaam:                   "contactpersonen",
		Meervoud:                  "contactpersonen",
		Factory:                   func() Representatie { return &Contactpersoon_Input{} },
		Tabelnaam:                 "contactpersoon",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &Contactpersoon{} },
		DBSliceFactory:            func() any { return &[]Contactpersoon{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "organisatie_id",
		SecondaireEntiteitIDKolom: "persoon_id",
		Momentvoorkomen:           Enkelvoudig,
		Layout: &EditorLayout{
			Positie:          &V3Positie{X: -15, Y: -2070},
			EdgeID:           "edge_1775566660638_2",
			SourceHandle:     "bottom",
			TargetHandle:     "top",
			DoelEdgeID:       "edge_1775565921272_6",
			DoelSourceHandle: "bottom",
			DoelTargetHandle: "top",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Contactpersoon_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Organisatie_Contactgegevens_Data"] = TypeMeta{
		Typenaam:               "Organisatie_Contactgegevens_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Organisatie_Contactgegevens.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fde68a",
		Veldnaam:               "organisatie_contactgegevens_data",
		Padnaam:                "organisatie_contactgegevens_data",
		Meervoud:               "organisatie_contactgegevens_data",
		Factory:                func() Representatie { return &Organisatie_Contactgegevens_Data{} },
		SliceFactory:           func() any { return &[]Organisatie_Contactgegevens_Data{} },
		Tabelnaam:              "organisatie_contactgegevens_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Organisatie_Contactgegevens_Data{} },
		DBSliceFactory:         func() any { return &[]Organisatie_Contactgegevens_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "organisatie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Organisatie_Contactgegevens",
	}
	MetaRegistry["Organisatie_Organisatienaam_Data"] = TypeMeta{
		Typenaam:               "Organisatie_Organisatienaam_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Organisatie_Organisatienaam.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fde68a",
		Veldnaam:               "organisatie_organisatienaam_data",
		Padnaam:                "organisatie_organisatienaam_data",
		Meervoud:               "organisatie_organisatienaam_data",
		Factory:                func() Representatie { return &Organisatie_Organisatienaam_Data{} },
		SliceFactory:           func() any { return &[]Organisatie_Organisatienaam_Data{} },
		Tabelnaam:              "organisatie_organisatienaam_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Organisatie_Organisatienaam_Data{} },
		DBSliceFactory:         func() any { return &[]Organisatie_Organisatienaam_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "organisatie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Organisatie_Organisatienaam",
	}
	MetaRegistry["Organisatie_BetrokkenOrganisatietype_Data"] = TypeMeta{
		Typenaam:               "Organisatie_BetrokkenOrganisatietype_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Organisatie_BetrokkenOrganisatietype.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fde68a",
		Veldnaam:               "organisatie_betrokkenorganisatietype_data",
		Padnaam:                "organisatie_betrokkenorganisatietype_data",
		Meervoud:               "organisatie_betrokkenorganisatietype_data",
		Factory:                func() Representatie { return &Organisatie_BetrokkenOrganisatietype_Data{} },
		SliceFactory:           func() any { return &[]Organisatie_BetrokkenOrganisatietype_Data{} },
		Tabelnaam:              "organisatie_betrokkenorganisatietype_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Organisatie_BetrokkenOrganisatietype_Data{} },
		DBSliceFactory:         func() any { return &[]Organisatie_BetrokkenOrganisatietype_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "organisatie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Organisatie_BetrokkenOrganisatietype",
	}
	MetaRegistry["Contactpersoon_Data"] = TypeMeta{
		Typenaam:               "Contactpersoon_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Contactpersoon.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fde68a",
		Veldnaam:               "contactpersoon_data",
		Padnaam:                "contactpersoon_data",
		Meervoud:               "contactpersoon_data",
		Factory:                func() Representatie { return &Contactpersoon_Data{} },
		SliceFactory:           func() any { return &[]Contactpersoon_Data{} },
		Tabelnaam:              "contactpersoon_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Contactpersoon_Data{} },
		DBSliceFactory:         func() any { return &[]Contactpersoon_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "organisatie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Contactpersoon",
	}
	MetaRegistry["Organisatie_Aanvang"] = TypeMeta{
		Typenaam:               "Organisatie_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Organisatie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#fde68a",
		Veldnaam:               "organisatie_aanvang",
		Padnaam:                "organisatie_aanvang",
		Meervoud:               "organisatie_aanvang",
		Factory:                func() Representatie { return &Organisatie_Aanvang{} },
		SliceFactory:           func() any { return &[]Organisatie_Aanvang{} },
		Tabelnaam:              "organisatie_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Organisatie_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Organisatie_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "organisatie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Organisatie",
	}
	MetaRegistry["Organisatie_Einde"] = TypeMeta{
		Typenaam:               "Organisatie_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Organisatie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#fde68a",
		Veldnaam:               "organisatie_einde",
		Padnaam:                "organisatie_einde",
		Meervoud:               "organisatie_einde",
		Factory:                func() Representatie { return &Organisatie_Einde{} },
		SliceFactory:           func() any { return &[]Organisatie_Einde{} },
		Tabelnaam:              "organisatie_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Organisatie_Einde{} },
		DBSliceFactory:         func() any { return &[]Organisatie_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "organisatie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Organisatie",
	}
	MetaRegistry["Persoon"] = TypeMeta{
		Typenaam:               "Persoon",
		Klassenaam:             "Persoon",
		Description:            "Persoon die betrokken is bij initiatieven in het portfolio.",
		Metatype:               MetatypeEntiteit,
		IsMaterieel:            true,
		Domein:                 "CG",
		Kleur:                  "#fecaca",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: -15, Y: -1875}},
		Veldnaam:               "persoon",
		Padnaam:                "personen",
		Meervoud:               "personen",
		Factory:                func() Representatie { return &Persoon{} },
		SliceFactory:           func() any { return &[]Persoon{} },
		Tabelnaam:              "persoon",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &Persoon{} },
		DBSliceFactory:         func() any { return &[]Persoon{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "PersoonContactgegevens", JSONRolnaam: "persoon_contactgegevens", Doeltype: "Persoon_Contactgegevens", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Persoonnamen", JSONRolnaam: "persoonnamen", Doeltype: "Persoon_Persoonnaam", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Persoon_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Persoon_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Persoon_Contactgegevens"] = TypeMeta{
		Typenaam:               "Persoon_Contactgegevens",
		Klassenaam:             "Contactgegevens",
		Description:            "Contactgegevens van de persoon.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "CG",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Persoon_Contactgegevens_Data",
		Kleur:                  "#fecaca",
		Veldnaam:               "contactgegevens",
		Padnaam:                "persoon_contactgegevens",
		Meervoud:               "persoon_contactgegevens",
		Factory:                func() Representatie { return &Persoon_Contactgegevens_Input{} },
		Tabelnaam:              "persoon_contactgegevens",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Persoon_Contactgegevens{} },
		DBSliceFactory:         func() any { return &[]Persoon_Contactgegevens{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "persoon_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie:      &V3Positie{X: -315, Y: -1770},
			EdgeID:       "Persoon->Persoon_Contactgegevens",
			SourceHandle: "left",
			TargetHandle: "right",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Persoon_Contactgegevens_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Persoon_Persoonnaam"] = TypeMeta{
		Typenaam:               "Persoon_Persoonnaam",
		Klassenaam:             "Persoonnaam",
		Description:            "Naam van de persoon.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "CG",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Persoon_Persoonnaam_Data",
		Kleur:                  "#fecaca",
		Veldnaam:               "persoonnaam",
		Padnaam:                "persoonnamen",
		Meervoud:               "persoonnamen",
		Factory:                func() Representatie { return &Persoon_Persoonnaam_Input{} },
		Tabelnaam:              "persoon_persoonnaam",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Persoon_Persoonnaam{} },
		DBSliceFactory:         func() any { return &[]Persoon_Persoonnaam{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "persoon_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie:      &V3Positie{X: -300, Y: -1905},
			EdgeID:       "edge_1775569596827_17",
			SourceHandle: "left",
			TargetHandle: "right",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Persoon_Persoonnaam_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Persoon_Contactgegevens_Data"] = TypeMeta{
		Typenaam:               "Persoon_Contactgegevens_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Persoon_Contactgegevens.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fecaca",
		Veldnaam:               "persoon_contactgegevens_data",
		Padnaam:                "persoon_contactgegevens_data",
		Meervoud:               "persoon_contactgegevens_data",
		Factory:                func() Representatie { return &Persoon_Contactgegevens_Data{} },
		SliceFactory:           func() any { return &[]Persoon_Contactgegevens_Data{} },
		Tabelnaam:              "persoon_contactgegevens_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Persoon_Contactgegevens_Data{} },
		DBSliceFactory:         func() any { return &[]Persoon_Contactgegevens_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "persoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Persoon_Contactgegevens",
	}
	MetaRegistry["Persoon_Persoonnaam_Data"] = TypeMeta{
		Typenaam:               "Persoon_Persoonnaam_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Persoon_Persoonnaam.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fecaca",
		Veldnaam:               "persoon_persoonnaam_data",
		Padnaam:                "persoon_persoonnaam_data",
		Meervoud:               "persoon_persoonnaam_data",
		Factory:                func() Representatie { return &Persoon_Persoonnaam_Data{} },
		SliceFactory:           func() any { return &[]Persoon_Persoonnaam_Data{} },
		Tabelnaam:              "persoon_persoonnaam_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Persoon_Persoonnaam_Data{} },
		DBSliceFactory:         func() any { return &[]Persoon_Persoonnaam_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "persoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Persoon_Persoonnaam",
	}
	MetaRegistry["Persoon_Aanvang"] = TypeMeta{
		Typenaam:               "Persoon_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Persoon.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#fecaca",
		Veldnaam:               "persoon_aanvang",
		Padnaam:                "persoon_aanvang",
		Meervoud:               "persoon_aanvang",
		Factory:                func() Representatie { return &Persoon_Aanvang{} },
		SliceFactory:           func() any { return &[]Persoon_Aanvang{} },
		Tabelnaam:              "persoon_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Persoon_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Persoon_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "persoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Persoon",
	}
	MetaRegistry["Persoon_Einde"] = TypeMeta{
		Typenaam:               "Persoon_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Persoon.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#fecaca",
		Veldnaam:               "persoon_einde",
		Padnaam:                "persoon_einde",
		Meervoud:               "persoon_einde",
		Factory:                func() Representatie { return &Persoon_Einde{} },
		SliceFactory:           func() any { return &[]Persoon_Einde{} },
		Tabelnaam:              "persoon_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Persoon_Einde{} },
		DBSliceFactory:         func() any { return &[]Persoon_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "persoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Persoon",
	}

	// Referentielijst-instantie metadata + editor-posities
	ReferentielijstInstantieRegistry["AdellijkeTitels"] = ReferentielijstInstantieInfo{
		Naam:   "",
		Layout: &EditorLayout{Positie: &V3Positie{X: 1890, Y: -319.5}},
	}
	ReferentielijstInstantieRegistry["Landenlijst"] = ReferentielijstInstantieInfo{
		Naam:   "",
		Layout: &EditorLayout{Positie: &V3Positie{X: 1005, Y: -319.5}},
	}
}
