package model

// Additieve MetaRegistry-entries — voegt types toe aan de bestaande MetaRegistry.
// Gegenereerd door cmd/codegen — niet handmatig bewerken.

func initConfiguratieMetaRegistry() {
	MetaRegistry["FormulierDefinitie"] = TypeMeta{
		Typenaam:               "FormulierDefinitie",
		Klassenaam:             "FormulierDefinitie",
		Description:            "Formulierdefinitie voor custom layouts van entiteitsformulieren. Bevat metadata (naam, status, doeltype) en een JSON layout-boom. Bitemporeel: wijzigingen zijn traceerbaar en corrigeerbaar via registraties.",
		Metatype:               MetatypeEntiteit,
		IsMaterieel:            true,
		Domein:                 "configuratie",
		Kleur:                  "#c4b5fd",
		Veldnaam:               "formulierdefinitie",
		Padnaam:                "formulier_definities",
		Meervoud:               "formulier definities",
		Factory:                func() Representatie { return &FormulierDefinitie{} },
		SliceFactory:           func() any { return &[]FormulierDefinitie{} },
		Tabelnaam:              "formulierdefinitie",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &FormulierDefinitie{} },
		DBSliceFactory:         func() any { return &[]FormulierDefinitie{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "FormulierDefinitieMetas", JSONRolnaam: "formulier_definitie_metas", Doeltype: "FormulierDefinitie_Meta", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "FormulierDefinitieLayouts", JSONRolnaam: "formulier_definitie_layouts", Doeltype: "FormulierDefinitie_Layout", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "FormulierDefinitie_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "FormulierDefinitie_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["FormulierDefinitie_Meta"] = TypeMeta{
		Typenaam:               "FormulierDefinitie_Meta",
		Klassenaam:             "Meta",
		Description:            "Metadata van de formulierdefinitie: naam, beschrijving, doeltype en status.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "configuratie",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "FormulierDefinitie_Meta_Data",
		Kleur:                  "#c4b5fd",
		Veldnaam:               "meta",
		Padnaam:                "formulier_definitie_metas",
		Meervoud:               "formulier_definitie_metas",
		Factory:                func() Representatie { return &FormulierDefinitie_Meta_Input{} },
		Tabelnaam:              "formulierdefinitie_meta",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &FormulierDefinitie_Meta{} },
		DBSliceFactory:         func() any { return &[]FormulierDefinitie_Meta{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "formulierdefinitie_id",
		Momentvoorkomen:        Enkelvoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "FormulierDefinitie_Meta_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["FormulierDefinitie_Layout"] = TypeMeta{
		Typenaam:               "FormulierDefinitie_Layout",
		Klassenaam:             "Layout",
		Description:            "De layout-boom van het formulier als JSON-structuur. Bevat groepen, rijen, velden en conditionele elementen.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "configuratie",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "FormulierDefinitie_Layout_Data",
		Kleur:                  "#c4b5fd",
		Veldnaam:               "layout",
		Padnaam:                "formulier_definitie_layouts",
		Meervoud:               "formulier_definitie_layouts",
		Factory:                func() Representatie { return &FormulierDefinitie_Layout_Input{} },
		Tabelnaam:              "formulierdefinitie_layout",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &FormulierDefinitie_Layout{} },
		DBSliceFactory:         func() any { return &[]FormulierDefinitie_Layout{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "formulierdefinitie_id",
		Momentvoorkomen:        Enkelvoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "FormulierDefinitie_Layout_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["FormulierDefinitie_Meta_Data"] = TypeMeta{
		Typenaam:               "FormulierDefinitie_Meta_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van FormulierDefinitie_Meta.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#c4b5fd",
		Veldnaam:               "formulierdefinitie_meta_data",
		Padnaam:                "formulierdefinitie_meta_data",
		Meervoud:               "formulierdefinitie_meta_data",
		Factory:                func() Representatie { return &FormulierDefinitie_Meta_Data{} },
		SliceFactory:           func() any { return &[]FormulierDefinitie_Meta_Data{} },
		Tabelnaam:              "formulierdefinitie_meta_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &FormulierDefinitie_Meta_Data{} },
		DBSliceFactory:         func() any { return &[]FormulierDefinitie_Meta_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "formulierdefinitie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "FormulierDefinitie_Meta",
	}
	MetaRegistry["FormulierDefinitie_Layout_Data"] = TypeMeta{
		Typenaam:               "FormulierDefinitie_Layout_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van FormulierDefinitie_Layout.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#c4b5fd",
		Veldnaam:               "formulierdefinitie_layout_data",
		Padnaam:                "formulierdefinitie_layout_data",
		Meervoud:               "formulierdefinitie_layout_data",
		Factory:                func() Representatie { return &FormulierDefinitie_Layout_Data{} },
		SliceFactory:           func() any { return &[]FormulierDefinitie_Layout_Data{} },
		Tabelnaam:              "formulierdefinitie_layout_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &FormulierDefinitie_Layout_Data{} },
		DBSliceFactory:         func() any { return &[]FormulierDefinitie_Layout_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "formulierdefinitie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "FormulierDefinitie_Layout",
	}
	MetaRegistry["FormulierDefinitie_Aanvang"] = TypeMeta{
		Typenaam:               "FormulierDefinitie_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van FormulierDefinitie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#c4b5fd",
		Veldnaam:               "formulierdefinitie_aanvang",
		Padnaam:                "formulierdefinitie_aanvang",
		Meervoud:               "formulierdefinitie_aanvang",
		Factory:                func() Representatie { return &FormulierDefinitie_Aanvang{} },
		SliceFactory:           func() any { return &[]FormulierDefinitie_Aanvang{} },
		Tabelnaam:              "formulierdefinitie_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &FormulierDefinitie_Aanvang{} },
		DBSliceFactory:         func() any { return &[]FormulierDefinitie_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "formulierdefinitie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "FormulierDefinitie",
	}
	MetaRegistry["FormulierDefinitie_Einde"] = TypeMeta{
		Typenaam:               "FormulierDefinitie_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van FormulierDefinitie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#c4b5fd",
		Veldnaam:               "formulierdefinitie_einde",
		Padnaam:                "formulierdefinitie_einde",
		Meervoud:               "formulierdefinitie_einde",
		Factory:                func() Representatie { return &FormulierDefinitie_Einde{} },
		SliceFactory:           func() any { return &[]FormulierDefinitie_Einde{} },
		Tabelnaam:              "formulierdefinitie_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &FormulierDefinitie_Einde{} },
		DBSliceFactory:         func() any { return &[]FormulierDefinitie_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "formulierdefinitie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "FormulierDefinitie",
	}
}
