package model

// Additieve MetaRegistry-entries — voegt types toe aan de bestaande MetaRegistry.
// Gegenereerd door cmd/codegen — niet handmatig bewerken.

func initKennis2MetaRegistry() {
	MetaRegistry["Kennisartikel"] = TypeMeta{
		Typenaam:               "Kennisartikel",
		Klassenaam:             "Kennisartikel",
		Description:            "Een kennisartikel (KA) bevat als afgeleid veld de NL titel. De rest van de informatie hangt onder een KA-taalvariant.",
		Metatype:               MetatypeEntiteit,
		IsMaterieel:            true,
		Domein:                 "kennis2",
		Kleur:                  "#bfdbfe",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 297.625, Y: -0.25}},
		Veldnaam:               "kennisartikel",
		Padnaam:                "kennisartikelen",
		Meervoud:               "kennisartikelen",
		Factory:                func() Representatie { return &Kennisartikel{} },
		SliceFactory:           func() any { return &[]Kennisartikel{} },
		Tabelnaam:              "kennisartikel",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &Kennisartikel{} },
		DBSliceFactory:         func() any { return &[]Kennisartikel{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Kennisartikeltrefwoorden", JSONRolnaam: "kennisartikeltrefwoorden", Doeltype: "KA_Tr", Momentvoorkomen: Meervoudig, NaamLabelHeen: "heeft", NaamLabelTerug: "is trefwoord van"},
			{Rolnaam: "KennisartikelTaalvarianten", JSONRolnaam: "kennisartikel_taalvarianten", Doeltype: "KA_TV", Momentvoorkomen: Meervoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Kennisartikel_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Kennisartikel_Einde", Momentvoorkomen: Enkelvoudig},
		},
		AfgeleideVelden: []AfgeleidVeld{
			{
				// nl-titel: de Nederlandse titel van de NL KennisartikelTaalvariant.
				// Vereist cross-entiteit navigatie via KA_TV → KennisartikelTaalvariant.
				// De expressie evalueert wanneer KennisartikelTaalvariant in de CEL-context
				// beschikbaar is (toekomstige uitbreiding van bouwCelContext voor relaties).
				Naam:                "nl-titel",
				Description:         "De Nederlandse titel van de NL KennisartikelTaalvariant, of het id als die er niet is.",
				GoType:              "string",
				AfleidingsregelTaal: "cel",
				// Navigeert via KennisartikelTaalvarianten (rolnaam, lijst) naar de NL-variant.
				// Vereist dat bouwCelContext de KA_TV-list beschikbaar stelt, én dat de
				// doelentiteit KennisartikelTaalvariant met taal+titel in context staat.
				Afleidingsregel: `KennisartikelTaalvarianten.filter(tv, tv.taal == "nl").size() > 0 ? KennisartikelTaalvarianten.filter(tv, tv.taal == "nl")[0].titel : null`,
				IsWeergaveVeld:  true,
			},
		},
	}
	MetaRegistry["KA_Tr"] = TypeMeta{
		Typenaam:                  "KA_Tr",
		Klassenaam:                "KA_Tr",
		Description:               "",
		Metatype:                  MetatypeRelatie,
		IsMaterieel:               true,
		Domein:                    "kennis2",
		GESubtype:                 GESubtypeHub,
		DataTypenaam:              "KA_Tr_Data",
		Kleur:                     "",
		Veldnaam:                  "ka_tr",
		Padnaam:                   "kennisartikeltrefwoorden",
		Meervoud:                  "kennisartikeltrefwoorden",
		Factory:                   func() Representatie { return &KA_Tr_Input{} },
		Tabelnaam:                 "ka_tr",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &KA_Tr{} },
		DBSliceFactory:            func() any { return &[]KA_Tr{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "kennisartikel_id",
		SecondaireEntiteitIDKolom: "trefwoord_id",
		Momentvoorkomen:           Meervoudig,
		Layout:                    &EditorLayout{Positie: &V3Positie{X: 590, Y: 37.25}},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "KA_Tr_Data", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "KA_Tr_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "KA_Tr_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["KA_TV"] = TypeMeta{
		Typenaam:                  "KA_TV",
		Klassenaam:                "KA_TV",
		Description:               "",
		Metatype:                  MetatypeRelatie,
		IsMaterieel:               false,
		Domein:                    "kennis2",
		GESubtype:                 GESubtypeHub,
		DataTypenaam:              "KA_TV_Data",
		Kleur:                     "",
		Veldnaam:                  "ka_tv",
		Padnaam:                   "kennisartikel_taalvarianten",
		Meervoud:                  "kennisartikel_taalvarianten",
		Factory:                   func() Representatie { return &KA_TV_Input{} },
		Tabelnaam:                 "ka_tv",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &KA_TV{} },
		DBSliceFactory:            func() any { return &[]KA_TV{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "kennisartikel_id",
		SecondaireEntiteitIDKolom: "kennisartikeltaalvariant_id",
		Momentvoorkomen:           Meervoudig,
		Layout:                    &EditorLayout{Positie: &V3Positie{X: 358.125, Y: 180}},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "KA_TV_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["KA_Tr_Data"] = TypeMeta{
		Typenaam:               "KA_Tr_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van KA_Tr.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "ka_tr_data",
		Padnaam:                "ka_tr_data",
		Meervoud:               "ka_tr_data",
		Factory:                func() Representatie { return &KA_Tr_Data{} },
		SliceFactory:           func() any { return &[]KA_Tr_Data{} },
		Tabelnaam:              "ka_tr_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &KA_Tr_Data{} },
		DBSliceFactory:         func() any { return &[]KA_Tr_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "kennisartikel_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "KA_Tr",
	}
	MetaRegistry["KA_TV_Data"] = TypeMeta{
		Typenaam:               "KA_TV_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van KA_TV.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "ka_tv_data",
		Padnaam:                "ka_tv_data",
		Meervoud:               "ka_tv_data",
		Factory:                func() Representatie { return &KA_TV_Data{} },
		SliceFactory:           func() any { return &[]KA_TV_Data{} },
		Tabelnaam:              "ka_tv_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &KA_TV_Data{} },
		DBSliceFactory:         func() any { return &[]KA_TV_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "kennisartikel_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "KA_TV",
	}
	MetaRegistry["Kennisartikel_Aanvang"] = TypeMeta{
		Typenaam:               "Kennisartikel_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Kennisartikel.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "kennisartikel_aanvang",
		Padnaam:                "kennisartikel_aanvang",
		Meervoud:               "kennisartikel_aanvang",
		Factory:                func() Representatie { return &Kennisartikel_Aanvang{} },
		SliceFactory:           func() any { return &[]Kennisartikel_Aanvang{} },
		Tabelnaam:              "kennisartikel_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Kennisartikel_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Kennisartikel_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "kennisartikel_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Kennisartikel",
	}
	MetaRegistry["Kennisartikel_Einde"] = TypeMeta{
		Typenaam:               "Kennisartikel_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Kennisartikel.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "kennisartikel_einde",
		Padnaam:                "kennisartikel_einde",
		Meervoud:               "kennisartikel_einde",
		Factory:                func() Representatie { return &Kennisartikel_Einde{} },
		SliceFactory:           func() any { return &[]Kennisartikel_Einde{} },
		Tabelnaam:              "kennisartikel_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Kennisartikel_Einde{} },
		DBSliceFactory:         func() any { return &[]Kennisartikel_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "kennisartikel_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Kennisartikel",
	}
	MetaRegistry["KA_Tr_Aanvang"] = TypeMeta{
		Typenaam:               "KA_Tr_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van KA_Tr.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "ka_tr_aanvang",
		Padnaam:                "ka_tr_aanvang",
		Meervoud:               "ka_tr_aanvang",
		Factory:                func() Representatie { return &KA_Tr_Aanvang{} },
		SliceFactory:           func() any { return &[]KA_Tr_Aanvang{} },
		Tabelnaam:              "ka_tr_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &KA_Tr_Aanvang{} },
		DBSliceFactory:         func() any { return &[]KA_Tr_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "kennisartikel_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "KA_Tr",
	}
	MetaRegistry["KA_Tr_Einde"] = TypeMeta{
		Typenaam:               "KA_Tr_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van KA_Tr.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "ka_tr_einde",
		Padnaam:                "ka_tr_einde",
		Meervoud:               "ka_tr_einde",
		Factory:                func() Representatie { return &KA_Tr_Einde{} },
		SliceFactory:           func() any { return &[]KA_Tr_Einde{} },
		Tabelnaam:              "ka_tr_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &KA_Tr_Einde{} },
		DBSliceFactory:         func() any { return &[]KA_Tr_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "kennisartikel_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "KA_Tr",
	}
	MetaRegistry["KennisartikelTaalvariant"] = TypeMeta{
		Typenaam:               "KennisartikelTaalvariant",
		Klassenaam:             "KennisartikelTaalvariant",
		Description:            "",
		Metatype:               MetatypeEntiteit,
		IsMaterieel:            false,
		Domein:                 "kennis2",
		Kleur:                  "#bfdbfe",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 291.625, Y: 300}},
		Veldnaam:               "kennisartikeltaalvariant",
		Padnaam:                "kennisartikeltaalvarianten",
		Meervoud:               "kennisartikeltaalvarianten",
		Factory:                func() Representatie { return &KennisartikelTaalvariant{} },
		SliceFactory:           func() any { return &[]KennisartikelTaalvariant{} },
		Tabelnaam:              "kennisartikeltaalvariant",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &KennisartikelTaalvariant{} },
		DBSliceFactory:         func() any { return &[]KennisartikelTaalvariant{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Tvtitels", JSONRolnaam: "tvtitels", Doeltype: "KennisartikelTaalvariant_KennisartikeltaalvariantTitel", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Kennissecties", JSONRolnaam: "kennissecties", Doeltype: "KennisartikelTaalvariant_Sectie", Momentvoorkomen: Meervoudig},
			{Rolnaam: "Tvtalen", JSONRolnaam: "tvtalen", Doeltype: "KennisartikelTaalvariant_KennisartikelTaalvariantTaal", Momentvoorkomen: Enkelvoudig, NaamLabelHeen: "heen", NaamLabelTerug: "terug"},
		},
		AfgeleideVelden: []AfgeleidVeld{
			{
				// taal: afgeleid uit de TaalGE (Tvtalen → KennisartikelTaalvariantTaal, enkelvoudig Hub+Data).
				Naam:                "taal",
				Description:         "Taal van deze KennisartikelTaalvariant, afgeleid uit de Taal-GE.",
				GoType:              "string",
				AfleidingsregelTaal: "cel",
				Afleidingsregel:     "KennisartikelTaalvariantTaal.taal",
				IsWeergaveVeld:      true,
			},
			{
				// titel: afgeleid uit de TitelGE (Tvtitels → KennisartikeltaalvariantTitel, enkelvoudig Hub+Data).
				Naam:                "titel",
				Description:         "Titel van deze KennisartikelTaalvariant, afgeleid uit de Titel-GE.",
				GoType:              "string",
				AfleidingsregelTaal: "cel",
				Afleidingsregel:     "KennisartikeltaalvariantTitel.titel",
				IsWeergaveVeld:      true,
			},
		},
	}
	MetaRegistry["KennisartikelTaalvariant_KennisartikeltaalvariantTitel"] = TypeMeta{
		Typenaam:               "KennisartikelTaalvariant_KennisartikeltaalvariantTitel",
		Klassenaam:             "KennisartikeltaalvariantTitel",
		Description:            "",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "kennis2",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "KennisartikelTaalvariant_KennisartikeltaalvariantTitel_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "kennisartikeltaalvarianttitel",
		Padnaam:                "tvtitels",
		Meervoud:               "tvtitels",
		Factory:                func() Representatie { return &KennisartikelTaalvariant_KennisartikeltaalvariantTitel_Input{} },
		Tabelnaam:              "kennisartikeltaalvariant_kennisartikeltaalvarianttitel",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &KennisartikelTaalvariant_KennisartikeltaalvariantTitel{} },
		DBSliceFactory:         func() any { return &[]KennisartikelTaalvariant_KennisartikeltaalvariantTitel{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "kennisartikeltaalvariant_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 676.75, Y: 360}},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "KennisartikelTaalvariant_KennisartikeltaalvariantTitel_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["KennisartikelTaalvariant_Sectie"] = TypeMeta{
		Typenaam:               "KennisartikelTaalvariant_Sectie",
		Klassenaam:             "Sectie",
		Description:            "",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "kennis2",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "KennisartikelTaalvariant_Sectie_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "sectie",
		Padnaam:                "kennissecties",
		Meervoud:               "kennissecties",
		Factory:                func() Representatie { return &KennisartikelTaalvariant_Sectie_Input{} },
		Tabelnaam:              "kennisartikeltaalvariant_sectie",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &KennisartikelTaalvariant_Sectie{} },
		DBSliceFactory:         func() any { return &[]KennisartikelTaalvariant_Sectie{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "kennisartikeltaalvariant_id",
		Momentvoorkomen:        Meervoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 297.625, Y: 525},
			UseEdges: []V3UseEdge{
				{Doel: "Kennissectietype", ID: "KennisartikelTaalvariant_Sectie-->Kennissectietype"},
			},
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "KennisartikelTaalvariant_Sectie_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["KennisartikelTaalvariant_KennisartikelTaalvariantTaal"] = TypeMeta{
		Typenaam:               "KennisartikelTaalvariant_KennisartikelTaalvariantTaal",
		Klassenaam:             "KennisartikelTaalvariantTaal",
		Description:            "",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "kennis2",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "KennisartikelTaalvariant_KennisartikelTaalvariantTaal_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "kennisartikeltaalvarianttaal",
		Padnaam:                "tvtalen",
		Meervoud:               "tvtalen",
		Factory:                func() Representatie { return &KennisartikelTaalvariant_KennisartikelTaalvariantTaal_Input{} },
		Tabelnaam:              "kennisartikeltaalvariant_kennisartikeltaalvarianttaal",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &KennisartikelTaalvariant_KennisartikelTaalvariantTaal{} },
		DBSliceFactory:         func() any { return &[]KennisartikelTaalvariant_KennisartikelTaalvariantTaal{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "kennisartikeltaalvariant_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 676.75, Y: 256.75},
			UseEdges: []V3UseEdge{
				{Doel: "Taal", ID: "KennisartikelTaalvariant_KennisartikelTaalvariantTaal-->Taal"},
			},
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "KennisartikelTaalvariant_KennisartikelTaalvariantTaal_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["KennisartikelTaalvariant_KennisartikeltaalvariantTitel_Data"] = TypeMeta{
		Typenaam:               "KennisartikelTaalvariant_KennisartikeltaalvariantTitel_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van KennisartikelTaalvariant_KennisartikeltaalvariantTitel.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "kennisartikeltaalvariant_kennisartikeltaalvarianttitel_data",
		Padnaam:                "kennisartikeltaalvariant_kennisartikeltaalvarianttitel_data",
		Meervoud:               "kennisartikeltaalvariant_kennisartikeltaalvarianttitel_data",
		Factory:                func() Representatie { return &KennisartikelTaalvariant_KennisartikeltaalvariantTitel_Data{} },
		SliceFactory:           func() any { return &[]KennisartikelTaalvariant_KennisartikeltaalvariantTitel_Data{} },
		Tabelnaam:              "kennisartikeltaalvariant_kennisartikeltaalvarianttitel_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &KennisartikelTaalvariant_KennisartikeltaalvariantTitel_Data{} },
		DBSliceFactory:         func() any { return &[]KennisartikelTaalvariant_KennisartikeltaalvariantTitel_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "kennisartikeltaalvariant_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "KennisartikelTaalvariant_KennisartikeltaalvariantTitel",
	}
	MetaRegistry["KennisartikelTaalvariant_Sectie_Data"] = TypeMeta{
		Typenaam:               "KennisartikelTaalvariant_Sectie_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van KennisartikelTaalvariant_Sectie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "kennisartikeltaalvariant_sectie_data",
		Padnaam:                "kennisartikeltaalvariant_sectie_data",
		Meervoud:               "kennisartikeltaalvariant_sectie_data",
		Factory:                func() Representatie { return &KennisartikelTaalvariant_Sectie_Data{} },
		SliceFactory:           func() any { return &[]KennisartikelTaalvariant_Sectie_Data{} },
		Tabelnaam:              "kennisartikeltaalvariant_sectie_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &KennisartikelTaalvariant_Sectie_Data{} },
		DBSliceFactory:         func() any { return &[]KennisartikelTaalvariant_Sectie_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "kennisartikeltaalvariant_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "KennisartikelTaalvariant_Sectie",
	}
	MetaRegistry["KennisartikelTaalvariant_KennisartikelTaalvariantTaal_Data"] = TypeMeta{
		Typenaam:               "KennisartikelTaalvariant_KennisartikelTaalvariantTaal_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van KennisartikelTaalvariant_KennisartikelTaalvariantTaal.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "kennisartikeltaalvariant_kennisartikeltaalvarianttaal_data",
		Padnaam:                "kennisartikeltaalvariant_kennisartikeltaalvarianttaal_data",
		Meervoud:               "kennisartikeltaalvariant_kennisartikeltaalvarianttaal_data",
		Factory:                func() Representatie { return &KennisartikelTaalvariant_KennisartikelTaalvariantTaal_Data{} },
		SliceFactory:           func() any { return &[]KennisartikelTaalvariant_KennisartikelTaalvariantTaal_Data{} },
		Tabelnaam:              "kennisartikeltaalvariant_kennisartikeltaalvarianttaal_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &KennisartikelTaalvariant_KennisartikelTaalvariantTaal_Data{} },
		DBSliceFactory:         func() any { return &[]KennisartikelTaalvariant_KennisartikelTaalvariantTaal_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "kennisartikeltaalvariant_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "KennisartikelTaalvariant_KennisartikelTaalvariantTaal",
	}
	MetaRegistry["Trefwoord"] = TypeMeta{
		Typenaam:               "Trefwoord",
		Klassenaam:             "Trefwoord",
		Description:            "",
		Metatype:               MetatypeEntiteit,
		EntiteitSubtype:        EntiteitSubtypeReferentielijstItem,
		IsMaterieel:            false,
		Domein:                 "kennis2",
		Kleur:                  "#fff3c7",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 695.75, Y: 8.25}},
		Veldnaam:               "trefwoord",
		Padnaam:                "trefwoorden",
		Meervoud:               "trefwoorden",
		Factory:                func() Representatie { return &Trefwoord{} },
		SliceFactory:           func() any { return &[]Trefwoord{} },
		Tabelnaam:              "trefwoord",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &Trefwoord{} },
		DBSliceFactory:         func() any { return &[]Trefwoord{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Trefwoordtaalvarianten", JSONRolnaam: "trefwoordtaalvarianten", Doeltype: "Trefwoord_TrefwoordTaalvariant", Momentvoorkomen: Meervoudig},
		},
		AfgeleideVelden: []AfgeleidVeld{
			{
				// nl-trefwoord: het Nederlandse trefwoord uit de meervoudige TrefwoordTaalvariant GE.
				// bouwCelContext selecteert het eerste actieve TrefwoordTaalvariant-item.
				// De expressie controleert of dat item taal=nl heeft; voor volledige lijst-filter
				// ondersteuning dient de CEL-evaluator te worden uitgebreid met .filter().
				Naam:                "nl-trefwoord",
				Description:         "Het Nederlandse trefwoord (TrefwoordTaalvariant met taal=nl).",
				GoType:              "string",
				AfleidingsregelTaal: "cel",
				// Filtert de lijst van TrefwoordTaalvariant GE's op taal=nl.
				// Rolnaam Trefwoordtaalvarianten is beschikbaar in de CEL-context als array.
				Afleidingsregel: `Trefwoordtaalvarianten.filter(t, t.taal == "nl").size() > 0 ? Trefwoordtaalvarianten.filter(t, t.taal == "nl")[0].woord : Trefwoordtaalvarianten.size() > 0 ? Trefwoordtaalvarianten[0].woord : null`,
				IsWeergaveVeld:  true,
			},
		},
	}
	MetaRegistry["Trefwoord_TrefwoordTaalvariant"] = TypeMeta{
		Typenaam:               "Trefwoord_TrefwoordTaalvariant",
		Klassenaam:             "TrefwoordTaalvariant",
		Description:            "",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "kennis2",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Trefwoord_TrefwoordTaalvariant_Data",
		Kleur:                  "#fff3c7",
		Veldnaam:               "trefwoordtaalvariant",
		Padnaam:                "trefwoordtaalvarianten",
		Meervoud:               "trefwoordtaalvarianten",
		Factory:                func() Representatie { return &Trefwoord_TrefwoordTaalvariant_Input{} },
		Tabelnaam:              "trefwoord_trefwoordtaalvariant",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Trefwoord_TrefwoordTaalvariant{} },
		DBSliceFactory:         func() any { return &[]Trefwoord_TrefwoordTaalvariant{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "trefwoord_id",
		Momentvoorkomen:        Meervoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 1050, Y: -0.25},
			UseEdges: []V3UseEdge{
				{Doel: "Taal", ID: "Trefwoord_Trefwoord-->Taal"},
			},
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Trefwoord_TrefwoordTaalvariant_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Trefwoord_TrefwoordTaalvariant_Data"] = TypeMeta{
		Typenaam:               "Trefwoord_TrefwoordTaalvariant_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Trefwoord_TrefwoordTaalvariant.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fff3c7",
		Veldnaam:               "trefwoord_trefwoordtaalvariant_data",
		Padnaam:                "trefwoord_trefwoordtaalvariant_data",
		Meervoud:               "trefwoord_trefwoordtaalvariant_data",
		Factory:                func() Representatie { return &Trefwoord_TrefwoordTaalvariant_Data{} },
		SliceFactory:           func() any { return &[]Trefwoord_TrefwoordTaalvariant_Data{} },
		Tabelnaam:              "trefwoord_trefwoordtaalvariant_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Trefwoord_TrefwoordTaalvariant_Data{} },
		DBSliceFactory:         func() any { return &[]Trefwoord_TrefwoordTaalvariant_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "trefwoord_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Trefwoord_TrefwoordTaalvariant",
	}

	// Referentielijst-instantie metadata + editor-posities
	ReferentielijstInstantieRegistry["AdellijkeTitels"] = ReferentielijstInstantieInfo{
		Naam:   "",
		Layout: &EditorLayout{Positie: &V3Positie{X: 1920, Y: -330}},
	}
	ReferentielijstInstantieRegistry["Landenlijst"] = ReferentielijstInstantieInfo{
		Naam:   "",
		Layout: &EditorLayout{Positie: &V3Positie{X: 1005, Y: -319.5}},
	}
}
