package model

// MetaRegistry is the hardcoded meta model registry.
var MetaRegistry = MetaRegistryType{
	"A": {
		// UML
		Typenaam:    "A",
		Description: "Entiteit A met materiele tijdlijn en onderliggende representaties U, V, W en Rel_A_B.",
		Metatype:    MetatypeEntiteit,
		IsMaterieel: true,
		Kleur:       "#bfdbfe",
		// JSON veldnaam in REST requests
		Veldnaam:     "a",
		Padnaam:      "as",
		Factory:      func() Representatie { return &A{} },
		SliceFactory: func() any { return &[]A{} },
		// Database
		Tabelnaam:      "a",
		IDKolom:        "id",
		DBFactory:      func() Representatie { return &A{} },
		DBSliceFactory: func() any { return &[]A{} },
		// Alleen voor gegevenselementen/relaties:
		// die hebben een FK naar een of twee entiteiten
		HeeftPFK:                  false,
		RelatieveAutoincrement:    false,
		EntiteitIDKolom:           "",
		SecondaireEntiteitIDKolom: "",
		// Alleen voor entiteiten: de onderliggende gegevenselementen/relaties
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Us", JSONRolnaam: "us", Doeltype: "A_U", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Vs", JSONRolnaam: "vs", Doeltype: "A_V", Momentvoorkomen: Meervoudig},
			{Rolnaam: "Ws", JSONRolnaam: "ws", Doeltype: "A_W", Momentvoorkomen: Meervoudig},
			{Rolnaam: "RelABs", JSONRolnaam: "rel_abs", Doeltype: "Rel_A_B", Momentvoorkomen: Meervoudig},
			// Materiële tijdlijn: aanvang/einde als enkelvoudige plumbing-GE's (zie materiele_tijd.md)
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "A_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "A_Einde", Momentvoorkomen: Enkelvoudig},
		},
	},
	"B": {
		// UML
		Typenaam:    "B",
		Description: "Entiteit B met materiele tijdlijn en onderliggende representaties X en Y.",
		Metatype:    MetatypeEntiteit,
		IsMaterieel: true,
		Kleur:       "#fecaca",
		// JSON veldnaam in REST requests
		Veldnaam:     "b",
		Padnaam:      "bs",
		Factory:      func() Representatie { return &B{} },
		SliceFactory: func() any { return &[]B{} },
		// Database
		Tabelnaam:      "b",
		IDKolom:        "id",
		DBFactory:      func() Representatie { return &B{} },
		DBSliceFactory: func() any { return &[]B{} },
		// Alleen voor gegevenselementen/relaties:
		// die hebben een FK naar een of twee entiteiten
		HeeftPFK:                  false,
		RelatieveAutoincrement:    false,
		EntiteitIDKolom:           "",
		SecondaireEntiteitIDKolom: "",
		// Alleen voor entiteiten: de onderliggende gegevenselementen/relaties
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Xs", JSONRolnaam: "xs", Doeltype: "B_X", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Ys", JSONRolnaam: "ys", Doeltype: "B_Y", Momentvoorkomen: Enkelvoudig},
			// Materiële tijdlijn: aanvang/einde als enkelvoudige plumbing-GE's (zie materiele_tijd.md)
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "B_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "B_Einde", Momentvoorkomen: Enkelvoudig},
		},
	},
	"Rel_A_B": {
		// UML
		Typenaam:     "Rel_A_B",
		Description:  "Relatie tussen A en B, meervoudig voorkomend per A en met relatieve relatie-id.",
		Metatype:     MetatypeRelatie,
		IsMaterieel:  true,
		GESubtype:    GESubtypeHub,
		DataTypenaam: "Rel_A_B_Data",
		Kleur:        "#ede9fe",
		// JSON veldnaam in REST requests
		Veldnaam: "rel_a_b",
		Padnaam:  "rel_a_bs",
		Factory:  func() Representatie { return &Rel_A_B_Input{} },
		// Database
		Tabelnaam:      "rel_a_b",
		IDKolom:        "rel_id",
		DBFactory:      func() Representatie { return &Rel_A_B{} },
		DBSliceFactory: func() any { return &[]Rel_A_B{} },
		// Alleen voor gegevenselementen/relaties:
		// die hebben een FK naar een (of twee bij relaties) entiteiten
		HeeftPFK:                  true,
		EntiteitIDKolom:           "a_id",
		RelatieveAutoincrement:    true,
		SecondaireEntiteitIDKolom: "b_id",
		Momentvoorkomen:           Meervoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Rel_A_B_Data", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Rel_A_B_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Rel_A_B_Einde", Momentvoorkomen: Enkelvoudig},
		},
	},
	"A_U": {
		// UML
		Typenaam:     "A_U",
		Description:  "Enkelvoudig gegevenselement van A met formele tijdlijn.",
		Metatype:     MetatypeGegevenselement,
		IsMaterieel:  false,
		GESubtype:    GESubtypeHub,
		DataTypenaam: "A_U_Data",
		Kleur:        "#dbeafe",
		// JSON veldnaam in REST requests
		Veldnaam: "u",
		Padnaam:  "a_us",
		Factory:  func() Representatie { return &A_U_Input{} },
		// Database
		Tabelnaam:                 "a_u",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &A_U{} },
		DBSliceFactory:            func() any { return &[]A_U{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "a_id",
		SecondaireEntiteitIDKolom: "",
		Momentvoorkomen:           Enkelvoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "A_U_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"A_V": {
		// UML
		Typenaam:     "A_V",
		Description:  "Meervoudig gegevenselement van A met onder andere een datumveld.",
		Metatype:     MetatypeGegevenselement,
		IsMaterieel:  false,
		GESubtype:    GESubtypeHub,
		DataTypenaam: "A_V_Data",
		Kleur:        "#c7f9cc",
		// JSON veldnaam in REST requests
		Veldnaam: "v",
		Padnaam:  "a_vs",
		Factory:  func() Representatie { return &A_V_Input{} },
		// Database
		Tabelnaam:                 "a_v",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &A_V{} },
		DBSliceFactory:            func() any { return &[]A_V{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "a_id",
		SecondaireEntiteitIDKolom: "",
		Momentvoorkomen:           Meervoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "A_V_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"A_W": {
		// UML
		Typenaam:     "A_W",
		Description:  "Meervoudig gegevenselement van A met numerieke waarden.",
		Metatype:     MetatypeGegevenselement,
		IsMaterieel:  true,
		GESubtype:    GESubtypeHub,
		DataTypenaam: "A_W_Data",
		Kleur:        "#bbf7d0",
		// JSON veldnaam in REST requests
		Veldnaam: "w",
		Padnaam:  "a_ws",
		Factory:  func() Representatie { return &A_W_Input{} },
		// Database
		Tabelnaam:                 "a_w",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &A_W{} },
		DBSliceFactory:            func() any { return &[]A_W{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "a_id",
		SecondaireEntiteitIDKolom: "",
		Momentvoorkomen:           Meervoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "A_W_Data", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "A_W_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "A_W_Einde", Momentvoorkomen: Enkelvoudig},
		},
	},
	"B_X": {
		// UML
		Typenaam:     "B_X",
		Description:  "Enkelvoudig gegevenselement van B met twee tekstvelden.",
		Metatype:     MetatypeGegevenselement,
		IsMaterieel:  false,
		GESubtype:    GESubtypeHub,
		DataTypenaam: "B_X_Data",
		Kleur:        "#fdba74",
		// JSON veldnaam in REST requests
		Veldnaam: "x",
		Padnaam:  "b_xs",
		Factory:  func() Representatie { return &B_X_Input{} },
		// Database
		Tabelnaam:                 "b_x",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &B_X{} },
		DBSliceFactory:            func() any { return &[]B_X{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "b_id",
		SecondaireEntiteitIDKolom: "",
		Momentvoorkomen:           Enkelvoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "B_X_Data", Momentvoorkomen: Enkelvoudig},
		},
	},
	"B_Y": {
		// UML
		Typenaam:     "B_Y",
		Description:  "Enkelvoudig gegevenselement van B met een tekstveld.",
		Metatype:     MetatypeGegevenselement,
		IsMaterieel:  false,
		GESubtype:    GESubtypeHub,
		DataTypenaam: "B_Y_Data",
		Kleur:        "#fde68a",
		// JSON veldnaam in REST requests
		Veldnaam: "y",
		Padnaam:  "b_ys",
		Factory:  func() Representatie { return &B_Y_Input{} },
		// Database
		Tabelnaam:                 "b_y",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &B_Y{} },
		DBSliceFactory:            func() any { return &[]B_Y{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "b_id",
		SecondaireEntiteitIDKolom: "",
		Momentvoorkomen:           Enkelvoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "B_Y_Data", Momentvoorkomen: Enkelvoudig},
		},
	},

	// ==== Aanvang/Einde als materiële GE-types per entiteitstype ====
	// Gedragen zich als enkelvoudige gegevenselementen; worden afgehandeld door handleRepresentatieOpvoer.
	"A_Aanvang": {
		Typenaam:               "A_Aanvang",
		Description:            "Aanvangsdatum van entiteit A.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "a_aanvang",
		Padnaam:                "a_aanvang",
		Factory:                func() Representatie { return &A_Aanvang{} },
		SliceFactory:           func() any { return &[]A_Aanvang{} },
		Tabelnaam:              "a_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &A_Aanvang{} },
		DBSliceFactory:         func() any { return &[]A_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id", // hernoemd van "id" → "a_id" (consistent met andere GE-types)
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "A",
	},
	"A_Einde": {
		Typenaam:               "A_Einde",
		Description:            "Einddatum van entiteit A.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "a_einde",
		Padnaam:                "a_einde",
		Factory:                func() Representatie { return &A_Einde{} },
		SliceFactory:           func() any { return &[]A_Einde{} },
		Tabelnaam:              "a_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &A_Einde{} },
		DBSliceFactory:         func() any { return &[]A_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id", // hernoemd van "id" → "a_id"
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "A",
	},
	"B_Aanvang": {
		Typenaam:               "B_Aanvang",
		Description:            "Aanvangsdatum van entiteit B.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Kleur:                  "#fecaca",
		Veldnaam:               "b_aanvang",
		Padnaam:                "b_aanvang",
		Factory:                func() Representatie { return &B_Aanvang{} },
		SliceFactory:           func() any { return &[]B_Aanvang{} },
		Tabelnaam:              "b_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &B_Aanvang{} },
		DBSliceFactory:         func() any { return &[]B_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "b_id", // hernoemd van "id" → "b_id"
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "B",
	},
	"B_Einde": {
		Typenaam:               "B_Einde",
		Description:            "Einddatum van entiteit B.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Kleur:                  "#fecaca",
		Veldnaam:               "b_einde",
		Padnaam:                "b_einde",
		Factory:                func() Representatie { return &B_Einde{} },
		SliceFactory:           func() any { return &[]B_Einde{} },
		Tabelnaam:              "b_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &B_Einde{} },
		DBSliceFactory:         func() any { return &[]B_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "b_id", // hernoemd van "id" → "b_id"
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "B",
	},

	// ==== _Data entries: geversioned inhoud per hub ====
	// Elk _Data type is gekoppeld aan een hub via BovenliggendTypenaam.
	// PK: (ent_id, rel_id, versie). IDKolom = "versie".
	// Versie incrementeert per (ent_id, rel_id) via composite trigger.
	// Factory en DBFactory zijn identiek (geen _Input nodig voor _Data).

	"A_U_Data": {
		Typenaam:               "A_U_Data",
		Description:            "Geversioned inhoud van gegevenselement A_U.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		IsMaterieel:            false,
		Kleur:                  "#dbeafe",
		Veldnaam:               "a_u_data",
		Padnaam:                "a_u_data",
		Factory:                func() Representatie { return &A_U_Data{} },
		SliceFactory:           func() any { return &[]A_U_Data{} },
		Tabelnaam:              "a_u_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &A_U_Data{} },
		DBSliceFactory:         func() any { return &[]A_U_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "A_U",
	},
	"A_V_Data": {
		Typenaam:               "A_V_Data",
		Description:            "Geversioned inhoud van gegevenselement A_V.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		IsMaterieel:            false,
		Kleur:                  "#c7f9cc",
		Veldnaam:               "a_v_data",
		Padnaam:                "a_v_data",
		Factory:                func() Representatie { return &A_V_Data{} },
		SliceFactory:           func() any { return &[]A_V_Data{} },
		Tabelnaam:              "a_v_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &A_V_Data{} },
		DBSliceFactory:         func() any { return &[]A_V_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "A_V",
	},
	"A_W_Data": {
		Typenaam:               "A_W_Data",
		Description:            "Geversioned inhoud van gegevenselement A_W.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		IsMaterieel:            false,
		Kleur:                  "#bbf7d0",
		Veldnaam:               "a_w_data",
		Padnaam:                "a_w_data",
		Factory:                func() Representatie { return &A_W_Data{} },
		SliceFactory:           func() any { return &[]A_W_Data{} },
		Tabelnaam:              "a_w_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &A_W_Data{} },
		DBSliceFactory:         func() any { return &[]A_W_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "A_W",
	},
	"Rel_A_B_Data": {
		Typenaam:               "Rel_A_B_Data",
		Description:            "Geversioned inhoud van relatie Rel_A_B.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		IsMaterieel:            false,
		Kleur:                  "#ede9fe",
		Veldnaam:               "rel_a_b_data",
		Padnaam:                "rel_a_b_data",
		Factory:                func() Representatie { return &Rel_A_B_Data{} },
		SliceFactory:           func() any { return &[]Rel_A_B_Data{} },
		Tabelnaam:              "rel_a_b_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Rel_A_B_Data{} },
		DBSliceFactory:         func() any { return &[]Rel_A_B_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Rel_A_B",
	},
	"B_X_Data": {
		Typenaam:               "B_X_Data",
		Description:            "Geversioned inhoud van gegevenselement B_X.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		IsMaterieel:            false,
		Kleur:                  "#fdba74",
		Veldnaam:               "b_x_data",
		Padnaam:                "b_x_data",
		Factory:                func() Representatie { return &B_X_Data{} },
		SliceFactory:           func() any { return &[]B_X_Data{} },
		Tabelnaam:              "b_x_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &B_X_Data{} },
		DBSliceFactory:         func() any { return &[]B_X_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "b_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "B_X",
	},
	"B_Y_Data": {
		Typenaam:               "B_Y_Data",
		Description:            "Geversioned inhoud van gegevenselement B_Y.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		IsMaterieel:            false,
		Kleur:                  "#fde68a",
		Veldnaam:               "b_y_data",
		Padnaam:                "b_y_data",
		Factory:                func() Representatie { return &B_Y_Data{} },
		SliceFactory:           func() any { return &[]B_Y_Data{} },
		Tabelnaam:              "b_y_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &B_Y_Data{} },
		DBSliceFactory:         func() any { return &[]B_Y_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "b_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "B_Y",
	},

	// ==== Hub-level _Aanvang/_Einde: materiële plumbing voor hubs ====
	// Analoog aan entiteits-plumbing (A_Aanvang, B_Einde), maar met drieledige PK
	// (ent_id, rel_id, versie) omdat ze onder een hub hangen i.p.v. direct
	// onder een entiteit. Alleen voor materiële hubs (A_W, Rel_A_B).

	"A_W_Aanvang": {
		Typenaam:               "A_W_Aanvang",
		Description:            "Aanvangsdatum van GE-hub A_W.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		IsMaterieel:            false,
		Kleur:                  "#bbf7d0",
		Veldnaam:               "a_w_aanvang",
		Padnaam:                "a_w_aanvang",
		Factory:                func() Representatie { return &A_W_Aanvang{} },
		SliceFactory:           func() any { return &[]A_W_Aanvang{} },
		Tabelnaam:              "a_w_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &A_W_Aanvang{} },
		DBSliceFactory:         func() any { return &[]A_W_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "A_W",
	},
	"A_W_Einde": {
		Typenaam:               "A_W_Einde",
		Description:            "Einddatum van GE-hub A_W.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		IsMaterieel:            false,
		Kleur:                  "#bbf7d0",
		Veldnaam:               "a_w_einde",
		Padnaam:                "a_w_einde",
		Factory:                func() Representatie { return &A_W_Einde{} },
		SliceFactory:           func() any { return &[]A_W_Einde{} },
		Tabelnaam:              "a_w_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &A_W_Einde{} },
		DBSliceFactory:         func() any { return &[]A_W_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "A_W",
	},
	"Rel_A_B_Aanvang": {
		Typenaam:               "Rel_A_B_Aanvang",
		Description:            "Aanvangsdatum van relatie-hub Rel_A_B.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		IsMaterieel:            false,
		Kleur:                  "#ede9fe",
		Veldnaam:               "rel_a_b_aanvang",
		Padnaam:                "rel_a_b_aanvang",
		Factory:                func() Representatie { return &Rel_A_B_Aanvang{} },
		SliceFactory:           func() any { return &[]Rel_A_B_Aanvang{} },
		Tabelnaam:              "rel_a_b_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Rel_A_B_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Rel_A_B_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Rel_A_B",
	},
	"Rel_A_B_Einde": {
		Typenaam:               "Rel_A_B_Einde",
		Description:            "Einddatum van relatie-hub Rel_A_B.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		IsMaterieel:            false,
		Kleur:                  "#ede9fe",
		Veldnaam:               "rel_a_b_einde",
		Padnaam:                "rel_a_b_einde",
		Factory:                func() Representatie { return &Rel_A_B_Einde{} },
		SliceFactory:           func() any { return &[]Rel_A_B_Einde{} },
		Tabelnaam:              "rel_a_b_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Rel_A_B_Einde{} },
		DBSliceFactory:         func() any { return &[]Rel_A_B_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "a_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Rel_A_B",
	},
}
