package model

// Additieve MetaRegistry-entries — voegt types toe aan de bestaande MetaRegistry.
// Gegenereerd door cmd/codegen — niet handmatig bewerken.

func init() {
	MetaRegistry["NatuurlijkPersoon"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon",
		Klassenaam:             "NatuurlijkPersoon",
		Description:            "Entiteit A met materiële tijdlijn en onderliggende representaties U, V, W en Rel_A_B.",
		Metatype:               MetatypeEntiteit,
		IsMaterieel:            true,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon",
		Padnaam:                "natuurlijk_personen",
		Meervoud:               "natuurlijk_personen",
		Factory:                func() Representatie { return &NatuurlijkPersoon{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon{} },
		Tabelnaam:              "natuurlijkpersoon",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Persoonsidentificaties", JSONRolnaam: "persoonsidentificaties", Doeltype: "NatuurlijkPersoon_Persoonsidentificatie", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Namen", JSONRolnaam: "namen", Doeltype: "NatuurlijkPersoon_Naam", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Burgerschappen", JSONRolnaam: "burgerschappen", Doeltype: "NatuurlijkPersoon_Burgerschap", Momentvoorkomen: Meervoudig},
			{Rolnaam: "Partnernamen", JSONRolnaam: "partnernamen", Doeltype: "NatuurlijkPersoon_Partnernaam", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Naamgebruiken", JSONRolnaam: "naamgebruiken", Doeltype: "NatuurlijkPersoon_Naamgebruik", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Bereikbaarheden", JSONRolnaam: "bereikbaarheden", Doeltype: "Bereikbaarheid", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "NatuurlijkPersoon_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "NatuurlijkPersoon_Einde", Momentvoorkomen: Enkelvoudig},
		},
		AfgeleideVelden: []AfgeleidVeld{
			{
				Naam:                "weergavenaam",
				Description:         "Samengestelde weergavenaam van de persoon, afgeleid uit voornaam/tussenvoegsel/achternaam.",
				GoType:              "string",
				AfleidingsregelTaal: "cel",
				Afleidingsregel:     "(Naam.roepnaam != null ? Naam.roepnaam : Naam.voorletters) + (Naam.tussenvoegsel != null ? ' ' + Naam.tussenvoegsel : '') + ' ' + Naam.achternaam",
				IsWeergaveVeld:      true,
			},
		},
	}
	MetaRegistry["NatuurlijkPersoon_Persoonsidentificatie"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon_Persoonsidentificatie",
		Klassenaam:             "Persoonsidentificatie",
		Description:            "Enkelvoudig gegevenselement van A met formele tijdlijn.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "NatuurlijkPersoon_Persoonsidentificatie_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "persoonsidentificatie",
		Padnaam:                "persoonsidentificaties",
		Meervoud:               "persoonsidentificaties",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Persoonsidentificatie_Input{} },
		Tabelnaam:              "natuurlijkpersoon_persoonsidentificatie",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Persoonsidentificatie{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Persoonsidentificatie{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "NatuurlijkPersoon_Persoonsidentificatie_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["NatuurlijkPersoon_Naam"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon_Naam",
		Klassenaam:             "Naam",
		Description:            "Meervoudig gegevenselement van A met onder andere een datumveld.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "NatuurlijkPersoon_Naam_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "naam",
		Padnaam:                "namen",
		Meervoud:               "namen",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Naam_Input{} },
		Tabelnaam:              "natuurlijkpersoon_naam",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Naam{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Naam{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "NatuurlijkPersoon_Naam_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["NatuurlijkPersoon_Burgerschap"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon_Burgerschap",
		Klassenaam:             "Burgerschap",
		Description:            "Meervoudig gegevenselement van A met numerieke waarden.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            true,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "NatuurlijkPersoon_Burgerschap_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "burgerschap",
		Padnaam:                "burgerschappen",
		Meervoud:               "burgerschappen",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Burgerschap_Input{} },
		Tabelnaam:              "natuurlijkpersoon_burgerschap",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Burgerschap{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Burgerschap{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Meervoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "NatuurlijkPersoon_Burgerschap_Data", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "NatuurlijkPersoon_Burgerschap_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "NatuurlijkPersoon_Burgerschap_Einde", Momentvoorkomen: Enkelvoudig},
		},
		AfgeleideVelden: []AfgeleidVeld{
			{
				Naam:                "weergaveburgerschap",
				Description:         "Samengestelde weergave van nationaliteit en landcode.",
				GoType:              "string",
				AfleidingsregelTaal: "cel",
				Afleidingsregel:     "Burgerschap_Data.nationaliteit + ' (' + Burgerschap_Data.landcode + ')'",
				IsWeergaveVeld:      true,
			},
		},
	}
	MetaRegistry["NatuurlijkPersoon_Partnernaam"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon_Partnernaam",
		Klassenaam:             "Partnernaam",
		Description:            "",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "NatuurlijkPersoon_Partnernaam_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "partnernaam",
		Padnaam:                "partnernamen",
		Meervoud:               "partnernamen",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Partnernaam_Input{} },
		Tabelnaam:              "natuurlijkpersoon_partnernaam",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Partnernaam{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Partnernaam{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "NatuurlijkPersoon_Partnernaam_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["NatuurlijkPersoon_Naamgebruik"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon_Naamgebruik",
		Klassenaam:             "Naamgebruik",
		Description:            "",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "NatuurlijkPersoon_Naamgebruik_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "naamgebruik",
		Padnaam:                "naamgebruiken",
		Meervoud:               "naamgebruiken",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Naamgebruik_Input{} },
		Tabelnaam:              "natuurlijkpersoon_naamgebruik",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Naamgebruik{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Naamgebruik{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "NatuurlijkPersoon_Naamgebruik_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Bereikbaarheid"] = TypeMeta{
		Typenaam:                  "Bereikbaarheid",
		Klassenaam:                "Bereikbaarheid",
		Description:               "",
		Metatype:                  MetatypeRelatie,
		IsMaterieel:               true,
		GESubtype:                 GESubtypeHub,
		DataTypenaam:              "Bereikbaarheid_Data",
		Kleur:                     "",
		Veldnaam:                  "bereikbaarheid",
		Padnaam:                   "bereikbaarheden",
		Meervoud:                  "bereikbaarheden",
		Factory:                   func() Representatie { return &Bereikbaarheid_Input{} },
		Tabelnaam:                 "bereikbaarheid",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &Bereikbaarheid{} },
		DBSliceFactory:            func() any { return &[]Bereikbaarheid{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "natuurlijkpersoon_id",
		SecondaireEntiteitIDKolom: "locatie_id",
		Momentvoorkomen:           Enkelvoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Bereikbaarheid_Data", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Bereikbaarheid_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Bereikbaarheid_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["NatuurlijkPersoon_Persoonsidentificatie_Data"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon_Persoonsidentificatie_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van NatuurlijkPersoon_Persoonsidentificatie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_persoonsidentificatie_data",
		Padnaam:                "natuurlijkpersoon_persoonsidentificatie_data",
		Meervoud:               "natuurlijkpersoon_persoonsidentificatie_data",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Persoonsidentificatie_Data{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Persoonsidentificatie_Data{} },
		Tabelnaam:              "natuurlijkpersoon_persoonsidentificatie_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Persoonsidentificatie_Data{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Persoonsidentificatie_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon_Persoonsidentificatie",
	}
	MetaRegistry["NatuurlijkPersoon_Naam_Data"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon_Naam_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van NatuurlijkPersoon_Naam.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_naam_data",
		Padnaam:                "natuurlijkpersoon_naam_data",
		Meervoud:               "natuurlijkpersoon_naam_data",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Naam_Data{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Naam_Data{} },
		Tabelnaam:              "natuurlijkpersoon_naam_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Naam_Data{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Naam_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon_Naam",
	}
	MetaRegistry["NatuurlijkPersoon_Burgerschap_Data"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon_Burgerschap_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van NatuurlijkPersoon_Burgerschap.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_burgerschap_data",
		Padnaam:                "natuurlijkpersoon_burgerschap_data",
		Meervoud:               "natuurlijkpersoon_burgerschap_data",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Burgerschap_Data{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Burgerschap_Data{} },
		Tabelnaam:              "natuurlijkpersoon_burgerschap_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Burgerschap_Data{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Burgerschap_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon_Burgerschap",
	}
	MetaRegistry["NatuurlijkPersoon_Partnernaam_Data"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon_Partnernaam_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van NatuurlijkPersoon_Partnernaam.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_partnernaam_data",
		Padnaam:                "natuurlijkpersoon_partnernaam_data",
		Meervoud:               "natuurlijkpersoon_partnernaam_data",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Partnernaam_Data{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Partnernaam_Data{} },
		Tabelnaam:              "natuurlijkpersoon_partnernaam_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Partnernaam_Data{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Partnernaam_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon_Partnernaam",
	}
	MetaRegistry["NatuurlijkPersoon_Naamgebruik_Data"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon_Naamgebruik_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van NatuurlijkPersoon_Naamgebruik.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_naamgebruik_data",
		Padnaam:                "natuurlijkpersoon_naamgebruik_data",
		Meervoud:               "natuurlijkpersoon_naamgebruik_data",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Naamgebruik_Data{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Naamgebruik_Data{} },
		Tabelnaam:              "natuurlijkpersoon_naamgebruik_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Naamgebruik_Data{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Naamgebruik_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon_Naamgebruik",
	}
	MetaRegistry["Bereikbaarheid_Data"] = TypeMeta{
		Typenaam:               "Bereikbaarheid_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Bereikbaarheid.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "bereikbaarheid_data",
		Padnaam:                "bereikbaarheid_data",
		Meervoud:               "bereikbaarheid_data",
		Factory:                func() Representatie { return &Bereikbaarheid_Data{} },
		SliceFactory:           func() any { return &[]Bereikbaarheid_Data{} },
		Tabelnaam:              "bereikbaarheid_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Bereikbaarheid_Data{} },
		DBSliceFactory:         func() any { return &[]Bereikbaarheid_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Bereikbaarheid",
	}
	MetaRegistry["NatuurlijkPersoon_Aanvang"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van NatuurlijkPersoon.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_aanvang",
		Padnaam:                "natuurlijkpersoon_aanvang",
		Meervoud:               "natuurlijkpersoon_aanvang",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Aanvang{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Aanvang{} },
		Tabelnaam:              "natuurlijkpersoon_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Aanvang{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon",
	}
	MetaRegistry["NatuurlijkPersoon_Einde"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van NatuurlijkPersoon.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_einde",
		Padnaam:                "natuurlijkpersoon_einde",
		Meervoud:               "natuurlijkpersoon_einde",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Einde{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Einde{} },
		Tabelnaam:              "natuurlijkpersoon_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Einde{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon",
	}
	MetaRegistry["NatuurlijkPersoon_Burgerschap_Aanvang"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon_Burgerschap_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van NatuurlijkPersoon_Burgerschap.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_burgerschap_aanvang",
		Padnaam:                "natuurlijkpersoon_burgerschap_aanvang",
		Meervoud:               "natuurlijkpersoon_burgerschap_aanvang",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Burgerschap_Aanvang{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Burgerschap_Aanvang{} },
		Tabelnaam:              "natuurlijkpersoon_burgerschap_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Burgerschap_Aanvang{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Burgerschap_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon_Burgerschap",
	}
	MetaRegistry["NatuurlijkPersoon_Burgerschap_Einde"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon_Burgerschap_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van NatuurlijkPersoon_Burgerschap.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_burgerschap_einde",
		Padnaam:                "natuurlijkpersoon_burgerschap_einde",
		Meervoud:               "natuurlijkpersoon_burgerschap_einde",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Burgerschap_Einde{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Burgerschap_Einde{} },
		Tabelnaam:              "natuurlijkpersoon_burgerschap_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Burgerschap_Einde{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Burgerschap_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon_Burgerschap",
	}
	MetaRegistry["Bereikbaarheid_Aanvang"] = TypeMeta{
		Typenaam:               "Bereikbaarheid_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Bereikbaarheid.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "bereikbaarheid_aanvang",
		Padnaam:                "bereikbaarheid_aanvang",
		Meervoud:               "bereikbaarheid_aanvang",
		Factory:                func() Representatie { return &Bereikbaarheid_Aanvang{} },
		SliceFactory:           func() any { return &[]Bereikbaarheid_Aanvang{} },
		Tabelnaam:              "bereikbaarheid_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Bereikbaarheid_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Bereikbaarheid_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Bereikbaarheid",
	}
	MetaRegistry["Bereikbaarheid_Einde"] = TypeMeta{
		Typenaam:               "Bereikbaarheid_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Bereikbaarheid.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "bereikbaarheid_einde",
		Padnaam:                "bereikbaarheid_einde",
		Meervoud:               "bereikbaarheid_einde",
		Factory:                func() Representatie { return &Bereikbaarheid_Einde{} },
		SliceFactory:           func() any { return &[]Bereikbaarheid_Einde{} },
		Tabelnaam:              "bereikbaarheid_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Bereikbaarheid_Einde{} },
		DBSliceFactory:         func() any { return &[]Bereikbaarheid_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Bereikbaarheid",
	}
	MetaRegistry["Locatie"] = TypeMeta{
		Typenaam:               "Locatie",
		Klassenaam:             "Locatie",
		Description:            "Entiteit B met materiële tijdlijn en onderliggende representaties X en Y.",
		Metatype:               MetatypeEntiteit,
		IsMaterieel:            true,
		Kleur:                  "#fecaca",
		Veldnaam:               "locatie",
		Padnaam:                "locaties",
		Meervoud:               "locaties",
		Factory:                func() Representatie { return &Locatie{} },
		SliceFactory:           func() any { return &[]Locatie{} },
		Tabelnaam:              "locatie",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &Locatie{} },
		DBSliceFactory:         func() any { return &[]Locatie{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Adressen", JSONRolnaam: "adressen", Doeltype: "Locatie_Adres", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Baglocaties", JSONRolnaam: "baglocaties", Doeltype: "Locatie_BAGlocatie", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Locatie_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Locatie_Einde", Momentvoorkomen: Enkelvoudig},
		},
		AfgeleideVelden: []AfgeleidVeld{
			{
				Naam:                "weergaveadres",
				Description:         "Samengesteld weergaveadres, afgeleid uit straatnaam, huisnummer, postcode en plaats.",
				GoType:              "string",
				AfleidingsregelTaal: "cel",
				Afleidingsregel:     "Adres.straatnaam + ' ' + Adres.huisnummer + ', ' + Adres.postcode + ' ' + Adres.plaats",
				IsWeergaveVeld:      true,
			},
		},
	}
	MetaRegistry["Locatie_Adres"] = TypeMeta{
		Typenaam:               "Locatie_Adres",
		Klassenaam:             "Adres",
		Description:            "Enkelvoudig gegevenselement van B met twee tekstvelden.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Locatie_Adres_Data",
		Kleur:                  "#fecaca",
		Veldnaam:               "adres",
		Padnaam:                "adressen",
		Meervoud:               "adressen",
		Factory:                func() Representatie { return &Locatie_Adres_Input{} },
		Tabelnaam:              "locatie_adres",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Locatie_Adres{} },
		DBSliceFactory:         func() any { return &[]Locatie_Adres{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "locatie_id",
		Momentvoorkomen:        Enkelvoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Locatie_Adres_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Locatie_BAGlocatie"] = TypeMeta{
		Typenaam:               "Locatie_BAGlocatie",
		Klassenaam:             "BAGlocatie",
		Description:            "Enkelvoudig gegevenselement van B met een tekstveld.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Locatie_BAGlocatie_Data",
		Kleur:                  "#fecaca",
		Veldnaam:               "baglocatie",
		Padnaam:                "baglocaties",
		Meervoud:               "baglocaties",
		Factory:                func() Representatie { return &Locatie_BAGlocatie_Input{} },
		Tabelnaam:              "locatie_baglocatie",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Locatie_BAGlocatie{} },
		DBSliceFactory:         func() any { return &[]Locatie_BAGlocatie{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "locatie_id",
		Momentvoorkomen:        Enkelvoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Locatie_BAGlocatie_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Locatie_Adres_Data"] = TypeMeta{
		Typenaam:               "Locatie_Adres_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Locatie_Adres.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fecaca",
		Veldnaam:               "locatie_adres_data",
		Padnaam:                "locatie_adres_data",
		Meervoud:               "locatie_adres_data",
		Factory:                func() Representatie { return &Locatie_Adres_Data{} },
		SliceFactory:           func() any { return &[]Locatie_Adres_Data{} },
		Tabelnaam:              "locatie_adres_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Locatie_Adres_Data{} },
		DBSliceFactory:         func() any { return &[]Locatie_Adres_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "locatie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Locatie_Adres",
	}
	MetaRegistry["Locatie_BAGlocatie_Data"] = TypeMeta{
		Typenaam:               "Locatie_BAGlocatie_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Locatie_BAGlocatie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fecaca",
		Veldnaam:               "locatie_baglocatie_data",
		Padnaam:                "locatie_baglocatie_data",
		Meervoud:               "locatie_baglocatie_data",
		Factory:                func() Representatie { return &Locatie_BAGlocatie_Data{} },
		SliceFactory:           func() any { return &[]Locatie_BAGlocatie_Data{} },
		Tabelnaam:              "locatie_baglocatie_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Locatie_BAGlocatie_Data{} },
		DBSliceFactory:         func() any { return &[]Locatie_BAGlocatie_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "locatie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Locatie_BAGlocatie",
	}
	MetaRegistry["Locatie_Aanvang"] = TypeMeta{
		Typenaam:               "Locatie_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Locatie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#fecaca",
		Veldnaam:               "locatie_aanvang",
		Padnaam:                "locatie_aanvang",
		Meervoud:               "locatie_aanvang",
		Factory:                func() Representatie { return &Locatie_Aanvang{} },
		SliceFactory:           func() any { return &[]Locatie_Aanvang{} },
		Tabelnaam:              "locatie_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Locatie_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Locatie_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "locatie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Locatie",
	}
	MetaRegistry["Locatie_Einde"] = TypeMeta{
		Typenaam:               "Locatie_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Locatie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#fecaca",
		Veldnaam:               "locatie_einde",
		Padnaam:                "locatie_einde",
		Meervoud:               "locatie_einde",
		Factory:                func() Representatie { return &Locatie_Einde{} },
		SliceFactory:           func() any { return &[]Locatie_Einde{} },
		Tabelnaam:              "locatie_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Locatie_Einde{} },
		DBSliceFactory:         func() any { return &[]Locatie_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "locatie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Locatie",
	}

	// ====================================================================
	// REFERENTIELIJSTEN — generiek model met instanties
	// ====================================================================
	MetaRegistry["Referentielijst"] = TypeMeta{
		Typenaam:        "Referentielijst",
		Klassenaam:      "Referentielijst",
		Description:     "Generieke referentielijst-entiteit. Individuele lijsten (Landenlijst, EULidstaten, etc.) zijn records.",
		Metatype:        MetatypeEntiteit,
		EntiteitSubtype: EntiteitSubtypeReferentielijst,
		IsMaterieel:     true,
		Kleur:           "#fef3c7",
		Veldnaam:        "referentielijst",
		Padnaam:         "referentielijsten",
		Meervoud:        "referentielijsten",
		Factory:         func() Representatie { return &Referentielijst{} },
		SliceFactory:    func() any { return &[]Referentielijst{} },
		Tabelnaam:       "register_referentielijst",
		IDKolom:         "id",
		DBFactory:       func() Representatie { return &Referentielijst{} },
		DBSliceFactory:  func() any { return &[]Referentielijst{} },
		HeeftPFK:        false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Referentielijstnamen", JSONRolnaam: "referentielijstnamen", Doeltype: "Referentielijstnaam", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Referentielijstomschrijvingen", JSONRolnaam: "referentielijstomschrijvingen", Doeltype: "Referentielijstomschrijving", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "LandenlijstLanden", JSONRolnaam: "landenlijst_landen", Doeltype: "LandenlijstLand", Momentvoorkomen: Meervoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Referentielijst_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Referentielijst_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Referentielijstnaam"] = TypeMeta{
		Typenaam:               "Referentielijstnaam",
		Klassenaam:             "Referentielijstnaam",
		Description:            "Leesbare naam van een referentielijst.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Referentielijstnaam_Data",
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstnaam",
		Padnaam:                "referentielijstnamen",
		Meervoud:               "referentielijstnamen",
		Factory:                func() Representatie { return &Referentielijstnaam{} },
		Tabelnaam:              "referentielijstnaam",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Referentielijstnaam{} },
		DBSliceFactory:         func() any { return &[]Referentielijstnaam{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijst",
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Referentielijstnaam_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Referentielijstnaam_Data"] = TypeMeta{
		Typenaam:               "Referentielijstnaam_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Referentielijstnaam.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstnaam_data",
		Padnaam:                "referentielijstnaam_data",
		Meervoud:               "referentielijstnaam_data",
		Factory:                func() Representatie { return &Referentielijstnaam_Data{} },
		SliceFactory:           func() any { return &[]Referentielijstnaam_Data{} },
		Tabelnaam:              "referentielijstnaam_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Referentielijstnaam_Data{} },
		DBSliceFactory:         func() any { return &[]Referentielijstnaam_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijstnaam",
	}
	MetaRegistry["Referentielijstomschrijving"] = TypeMeta{
		Typenaam:               "Referentielijstomschrijving",
		Klassenaam:             "Referentielijstomschrijving",
		Description:            "Omschrijving van een referentielijst.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Referentielijstomschrijving_Data",
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstomschrijving",
		Padnaam:                "referentielijstomschrijvingen",
		Meervoud:               "referentielijstomschrijvingen",
		Factory:                func() Representatie { return &Referentielijstomschrijving{} },
		Tabelnaam:              "referentielijstomschrijving",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Referentielijstomschrijving{} },
		DBSliceFactory:         func() any { return &[]Referentielijstomschrijving{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijst",
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Referentielijstomschrijving_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Referentielijstomschrijving_Data"] = TypeMeta{
		Typenaam:               "Referentielijstomschrijving_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Referentielijstomschrijving.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstomschrijving_data",
		Padnaam:                "referentielijstomschrijving_data",
		Meervoud:               "referentielijstomschrijving_data",
		Factory:                func() Representatie { return &Referentielijstomschrijving_Data{} },
		SliceFactory:           func() any { return &[]Referentielijstomschrijving_Data{} },
		Tabelnaam:              "referentielijstomschrijving_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Referentielijstomschrijving_Data{} },
		DBSliceFactory:         func() any { return &[]Referentielijstomschrijving_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijstomschrijving",
	}
	MetaRegistry["Land"] = TypeMeta{
		Typenaam:        "Land",
		Klassenaam:      "Land",
		Description:     "Referentielijst-item: individueel land.",
		Metatype:        MetatypeEntiteit,
		EntiteitSubtype: EntiteitSubtypeReferentielijstItem,
		IsMaterieel:     true,
		Kleur:           "#fde68a",
		Veldnaam:        "land",
		Padnaam:         "landen",
		Meervoud:        "landen",
		Factory:         func() Representatie { return &Land{} },
		SliceFactory:    func() any { return &[]Land{} },
		Tabelnaam:       "land",
		IDKolom:         "id",
		DBFactory:       func() Representatie { return &Land{} },
		DBSliceFactory:  func() any { return &[]Land{} },
		HeeftPFK:        false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Landcodes", JSONRolnaam: "landcodes", Doeltype: "Landcode", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Landnamen", JSONRolnaam: "landnamen", Doeltype: "Landnaam", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Land_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Land_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["LandenlijstLand"] = TypeMeta{
		Typenaam:                  "LandenlijstLand",
		Klassenaam:                "LandenlijstLand",
		Description:               "Koppeling van een land aan referentielijst-instantie Landenlijst (referentielijst-items relatie).",
		Metatype:                  MetatypeRelatie,
		RelatieSubtype:            RelatieSubtypeReferentielijstItems,
		ReferentielijstInstantie:  "Landenlijst",
		IsMaterieel:               false,
		GESubtype:                 GESubtypeHub,
		DataTypenaam:              "LandenlijstLand_Data",
		Kleur:                     "#fcd34d",
		Veldnaam:                  "landenlijst_land",
		Padnaam:                   "landenlijst_landen",
		Meervoud:                  "landenlijst_landen",
		Factory:                   func() Representatie { return &LandenlijstLand_Input{} },
		Tabelnaam:                 "landenlijst_land",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &LandenlijstLand{} },
		DBSliceFactory:            func() any { return &[]LandenlijstLand{} },
		HeeftPFK:                  true,
		EntiteitIDKolom:           "referentielijst_id",
		RelatieveAutoincrement:    true,
		SecondaireEntiteitIDKolom: "land_id",
		Momentvoorkomen:           Meervoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "LandenlijstLand_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Landcode"] = TypeMeta{
		Typenaam:               "Landcode",
		Klassenaam:             "Landcode",
		Description:            "Enkelvoudig gegevenselement landcode van Land.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Landcode_Data",
		Kleur:                  "#fde68a",
		Veldnaam:               "landcode",
		Padnaam:                "landcodes",
		Meervoud:               "landcodes",
		Factory:                func() Representatie { return &Landcode_Input{} },
		Tabelnaam:              "landcode",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Landcode{} },
		DBSliceFactory:         func() any { return &[]Landcode{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "land_id",
		Momentvoorkomen:        Enkelvoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Landcode_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Landnaam"] = TypeMeta{
		Typenaam:               "Landnaam",
		Klassenaam:             "Landnaam",
		Description:            "Enkelvoudig gegevenselement landnaam van Land.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Landnaam_Data",
		Kleur:                  "#fde68a",
		Veldnaam:               "landnaam",
		Padnaam:                "landnamen",
		Meervoud:               "landnamen",
		Factory:                func() Representatie { return &Landnaam_Input{} },
		Tabelnaam:              "landnaam",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Landnaam{} },
		DBSliceFactory:         func() any { return &[]Landnaam{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "land_id",
		Momentvoorkomen:        Enkelvoudig,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Landnaam_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Landcode_Data"] = TypeMeta{
		Typenaam:               "Landcode_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van gegevenselement Landcode.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fde68a",
		Veldnaam:               "landcode_data",
		Padnaam:                "landcode_data",
		Meervoud:               "landcode_data",
		Factory:                func() Representatie { return &Landcode_Data{} },
		SliceFactory:           func() any { return &[]Landcode_Data{} },
		Tabelnaam:              "landcode_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Landcode_Data{} },
		DBSliceFactory:         func() any { return &[]Landcode_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "land_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Landcode",
	}
	MetaRegistry["Landnaam_Data"] = TypeMeta{
		Typenaam:               "Landnaam_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van gegevenselement Landnaam.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fde68a",
		Veldnaam:               "landnaam_data",
		Padnaam:                "landnaam_data",
		Meervoud:               "landnaam_data",
		Factory:                func() Representatie { return &Landnaam_Data{} },
		SliceFactory:           func() any { return &[]Landnaam_Data{} },
		Tabelnaam:              "landnaam_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Landnaam_Data{} },
		DBSliceFactory:         func() any { return &[]Landnaam_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "land_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Landnaam",
	}
	MetaRegistry["LandenlijstLand_Data"] = TypeMeta{
		Typenaam:               "LandenlijstLand_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van relatie LandenlijstLand.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fcd34d",
		Veldnaam:               "landenlijst_land_data",
		Padnaam:                "landenlijst_land_data",
		Meervoud:               "landenlijst_land_data",
		Factory:                func() Representatie { return &LandenlijstLand_Data{} },
		SliceFactory:           func() any { return &[]LandenlijstLand_Data{} },
		Tabelnaam:              "landenlijst_land_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &LandenlijstLand_Data{} },
		DBSliceFactory:         func() any { return &[]LandenlijstLand_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "LandenlijstLand",
	}
	MetaRegistry["Referentielijst_Aanvang"] = TypeMeta{
		Typenaam:               "Referentielijst_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van referentielijst.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijst_aanvang",
		Padnaam:                "referentielijst_aanvang",
		Meervoud:               "referentielijst_aanvang",
		Factory:                func() Representatie { return &Referentielijst_Aanvang{} },
		SliceFactory:           func() any { return &[]Referentielijst_Aanvang{} },
		Tabelnaam:              "referentielijst_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Referentielijst_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Referentielijst_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijst",
	}
	MetaRegistry["Referentielijst_Einde"] = TypeMeta{
		Typenaam:               "Referentielijst_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van referentielijst.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijst_einde",
		Padnaam:                "referentielijst_einde",
		Meervoud:               "referentielijst_einde",
		Factory:                func() Representatie { return &Referentielijst_Einde{} },
		SliceFactory:           func() any { return &[]Referentielijst_Einde{} },
		Tabelnaam:              "referentielijst_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Referentielijst_Einde{} },
		DBSliceFactory:         func() any { return &[]Referentielijst_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijst",
	}
	MetaRegistry["Land_Aanvang"] = TypeMeta{
		Typenaam:               "Land_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van referentielijst-item Land.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#fde68a",
		Veldnaam:               "land_aanvang",
		Padnaam:                "land_aanvang",
		Meervoud:               "land_aanvang",
		Factory:                func() Representatie { return &Land_Aanvang{} },
		SliceFactory:           func() any { return &[]Land_Aanvang{} },
		Tabelnaam:              "land_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Land_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Land_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "land_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Land",
	}
	MetaRegistry["Land_Einde"] = TypeMeta{
		Typenaam:               "Land_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van referentielijst-item Land.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#fde68a",
		Veldnaam:               "land_einde",
		Padnaam:                "land_einde",
		Meervoud:               "land_einde",
		Factory:                func() Representatie { return &Land_Einde{} },
		SliceFactory:           func() any { return &[]Land_Einde{} },
		Tabelnaam:              "land_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Land_Einde{} },
		DBSliceFactory:         func() any { return &[]Land_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "land_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Land",
	}
}
