package model

// Additieve MetaRegistry-entries — voegt types toe aan de bestaande MetaRegistry.
// Gegenereerd door cmd/codegen — niet handmatig bewerken.

func initNpLocMetaRegistry() {
	MetaRegistry["AdellijkeTitel"] = TypeMeta{
		Typenaam:               "AdellijkeTitel",
		Klassenaam:             "AdellijkeTitel",
		Description:            "Referentielijst-item: adellijke titel.",
		Metatype:               MetatypeEntiteit,
		EntiteitSubtype:        EntiteitSubtypeReferentielijstItem,
		IsMaterieel:            false,
		Domein:                 "np-loc",
		Kleur:                  "#c4b5fd",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 1665, Y: -120}},
		Veldnaam:               "adellijketitel",
		Padnaam:                "adellijke_titels",
		Meervoud:               "adellijke titels",
		Factory:                func() Representatie { return &AdellijkeTitel{} },
		SliceFactory:           func() any { return &[]AdellijkeTitel{} },
		Tabelnaam:              "adellijketitel",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &AdellijkeTitel{} },
		DBSliceFactory:         func() any { return &[]AdellijkeTitel{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "AdellijkeTitelTitels", JSONRolnaam: "adellijke_titel_titels", Doeltype: "AdellijkeTitelTitel", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["AdellijkeTitelTitel"] = TypeMeta{
		Typenaam:               "AdellijkeTitelTitel",
		Klassenaam:             "AdellijkeTitelTitel",
		Description:            "Enkelvoudig gegevenselement titel van AdellijkeTitel.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "np-loc",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "AdellijkeTitelTitel_Data",
		Kleur:                  "#c4b5fd",
		Veldnaam:               "adellijketiteltitel",
		Padnaam:                "adellijke_titel_titels",
		Meervoud:               "adellijke_titel_titels",
		Factory:                func() Representatie { return &AdellijkeTitelTitel_Input{} },
		Tabelnaam:              "adellijketiteltitel",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &AdellijkeTitelTitel{} },
		DBSliceFactory:         func() any { return &[]AdellijkeTitelTitel{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "adellijketitel_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 1665, Y: 75}, EdgeID: "AdellijkeTitel->AdellijkeTitel_AdellijkeTitelTitel",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "AdellijkeTitelTitel_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["AdellijkeTitelTitel_Data"] = TypeMeta{
		Typenaam:               "AdellijkeTitelTitel_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van AdellijkeTitelTitel.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#c4b5fd",
		Veldnaam:               "adellijketiteltitel_data",
		Padnaam:                "adellijketiteltitel_data",
		Meervoud:               "adellijketiteltitel_data",
		Factory:                func() Representatie { return &AdellijkeTitelTitel_Data{} },
		SliceFactory:           func() any { return &[]AdellijkeTitelTitel_Data{} },
		Tabelnaam:              "adellijketiteltitel_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &AdellijkeTitelTitel_Data{} },
		DBSliceFactory:         func() any { return &[]AdellijkeTitelTitel_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "adellijketitel_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "AdellijkeTitelTitel",
	}
	MetaRegistry["Locatie"] = TypeMeta{
		Typenaam:               "Locatie",
		Klassenaam:             "Locatie",
		Description:            "Fysiek bezoekbare locatie gelegen op het aardoppervlak.",
		Metatype:               MetatypeEntiteit,
		IsMaterieel:            true,
		Domein:                 "np-loc",
		Kleur:                  "#fecaca",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 600, Y: -885}},
		Veldnaam:               "locatie",
		Padnaam:                "locaties",
		Meervoud:               "locaties",
		Factory:                func() Representatie { return &Locatie{} },
		SliceFactory:           func() any { return &[]Locatie{} },
		Tabelnaam:              "locatie",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &Locatie{} },
		DBSliceFactory:         func() any { return &[]Locatie{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Adressen", JSONRolnaam: "adressen", Doeltype: "Locatie_Adres", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Baglocaties", JSONRolnaam: "baglocaties", Doeltype: "Locatie_BAGlocatie", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Locatie_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Locatie_Einde", Momentvoorkomen: Enkelvoudig},
		},
		AfgeleideVelden: []AfgeleidVeld{
			{
				Naam:                "weergaveadres",
				Description:         "Samengesteld weergaveadres, afgeleid uit straatnaam, huisnummer, postcode en plaats.",
				GoType:              "string",
				AfleidingsregelTaal: "cel",
				Afleidingsregel:     "Adres.straatnaam + ' ' + Adres.huisnummer + ', ' + Adres.postcode + ' ' + Adres.plaats",
				IsWeergaveVeld:      true,
			},
		},
	}
	MetaRegistry["Locatie_Adres"] = TypeMeta{
		Typenaam:               "Locatie_Adres",
		Klassenaam:             "Adres",
		Description:            "Binnenlands adres: een aanduiding van een binnenlandse locatie, uitgegeven door de gemeente en geregistreerd in de BAG.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "np-loc",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Locatie_Adres_Data",
		Kleur:                  "#fecaca",
		Veldnaam:               "adres",
		Padnaam:                "adressen",
		Meervoud:               "adressen",
		Factory:                func() Representatie { return &Locatie_Adres_Input{} },
		Tabelnaam:              "locatie_adres",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Locatie_Adres{} },
		DBSliceFactory:         func() any { return &[]Locatie_Adres{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "locatie_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 765, Y: -570}, EdgeID: "Locatie->Locatie_Adres",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Locatie_Adres_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Locatie_BAGlocatie"] = TypeMeta{
		Typenaam:               "Locatie_BAGlocatie",
		Klassenaam:             "BAGlocatie",
		Description:            "Unieke identificatie van het adresseerbaar object (verblijfsobject, stand- of ligplaats) uitgegeven door het bevoegd gemeentelijke orgaan.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "np-loc",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Locatie_BAGlocatie_Data",
		Kleur:                  "#fecaca",
		Veldnaam:               "baglocatie",
		Padnaam:                "baglocaties",
		Meervoud:               "baglocaties",
		Factory:                func() Representatie { return &Locatie_BAGlocatie_Input{} },
		Tabelnaam:              "locatie_baglocatie",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Locatie_BAGlocatie{} },
		DBSliceFactory:         func() any { return &[]Locatie_BAGlocatie{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "locatie_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 510, Y: -555}, EdgeID: "Locatie->Locatie_BAG-locatie",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Locatie_BAGlocatie_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Locatie_Adres_Data"] = TypeMeta{
		Typenaam:               "Locatie_Adres_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Locatie_Adres.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fecaca",
		Veldnaam:               "locatie_adres_data",
		Padnaam:                "locatie_adres_data",
		Meervoud:               "locatie_adres_data",
		Factory:                func() Representatie { return &Locatie_Adres_Data{} },
		SliceFactory:           func() any { return &[]Locatie_Adres_Data{} },
		Tabelnaam:              "locatie_adres_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Locatie_Adres_Data{} },
		DBSliceFactory:         func() any { return &[]Locatie_Adres_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "locatie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Locatie_Adres",
	}
	MetaRegistry["Locatie_BAGlocatie_Data"] = TypeMeta{
		Typenaam:               "Locatie_BAGlocatie_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Locatie_BAGlocatie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fecaca",
		Veldnaam:               "locatie_baglocatie_data",
		Padnaam:                "locatie_baglocatie_data",
		Meervoud:               "locatie_baglocatie_data",
		Factory:                func() Representatie { return &Locatie_BAGlocatie_Data{} },
		SliceFactory:           func() any { return &[]Locatie_BAGlocatie_Data{} },
		Tabelnaam:              "locatie_baglocatie_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Locatie_BAGlocatie_Data{} },
		DBSliceFactory:         func() any { return &[]Locatie_BAGlocatie_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "locatie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Locatie_BAGlocatie",
	}
	MetaRegistry["Locatie_Aanvang"] = TypeMeta{
		Typenaam:               "Locatie_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Locatie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#fecaca",
		Veldnaam:               "locatie_aanvang",
		Padnaam:                "locatie_aanvang",
		Meervoud:               "locatie_aanvang",
		Factory:                func() Representatie { return &Locatie_Aanvang{} },
		SliceFactory:           func() any { return &[]Locatie_Aanvang{} },
		Tabelnaam:              "locatie_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Locatie_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Locatie_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "locatie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Locatie",
	}
	MetaRegistry["Locatie_Einde"] = TypeMeta{
		Typenaam:               "Locatie_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Locatie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#fecaca",
		Veldnaam:               "locatie_einde",
		Padnaam:                "locatie_einde",
		Meervoud:               "locatie_einde",
		Factory:                func() Representatie { return &Locatie_Einde{} },
		SliceFactory:           func() any { return &[]Locatie_Einde{} },
		Tabelnaam:              "locatie_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Locatie_Einde{} },
		DBSliceFactory:         func() any { return &[]Locatie_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "locatie_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Locatie",
	}
	MetaRegistry["NatuurlijkPersoon"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon",
		Klassenaam:             "NatuurlijkPersoon",
		Description:            "Een mens voor zover deze door Nederlandse wetgeving met rechten en plichten wordt bekleed.",
		Metatype:               MetatypeEntiteit,
		IsMaterieel:            true,
		Domein:                 "np-loc",
		Kleur:                  "#bfdbfe",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: -210, Y: -885}},
		Veldnaam:               "natuurlijkpersoon",
		Padnaam:                "natuurlijk_personen",
		Meervoud:               "natuurlijk personen",
		Factory:                func() Representatie { return &NatuurlijkPersoon{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon{} },
		Tabelnaam:              "natuurlijkpersoon",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Persoonsidentificaties", JSONRolnaam: "persoonsidentificaties", Doeltype: "NatuurlijkPersoon_Persoonsidentificatie", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Namen", JSONRolnaam: "namen", Doeltype: "NatuurlijkPersoon_Naam", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Partnernamen", JSONRolnaam: "partnernamen", Doeltype: "NatuurlijkPersoon_Partnernaam", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Naamgebruiken", JSONRolnaam: "naamgebruiken", Doeltype: "NatuurlijkPersoon_Naamgebruik", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Bereikbaarheden", JSONRolnaam: "bereikbaarheden", Doeltype: "Bereikbaarheid", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "NatuurlijkPersoon_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "NatuurlijkPersoon_Einde", Momentvoorkomen: Enkelvoudig},
		},
		AfgeleideVelden: []AfgeleidVeld{
			{
				Naam:                "weergavenaam",
				Description:         "Samengestelde BRP-weergavenaam van de persoon, inclusief naamgebruik en partnernaam indien van toepassing.",
				GoType:              "string",
				AfleidingsregelTaal: "cel",
				Afleidingsregel:     "(Naam.roepnaam != null ? Naam.roepnaam : Naam.voorletters) + ' ' + (Naamgebruik.naamgebruik == 'PartnerNaam' ? (Partnernaam.achternaam != null ? Partnernaam.achternaam : ((Naam.tussenvoegsel != null ? Naam.tussenvoegsel + ' ' : '') + Naam.achternaam)) : Naamgebruik.naamgebruik == 'EigenNaam-PartnerNaam' ? ((Naam.tussenvoegsel != null ? Naam.tussenvoegsel + ' ' : '') + Naam.achternaam) + (Partnernaam.achternaam != null ? '-' + Partnernaam.achternaam : '') : Naamgebruik.naamgebruik == 'PartnerNaam-EigenNaam' ? (Partnernaam.achternaam != null ? Partnernaam.achternaam + '-' : '') + ((Naam.tussenvoegsel != null ? Naam.tussenvoegsel + ' ' : '') + Naam.achternaam) : ((Naam.tussenvoegsel != null ? Naam.tussenvoegsel + ' ' : '') + Naam.achternaam))",
				IsWeergaveVeld:      true,
			},
		},
	}
	MetaRegistry["NatuurlijkPersoon_Persoonsidentificatie"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon_Persoonsidentificatie",
		Klassenaam:             "Persoonsidentificatie",
		Description:            "Identificerende gegevens van de natuurlijk persoon (BSN, ingezetene).",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "np-loc",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "NatuurlijkPersoon_Persoonsidentificatie_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "persoonsidentificatie",
		Padnaam:                "persoonsidentificaties",
		Meervoud:               "persoonsidentificaties",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Persoonsidentificatie_Input{} },
		Tabelnaam:              "natuurlijkpersoon_persoonsidentificatie",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Persoonsidentificatie{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Persoonsidentificatie{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: -570, Y: -780}, EdgeID: "NatuurlijkPersoon->NatuurlijkPersoon_PersoonsIdentificatie",
			SourceHandle: "left",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "NatuurlijkPersoon_Persoonsidentificatie_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["NatuurlijkPersoon_Naam"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon_Naam",
		Klassenaam:             "Naam",
		Description:            "Naamgegevens van de natuurlijk persoon (voorletters, roepnaam, tussenvoegsel, achternaam).",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "np-loc",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "NatuurlijkPersoon_Naam_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "naam",
		Padnaam:                "namen",
		Meervoud:               "namen",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Naam_Input{} },
		Tabelnaam:              "natuurlijkpersoon_naam",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Naam{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Naam{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: -225, Y: -495}, EdgeID: "NatuurlijkPersoon->NatuurlijkPersoon_Naam",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "NatuurlijkPersoon_Naam_Data", Momentvoorkomen: Enkelvoudig},
		},
		AfgeleideVelden: []AfgeleidVeld{
			{
				Naam:                "weergavenaam",
				GoType:              "string",
				AfleidingsregelTaal: "cel",
				Afleidingsregel:     "(Naam.roepnaam != null ? Naam.roepnaam : Naam.voorletters) + (Naam.tussenvoegsel != null ? ' ' + Naam.tussenvoegsel : '') + ' ' + Naam.achternaam",
				IsWeergaveVeld:      true,
			},
		},
	}
	MetaRegistry["NatuurlijkPersoon_Partnernaam"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon_Partnernaam",
		Klassenaam:             "Partnernaam",
		Description:            "Achternaam van de partner van de natuurlijk persoon.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "np-loc",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "NatuurlijkPersoon_Partnernaam_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "partnernaam",
		Padnaam:                "partnernamen",
		Meervoud:               "partnernamen",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Partnernaam_Input{} },
		Tabelnaam:              "natuurlijkpersoon_partnernaam",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Partnernaam{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Partnernaam{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: -60, Y: -285}, EdgeID: "edge_1774209110136_2",
			SourceHandle: "bottom", TargetHandle: "top",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "NatuurlijkPersoon_Partnernaam_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["NatuurlijkPersoon_Naamgebruik"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon_Naamgebruik",
		Klassenaam:             "Naamgebruik",
		Description:            "Wijze waarop de geslachtsnaam wordt gebruikt.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "np-loc",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "NatuurlijkPersoon_Naamgebruik_Data",
		Kleur:                  "#bfdbfe",
		Veldnaam:               "naamgebruik",
		Padnaam:                "naamgebruiken",
		Meervoud:               "naamgebruiken",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Naamgebruik_Input{} },
		Tabelnaam:              "natuurlijkpersoon_naamgebruik",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Naamgebruik{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Naamgebruik{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 75, Y: -495}, EdgeID: "edge_1774209240752_5",
			SourceHandle: "bottom", TargetHandle: "top",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "NatuurlijkPersoon_Naamgebruik_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Bereikbaarheid"] = TypeMeta{
		Typenaam:                  "Bereikbaarheid",
		Klassenaam:                "Bereikbaarheid",
		Description:               "Koppeling van een natuurlijk persoon aan een locatie als bereikbaarheidsadres.",
		Metatype:                  MetatypeRelatie,
		IsMaterieel:               true,
		Domein:                    "np-loc",
		GESubtype:                 GESubtypeHub,
		DataTypenaam:              "Bereikbaarheid_Data",
		Kleur:                     "",
		Veldnaam:                  "bereikbaarheid",
		Padnaam:                   "bereikbaarheden",
		Meervoud:                  "bereikbaarheden",
		Factory:                   func() Representatie { return &Bereikbaarheid_Input{} },
		Tabelnaam:                 "bereikbaarheid",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &Bereikbaarheid{} },
		DBSliceFactory:            func() any { return &[]Bereikbaarheid{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "natuurlijkpersoon_id",
		SecondaireEntiteitIDKolom: "locatie_id",
		Momentvoorkomen:           Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 210, Y: -870}, EdgeID: "edge_1774201942583_1",
			SourceHandle: "right", TargetHandle: "left",
			DoelEdgeID: "edge_1774201991984_2", DoelSourceHandle: "right", DoelTargetHandle: "left",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Bereikbaarheid_Data", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Bereikbaarheid_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Bereikbaarheid_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["NatuurlijkPersoon_Persoonsidentificatie_Data"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon_Persoonsidentificatie_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van NatuurlijkPersoon_Persoonsidentificatie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_persoonsidentificatie_data",
		Padnaam:                "natuurlijkpersoon_persoonsidentificatie_data",
		Meervoud:               "natuurlijkpersoon_persoonsidentificatie_data",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Persoonsidentificatie_Data{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Persoonsidentificatie_Data{} },
		Tabelnaam:              "natuurlijkpersoon_persoonsidentificatie_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Persoonsidentificatie_Data{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Persoonsidentificatie_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon_Persoonsidentificatie",
	}
	MetaRegistry["NatuurlijkPersoon_Naam_Data"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon_Naam_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van NatuurlijkPersoon_Naam.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_naam_data",
		Padnaam:                "natuurlijkpersoon_naam_data",
		Meervoud:               "natuurlijkpersoon_naam_data",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Naam_Data{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Naam_Data{} },
		Tabelnaam:              "natuurlijkpersoon_naam_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Naam_Data{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Naam_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon_Naam",
	}
	MetaRegistry["NatuurlijkPersoon_Partnernaam_Data"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon_Partnernaam_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van NatuurlijkPersoon_Partnernaam.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_partnernaam_data",
		Padnaam:                "natuurlijkpersoon_partnernaam_data",
		Meervoud:               "natuurlijkpersoon_partnernaam_data",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Partnernaam_Data{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Partnernaam_Data{} },
		Tabelnaam:              "natuurlijkpersoon_partnernaam_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Partnernaam_Data{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Partnernaam_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon_Partnernaam",
	}
	MetaRegistry["NatuurlijkPersoon_Naamgebruik_Data"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon_Naamgebruik_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van NatuurlijkPersoon_Naamgebruik.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_naamgebruik_data",
		Padnaam:                "natuurlijkpersoon_naamgebruik_data",
		Meervoud:               "natuurlijkpersoon_naamgebruik_data",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Naamgebruik_Data{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Naamgebruik_Data{} },
		Tabelnaam:              "natuurlijkpersoon_naamgebruik_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Naamgebruik_Data{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Naamgebruik_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon_Naamgebruik",
	}
	MetaRegistry["Bereikbaarheid_Data"] = TypeMeta{
		Typenaam:               "Bereikbaarheid_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Bereikbaarheid.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "bereikbaarheid_data",
		Padnaam:                "bereikbaarheid_data",
		Meervoud:               "bereikbaarheid_data",
		Factory:                func() Representatie { return &Bereikbaarheid_Data{} },
		SliceFactory:           func() any { return &[]Bereikbaarheid_Data{} },
		Tabelnaam:              "bereikbaarheid_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Bereikbaarheid_Data{} },
		DBSliceFactory:         func() any { return &[]Bereikbaarheid_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Bereikbaarheid",
	}
	MetaRegistry["NatuurlijkPersoon_Aanvang"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van NatuurlijkPersoon.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_aanvang",
		Padnaam:                "natuurlijkpersoon_aanvang",
		Meervoud:               "natuurlijkpersoon_aanvang",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Aanvang{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Aanvang{} },
		Tabelnaam:              "natuurlijkpersoon_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Aanvang{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon",
	}
	MetaRegistry["NatuurlijkPersoon_Einde"] = TypeMeta{
		Typenaam:               "NatuurlijkPersoon_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van NatuurlijkPersoon.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "natuurlijkpersoon_einde",
		Padnaam:                "natuurlijkpersoon_einde",
		Meervoud:               "natuurlijkpersoon_einde",
		Factory:                func() Representatie { return &NatuurlijkPersoon_Einde{} },
		SliceFactory:           func() any { return &[]NatuurlijkPersoon_Einde{} },
		Tabelnaam:              "natuurlijkpersoon_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &NatuurlijkPersoon_Einde{} },
		DBSliceFactory:         func() any { return &[]NatuurlijkPersoon_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "NatuurlijkPersoon",
	}
	MetaRegistry["Bereikbaarheid_Aanvang"] = TypeMeta{
		Typenaam:               "Bereikbaarheid_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Bereikbaarheid.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "bereikbaarheid_aanvang",
		Padnaam:                "bereikbaarheid_aanvang",
		Meervoud:               "bereikbaarheid_aanvang",
		Factory:                func() Representatie { return &Bereikbaarheid_Aanvang{} },
		SliceFactory:           func() any { return &[]Bereikbaarheid_Aanvang{} },
		Tabelnaam:              "bereikbaarheid_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Bereikbaarheid_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Bereikbaarheid_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Bereikbaarheid",
	}
	MetaRegistry["Bereikbaarheid_Einde"] = TypeMeta{
		Typenaam:               "Bereikbaarheid_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Bereikbaarheid.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bfdbfe",
		Veldnaam:               "bereikbaarheid_einde",
		Padnaam:                "bereikbaarheid_einde",
		Meervoud:               "bereikbaarheid_einde",
		Factory:                func() Representatie { return &Bereikbaarheid_Einde{} },
		SliceFactory:           func() any { return &[]Bereikbaarheid_Einde{} },
		Tabelnaam:              "bereikbaarheid_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Bereikbaarheid_Einde{} },
		DBSliceFactory:         func() any { return &[]Bereikbaarheid_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "natuurlijkpersoon_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Bereikbaarheid",
	}
}
