package model

// Additieve MetaRegistry-entries — voegt types toe aan de bestaande MetaRegistry.
// Gegenereerd door cmd/codegen — niet handmatig bewerken.

func initOrgGeoMetaRegistry() {
	MetaRegistry["Afdeling"] = TypeMeta{
		Typenaam:               "Afdeling",
		Klassenaam:             "Afdeling",
		Description:            "Organisatorische eenheid binnen een organisatie. Demo-model: dient als tweede register naast NatuurlijkPersoon.",
		Metatype:               MetatypeEntiteit,
		IsMaterieel:            true,
		Domein:                 "org-geo",
		Kleur:                  "#bbf7d0",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: -1650, Y: -1710}},
		Veldnaam:               "afdeling",
		Padnaam:                "afdelingen",
		Meervoud:               "afdelingen",
		Factory:                func() Representatie { return &Afdeling{} },
		SliceFactory:           func() any { return &[]Afdeling{} },
		Tabelnaam:              "afdeling",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &Afdeling{} },
		DBSliceFactory:         func() any { return &[]Afdeling{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Afdelingsnaam", JSONRolnaam: "afdelingsnaam", Doeltype: "Afdeling_Afdelingsnaam", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Organisatie", JSONRolnaam: "organisatie", Doeltype: "Afdelingsorganisatie", Momentvoorkomen: Enkelvoudig, NaamLabelHeen: "hoort bij", NaamLabelTerug: "kent afdeling"},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Afdeling_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Afdeling_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Afdeling_Afdelingsnaam"] = TypeMeta{
		Typenaam:               "Afdeling_Afdelingsnaam",
		Klassenaam:             "Afdelingsnaam",
		Description:            "Naam van de afdeling.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "org-geo",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Afdeling_Afdelingsnaam_Data",
		Kleur:                  "#bbf7d0",
		Veldnaam:               "afdelingsnaam",
		Padnaam:                "afdelingsnaam",
		Meervoud:               "afdelingsnaam",
		Factory:                func() Representatie { return &Afdeling_Afdelingsnaam_Input{} },
		Tabelnaam:              "afdeling_afdelingsnaam",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Afdeling_Afdelingsnaam{} },
		DBSliceFactory:         func() any { return &[]Afdeling_Afdelingsnaam{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "afdeling_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout:                 &EditorLayout{Positie: &V3Positie{X: -1950, Y: -1530}},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Afdeling_Afdelingsnaam_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Afdelingsorganisatie"] = TypeMeta{
		Typenaam:                  "Afdelingsorganisatie",
		Klassenaam:                "Afdelingsorganisatie",
		Description:               "De organisatie waartoe de afdeling behoort.",
		Metatype:                  MetatypeRelatie,
		IsMaterieel:               true,
		Domein:                    "org-geo",
		GESubtype:                 GESubtypeHub,
		DataTypenaam:              "Afdelingsorganisatie_Data",
		Kleur:                     "",
		Veldnaam:                  "afdelingsorganisatie",
		Padnaam:                   "organisatie",
		Meervoud:                  "organisatie",
		Factory:                   func() Representatie { return &Afdelingsorganisatie_Input{} },
		Tabelnaam:                 "afdelingsorganisatie",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &Afdelingsorganisatie{} },
		DBSliceFactory:            func() any { return &[]Afdelingsorganisatie{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "afdeling_id",
		SecondaireEntiteitIDKolom: "organisatie_id",
		Momentvoorkomen:           Enkelvoudig,
		Directioneel:              true,
		Layout:                    &EditorLayout{Positie: &V3Positie{X: -1350, Y: -1860}},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Afdelingsorganisatie_Data", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Afdelingsorganisatie_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Afdelingsorganisatie_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Afdeling_Afdelingsnaam_Data"] = TypeMeta{
		Typenaam:               "Afdeling_Afdelingsnaam_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Afdeling_Afdelingsnaam.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bbf7d0",
		Veldnaam:               "afdeling_afdelingsnaam_data",
		Padnaam:                "afdeling_afdelingsnaam_data",
		Meervoud:               "afdeling_afdelingsnaam_data",
		Factory:                func() Representatie { return &Afdeling_Afdelingsnaam_Data{} },
		SliceFactory:           func() any { return &[]Afdeling_Afdelingsnaam_Data{} },
		Tabelnaam:              "afdeling_afdelingsnaam_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Afdeling_Afdelingsnaam_Data{} },
		DBSliceFactory:         func() any { return &[]Afdeling_Afdelingsnaam_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "afdeling_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Afdeling_Afdelingsnaam",
	}
	MetaRegistry["Afdelingsorganisatie_Data"] = TypeMeta{
		Typenaam:               "Afdelingsorganisatie_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Afdelingsorganisatie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bbf7d0",
		Veldnaam:               "afdelingsorganisatie_data",
		Padnaam:                "afdelingsorganisatie_data",
		Meervoud:               "afdelingsorganisatie_data",
		Factory:                func() Representatie { return &Afdelingsorganisatie_Data{} },
		SliceFactory:           func() any { return &[]Afdelingsorganisatie_Data{} },
		Tabelnaam:              "afdelingsorganisatie_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Afdelingsorganisatie_Data{} },
		DBSliceFactory:         func() any { return &[]Afdelingsorganisatie_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "afdeling_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Afdelingsorganisatie",
	}
	MetaRegistry["Afdeling_Aanvang"] = TypeMeta{
		Typenaam:               "Afdeling_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Afdeling.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bbf7d0",
		Veldnaam:               "afdeling_aanvang",
		Padnaam:                "afdeling_aanvang",
		Meervoud:               "afdeling_aanvang",
		Factory:                func() Representatie { return &Afdeling_Aanvang{} },
		SliceFactory:           func() any { return &[]Afdeling_Aanvang{} },
		Tabelnaam:              "afdeling_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Afdeling_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Afdeling_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "afdeling_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Afdeling",
	}
	MetaRegistry["Afdeling_Einde"] = TypeMeta{
		Typenaam:               "Afdeling_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Afdeling.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bbf7d0",
		Veldnaam:               "afdeling_einde",
		Padnaam:                "afdeling_einde",
		Meervoud:               "afdeling_einde",
		Factory:                func() Representatie { return &Afdeling_Einde{} },
		SliceFactory:           func() any { return &[]Afdeling_Einde{} },
		Tabelnaam:              "afdeling_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Afdeling_Einde{} },
		DBSliceFactory:         func() any { return &[]Afdeling_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "afdeling_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Afdeling",
	}
	MetaRegistry["Afdelingsorganisatie_Aanvang"] = TypeMeta{
		Typenaam:               "Afdelingsorganisatie_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Afdelingsorganisatie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bbf7d0",
		Veldnaam:               "afdelingsorganisatie_aanvang",
		Padnaam:                "afdelingsorganisatie_aanvang",
		Meervoud:               "afdelingsorganisatie_aanvang",
		Factory:                func() Representatie { return &Afdelingsorganisatie_Aanvang{} },
		SliceFactory:           func() any { return &[]Afdelingsorganisatie_Aanvang{} },
		Tabelnaam:              "afdelingsorganisatie_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Afdelingsorganisatie_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Afdelingsorganisatie_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "afdeling_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Afdelingsorganisatie",
	}
	MetaRegistry["Afdelingsorganisatie_Einde"] = TypeMeta{
		Typenaam:               "Afdelingsorganisatie_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Afdelingsorganisatie.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bbf7d0",
		Veldnaam:               "afdelingsorganisatie_einde",
		Padnaam:                "afdelingsorganisatie_einde",
		Meervoud:               "afdelingsorganisatie_einde",
		Factory:                func() Representatie { return &Afdelingsorganisatie_Einde{} },
		SliceFactory:           func() any { return &[]Afdelingsorganisatie_Einde{} },
		Tabelnaam:              "afdelingsorganisatie_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Afdelingsorganisatie_Einde{} },
		DBSliceFactory:         func() any { return &[]Afdelingsorganisatie_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "afdeling_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Afdelingsorganisatie",
	}
	MetaRegistry["Medewerker"] = TypeMeta{
		Typenaam:               "Medewerker",
		Klassenaam:             "Medewerker",
		Description:            "Persoon die namens een afdeling werk verricht. In het demo-beleid is de medewerker de aanvrager; rol, afdeling en kanaal komen als subject-kenmerken uit de PIP.",
		Metatype:               MetatypeEntiteit,
		IsMaterieel:            true,
		Domein:                 "org-geo",
		Kleur:                  "#bbf7d0",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: -1650, Y: -2160}},
		Veldnaam:               "medewerker",
		Padnaam:                "medewerkers",
		Meervoud:               "medewerkers",
		Factory:                func() Representatie { return &Medewerker{} },
		SliceFactory:           func() any { return &[]Medewerker{} },
		Tabelnaam:              "medewerker",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &Medewerker{} },
		DBSliceFactory:         func() any { return &[]Medewerker{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Medewerkernaam", JSONRolnaam: "medewerkernaam", Doeltype: "Medewerker_Medewerkernaam", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanstelling", JSONRolnaam: "aanstelling", Doeltype: "Medewerker_Aanstelling", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Kanalen", JSONRolnaam: "kanalen", Doeltype: "Medewerker_Contactkanaal", Momentvoorkomen: Meervoudig},
			{Rolnaam: "Afdeling", JSONRolnaam: "afdeling", Doeltype: "Medewerkerafdeling", Momentvoorkomen: Enkelvoudig, NaamLabelHeen: "werkt bij", NaamLabelTerug: "heeft medewerker"},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Medewerker_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Medewerker_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Medewerker_Medewerkernaam"] = TypeMeta{
		Typenaam:               "Medewerker_Medewerkernaam",
		Klassenaam:             "Medewerkernaam",
		Description:            "Naam van de medewerker.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "org-geo",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Medewerker_Medewerkernaam_Data",
		Kleur:                  "#bbf7d0",
		Veldnaam:               "medewerkernaam",
		Padnaam:                "medewerkernaam",
		Meervoud:               "medewerkernaam",
		Factory:                func() Representatie { return &Medewerker_Medewerkernaam_Input{} },
		Tabelnaam:              "medewerker_medewerkernaam",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Medewerker_Medewerkernaam{} },
		DBSliceFactory:         func() any { return &[]Medewerker_Medewerkernaam{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "medewerker_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout:                 &EditorLayout{Positie: &V3Positie{X: -2010, Y: -2310}},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Medewerker_Medewerkernaam_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Medewerker_Aanstelling"] = TypeMeta{
		Typenaam:               "Medewerker_Aanstelling",
		Klassenaam:             "Aanstelling",
		Description:            "Functie en rol van de medewerker.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "org-geo",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Medewerker_Aanstelling_Data",
		Kleur:                  "#bbf7d0",
		Veldnaam:               "aanstelling",
		Padnaam:                "aanstelling",
		Meervoud:               "aanstelling",
		Factory:                func() Representatie { return &Medewerker_Aanstelling_Input{} },
		Tabelnaam:              "medewerker_aanstelling",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Medewerker_Aanstelling{} },
		DBSliceFactory:         func() any { return &[]Medewerker_Aanstelling{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "medewerker_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout:                 &EditorLayout{Positie: &V3Positie{X: -1650, Y: -2385}},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Medewerker_Aanstelling_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Medewerker_Contactkanaal"] = TypeMeta{
		Typenaam:               "Medewerker_Contactkanaal",
		Klassenaam:             "Contactkanaal",
		Description:            "Kanaal waarlangs de medewerker klanten te woord staat; meervoudig, want een medewerker kan meerdere kanalen bedienen.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "org-geo",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Medewerker_Contactkanaal_Data",
		Kleur:                  "#bbf7d0",
		Veldnaam:               "contactkanaal",
		Padnaam:                "kanalen",
		Meervoud:               "kanalen",
		Factory:                func() Representatie { return &Medewerker_Contactkanaal_Input{} },
		Tabelnaam:              "medewerker_contactkanaal",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Medewerker_Contactkanaal{} },
		DBSliceFactory:         func() any { return &[]Medewerker_Contactkanaal{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "medewerker_id",
		Momentvoorkomen:        Meervoudig,
		Layout:                 &EditorLayout{Positie: &V3Positie{X: -1290, Y: -2310}},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Medewerker_Contactkanaal_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Medewerkerafdeling"] = TypeMeta{
		Typenaam:                  "Medewerkerafdeling",
		Klassenaam:                "Medewerkerafdeling",
		Description:               "De afdeling waar de medewerker werkt.",
		Metatype:                  MetatypeRelatie,
		IsMaterieel:               true,
		Domein:                    "org-geo",
		GESubtype:                 GESubtypeHub,
		DataTypenaam:              "Medewerkerafdeling_Data",
		Kleur:                     "",
		Veldnaam:                  "medewerkerafdeling",
		Padnaam:                   "afdeling",
		Meervoud:                  "afdeling",
		Factory:                   func() Representatie { return &Medewerkerafdeling_Input{} },
		Tabelnaam:                 "medewerkerafdeling",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &Medewerkerafdeling{} },
		DBSliceFactory:            func() any { return &[]Medewerkerafdeling{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "medewerker_id",
		SecondaireEntiteitIDKolom: "afdeling_id",
		Momentvoorkomen:           Enkelvoudig,
		Directioneel:              true,
		Layout:                    &EditorLayout{Positie: &V3Positie{X: -1650, Y: -1935}},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Medewerkerafdeling_Data", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Medewerkerafdeling_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Medewerkerafdeling_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Medewerker_Medewerkernaam_Data"] = TypeMeta{
		Typenaam:               "Medewerker_Medewerkernaam_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Medewerker_Medewerkernaam.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bbf7d0",
		Veldnaam:               "medewerker_medewerkernaam_data",
		Padnaam:                "medewerker_medewerkernaam_data",
		Meervoud:               "medewerker_medewerkernaam_data",
		Factory:                func() Representatie { return &Medewerker_Medewerkernaam_Data{} },
		SliceFactory:           func() any { return &[]Medewerker_Medewerkernaam_Data{} },
		Tabelnaam:              "medewerker_medewerkernaam_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Medewerker_Medewerkernaam_Data{} },
		DBSliceFactory:         func() any { return &[]Medewerker_Medewerkernaam_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "medewerker_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Medewerker_Medewerkernaam",
	}
	MetaRegistry["Medewerker_Aanstelling_Data"] = TypeMeta{
		Typenaam:               "Medewerker_Aanstelling_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Medewerker_Aanstelling.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bbf7d0",
		Veldnaam:               "medewerker_aanstelling_data",
		Padnaam:                "medewerker_aanstelling_data",
		Meervoud:               "medewerker_aanstelling_data",
		Factory:                func() Representatie { return &Medewerker_Aanstelling_Data{} },
		SliceFactory:           func() any { return &[]Medewerker_Aanstelling_Data{} },
		Tabelnaam:              "medewerker_aanstelling_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Medewerker_Aanstelling_Data{} },
		DBSliceFactory:         func() any { return &[]Medewerker_Aanstelling_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "medewerker_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Medewerker_Aanstelling",
	}
	MetaRegistry["Medewerker_Contactkanaal_Data"] = TypeMeta{
		Typenaam:               "Medewerker_Contactkanaal_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Medewerker_Contactkanaal.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bbf7d0",
		Veldnaam:               "medewerker_contactkanaal_data",
		Padnaam:                "medewerker_contactkanaal_data",
		Meervoud:               "medewerker_contactkanaal_data",
		Factory:                func() Representatie { return &Medewerker_Contactkanaal_Data{} },
		SliceFactory:           func() any { return &[]Medewerker_Contactkanaal_Data{} },
		Tabelnaam:              "medewerker_contactkanaal_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Medewerker_Contactkanaal_Data{} },
		DBSliceFactory:         func() any { return &[]Medewerker_Contactkanaal_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "medewerker_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Medewerker_Contactkanaal",
	}
	MetaRegistry["Medewerkerafdeling_Data"] = TypeMeta{
		Typenaam:               "Medewerkerafdeling_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Medewerkerafdeling.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#bbf7d0",
		Veldnaam:               "medewerkerafdeling_data",
		Padnaam:                "medewerkerafdeling_data",
		Meervoud:               "medewerkerafdeling_data",
		Factory:                func() Representatie { return &Medewerkerafdeling_Data{} },
		SliceFactory:           func() any { return &[]Medewerkerafdeling_Data{} },
		Tabelnaam:              "medewerkerafdeling_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Medewerkerafdeling_Data{} },
		DBSliceFactory:         func() any { return &[]Medewerkerafdeling_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "medewerker_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Medewerkerafdeling",
	}
	MetaRegistry["Medewerker_Aanvang"] = TypeMeta{
		Typenaam:               "Medewerker_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Medewerker.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bbf7d0",
		Veldnaam:               "medewerker_aanvang",
		Padnaam:                "medewerker_aanvang",
		Meervoud:               "medewerker_aanvang",
		Factory:                func() Representatie { return &Medewerker_Aanvang{} },
		SliceFactory:           func() any { return &[]Medewerker_Aanvang{} },
		Tabelnaam:              "medewerker_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Medewerker_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Medewerker_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "medewerker_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Medewerker",
	}
	MetaRegistry["Medewerker_Einde"] = TypeMeta{
		Typenaam:               "Medewerker_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Medewerker.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bbf7d0",
		Veldnaam:               "medewerker_einde",
		Padnaam:                "medewerker_einde",
		Meervoud:               "medewerker_einde",
		Factory:                func() Representatie { return &Medewerker_Einde{} },
		SliceFactory:           func() any { return &[]Medewerker_Einde{} },
		Tabelnaam:              "medewerker_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Medewerker_Einde{} },
		DBSliceFactory:         func() any { return &[]Medewerker_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "medewerker_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Medewerker",
	}
	MetaRegistry["Medewerkerafdeling_Aanvang"] = TypeMeta{
		Typenaam:               "Medewerkerafdeling_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Medewerkerafdeling.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#bbf7d0",
		Veldnaam:               "medewerkerafdeling_aanvang",
		Padnaam:                "medewerkerafdeling_aanvang",
		Meervoud:               "medewerkerafdeling_aanvang",
		Factory:                func() Representatie { return &Medewerkerafdeling_Aanvang{} },
		SliceFactory:           func() any { return &[]Medewerkerafdeling_Aanvang{} },
		Tabelnaam:              "medewerkerafdeling_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Medewerkerafdeling_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Medewerkerafdeling_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "medewerker_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Medewerkerafdeling",
	}
	MetaRegistry["Medewerkerafdeling_Einde"] = TypeMeta{
		Typenaam:               "Medewerkerafdeling_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Medewerkerafdeling.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#bbf7d0",
		Veldnaam:               "medewerkerafdeling_einde",
		Padnaam:                "medewerkerafdeling_einde",
		Meervoud:               "medewerkerafdeling_einde",
		Factory:                func() Representatie { return &Medewerkerafdeling_Einde{} },
		SliceFactory:           func() any { return &[]Medewerkerafdeling_Einde{} },
		Tabelnaam:              "medewerkerafdeling_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Medewerkerafdeling_Einde{} },
		DBSliceFactory:         func() any { return &[]Medewerkerafdeling_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "medewerker_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Medewerkerafdeling",
	}
	MetaRegistry["Gemeentedeel"] = TypeMeta{
		Typenaam:               "Gemeentedeel",
		Klassenaam:             "Gemeentedeel",
		Description:            "Deel van een gemeente (stadsdeel, wijk of buurt). Locaties liggen in een gemeentedeel; het demo-beleid toetst hierop.",
		Metatype:               MetatypeEntiteit,
		IsMaterieel:            true,
		Domein:                 "org-geo",
		Kleur:                  "#fbcfe8",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 900, Y: -1410}},
		Veldnaam:               "gemeentedeel",
		Padnaam:                "gemeentedelen",
		Meervoud:               "gemeentedelen",
		Factory:                func() Representatie { return &Gemeentedeel{} },
		SliceFactory:           func() any { return &[]Gemeentedeel{} },
		Tabelnaam:              "gemeentedeel",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &Gemeentedeel{} },
		DBSliceFactory:         func() any { return &[]Gemeentedeel{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Wijkaanduiding", JSONRolnaam: "wijkaanduiding", Doeltype: "Gemeentedeel_Wijkaanduiding", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Gemeente", JSONRolnaam: "gemeente", Doeltype: "Gemeentedeelgemeente", Momentvoorkomen: Enkelvoudig, NaamLabelHeen: "ligt in", NaamLabelTerug: "is ingedeeld in"},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Gemeentedeel_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Gemeentedeel_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Gemeentedeel_Wijkaanduiding"] = TypeMeta{
		Typenaam:               "Gemeentedeel_Wijkaanduiding",
		Klassenaam:             "Wijkaanduiding",
		Description:            "Naam en soort van het gemeentedeel.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "org-geo",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Gemeentedeel_Wijkaanduiding_Data",
		Kleur:                  "#fbcfe8",
		Veldnaam:               "wijkaanduiding",
		Padnaam:                "wijkaanduiding",
		Meervoud:               "wijkaanduiding",
		Factory:                func() Representatie { return &Gemeentedeel_Wijkaanduiding_Input{} },
		Tabelnaam:              "gemeentedeel_wijkaanduiding",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Gemeentedeel_Wijkaanduiding{} },
		DBSliceFactory:         func() any { return &[]Gemeentedeel_Wijkaanduiding{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "gemeentedeel_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 1200, Y: -1560}},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Gemeentedeel_Wijkaanduiding_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Gemeentedeelgemeente"] = TypeMeta{
		Typenaam:                  "Gemeentedeelgemeente",
		Klassenaam:                "Gemeentedeelgemeente",
		Description:               "De gemeente waarvan dit een deel is.",
		Metatype:                  MetatypeRelatie,
		IsMaterieel:               true,
		Domein:                    "org-geo",
		GESubtype:                 GESubtypeHub,
		DataTypenaam:              "Gemeentedeelgemeente_Data",
		Kleur:                     "",
		Veldnaam:                  "gemeentedeelgemeente",
		Padnaam:                   "gemeente",
		Meervoud:                  "gemeente",
		Factory:                   func() Representatie { return &Gemeentedeelgemeente_Input{} },
		Tabelnaam:                 "gemeentedeelgemeente",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &Gemeentedeelgemeente{} },
		DBSliceFactory:            func() any { return &[]Gemeentedeelgemeente{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "gemeentedeel_id",
		SecondaireEntiteitIDKolom: "gemeente_id",
		Momentvoorkomen:           Enkelvoudig,
		Directioneel:              true,
		Layout:                    &EditorLayout{Positie: &V3Positie{X: 600, Y: -1560}},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Gemeentedeelgemeente_Data", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Gemeentedeelgemeente_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Gemeentedeelgemeente_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Gemeentedeel_Wijkaanduiding_Data"] = TypeMeta{
		Typenaam:               "Gemeentedeel_Wijkaanduiding_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Gemeentedeel_Wijkaanduiding.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fbcfe8",
		Veldnaam:               "gemeentedeel_wijkaanduiding_data",
		Padnaam:                "gemeentedeel_wijkaanduiding_data",
		Meervoud:               "gemeentedeel_wijkaanduiding_data",
		Factory:                func() Representatie { return &Gemeentedeel_Wijkaanduiding_Data{} },
		SliceFactory:           func() any { return &[]Gemeentedeel_Wijkaanduiding_Data{} },
		Tabelnaam:              "gemeentedeel_wijkaanduiding_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Gemeentedeel_Wijkaanduiding_Data{} },
		DBSliceFactory:         func() any { return &[]Gemeentedeel_Wijkaanduiding_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "gemeentedeel_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Gemeentedeel_Wijkaanduiding",
	}
	MetaRegistry["Gemeentedeelgemeente_Data"] = TypeMeta{
		Typenaam:               "Gemeentedeelgemeente_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Gemeentedeelgemeente.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fbcfe8",
		Veldnaam:               "gemeentedeelgemeente_data",
		Padnaam:                "gemeentedeelgemeente_data",
		Meervoud:               "gemeentedeelgemeente_data",
		Factory:                func() Representatie { return &Gemeentedeelgemeente_Data{} },
		SliceFactory:           func() any { return &[]Gemeentedeelgemeente_Data{} },
		Tabelnaam:              "gemeentedeelgemeente_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Gemeentedeelgemeente_Data{} },
		DBSliceFactory:         func() any { return &[]Gemeentedeelgemeente_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "gemeentedeel_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Gemeentedeelgemeente",
	}
	MetaRegistry["Gemeentedeel_Aanvang"] = TypeMeta{
		Typenaam:               "Gemeentedeel_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Gemeentedeel.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#fbcfe8",
		Veldnaam:               "gemeentedeel_aanvang",
		Padnaam:                "gemeentedeel_aanvang",
		Meervoud:               "gemeentedeel_aanvang",
		Factory:                func() Representatie { return &Gemeentedeel_Aanvang{} },
		SliceFactory:           func() any { return &[]Gemeentedeel_Aanvang{} },
		Tabelnaam:              "gemeentedeel_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Gemeentedeel_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Gemeentedeel_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "gemeentedeel_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Gemeentedeel",
	}
	MetaRegistry["Gemeentedeel_Einde"] = TypeMeta{
		Typenaam:               "Gemeentedeel_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Gemeentedeel.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#fbcfe8",
		Veldnaam:               "gemeentedeel_einde",
		Padnaam:                "gemeentedeel_einde",
		Meervoud:               "gemeentedeel_einde",
		Factory:                func() Representatie { return &Gemeentedeel_Einde{} },
		SliceFactory:           func() any { return &[]Gemeentedeel_Einde{} },
		Tabelnaam:              "gemeentedeel_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Gemeentedeel_Einde{} },
		DBSliceFactory:         func() any { return &[]Gemeentedeel_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "gemeentedeel_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Gemeentedeel",
	}
	MetaRegistry["Gemeentedeelgemeente_Aanvang"] = TypeMeta{
		Typenaam:               "Gemeentedeelgemeente_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Gemeentedeelgemeente.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#fbcfe8",
		Veldnaam:               "gemeentedeelgemeente_aanvang",
		Padnaam:                "gemeentedeelgemeente_aanvang",
		Meervoud:               "gemeentedeelgemeente_aanvang",
		Factory:                func() Representatie { return &Gemeentedeelgemeente_Aanvang{} },
		SliceFactory:           func() any { return &[]Gemeentedeelgemeente_Aanvang{} },
		Tabelnaam:              "gemeentedeelgemeente_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Gemeentedeelgemeente_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Gemeentedeelgemeente_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "gemeentedeel_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Gemeentedeelgemeente",
	}
	MetaRegistry["Gemeentedeelgemeente_Einde"] = TypeMeta{
		Typenaam:               "Gemeentedeelgemeente_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Gemeentedeelgemeente.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#fbcfe8",
		Veldnaam:               "gemeentedeelgemeente_einde",
		Padnaam:                "gemeentedeelgemeente_einde",
		Meervoud:               "gemeentedeelgemeente_einde",
		Factory:                func() Representatie { return &Gemeentedeelgemeente_Einde{} },
		SliceFactory:           func() any { return &[]Gemeentedeelgemeente_Einde{} },
		Tabelnaam:              "gemeentedeelgemeente_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Gemeentedeelgemeente_Einde{} },
		DBSliceFactory:         func() any { return &[]Gemeentedeelgemeente_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "gemeentedeel_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Gemeentedeelgemeente",
	}

	// Referentielijst-instantie metadata + editor-posities
	ReferentielijstInstantieRegistry["AdellijkeTitels"] = ReferentielijstInstantieInfo{
		Naam:   "",
		Layout: &EditorLayout{Positie: &V3Positie{X: 1920, Y: -330}},
	}
	ReferentielijstInstantieRegistry["Landenlijst"] = ReferentielijstInstantieInfo{
		Naam:   "",
		Layout: &EditorLayout{Positie: &V3Positie{X: 1005, Y: -319.5}},
	}
}
