package model

// MetaRegistry-entries voor het register-domein.
// Bevat: Referentielijst + alle register-scope GE's.
// Wordt aangeroepen vanuit de centrale init-volgorde in metaregistry_plumbing.go.

func initRegisterMetaRegistry() {
	MetaRegistry["Referentielijst"] = TypeMeta{
		Typenaam:        "Referentielijst",
		Klassenaam:      "Referentielijst",
		Description:     "Generieke referentielijst-entiteit. Individuele lijsten (Landenlijst, EULidstaten, etc.) zijn records.",
		Metatype:        MetatypeEntiteit,
		EntiteitSubtype: EntiteitSubtypeReferentielijst,
		IsMaterieel:     true,
		Domein:          "register",
		Kleur:           "#fef3c7",
		Layout:          &EditorLayout{Positie: &V3Positie{X: 1260, Y: -240}},
		Veldnaam:        "referentielijst",
		Padnaam:         "referentielijsten",
		Meervoud:        "referentielijsten",
		Factory:         func() Representatie { return &Referentielijst{} },
		SliceFactory:    func() any { return &[]Referentielijst{} },
		Tabelnaam:       "register_referentielijst",
		IDKolom:         "id",
		DBFactory:       func() Representatie { return &Referentielijst{} },
		DBSliceFactory:  func() any { return &[]Referentielijst{} },
		HeeftPFK:        false,
		// Register-scope GE's; domein-specifieke items-relaties (bijv. LandenlijstLand)
		// worden door het domein-bestand zelf ge-append via VoegOnderliggendGEToe.
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Referentielijstnamen", JSONRolnaam: "referentielijstnamen", Doeltype: "Referentielijstnaam", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Referentielijstomschrijvingen", JSONRolnaam: "referentielijstomschrijvingen", Doeltype: "Referentielijstomschrijving", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Visibilities", JSONRolnaam: "visibilities", Doeltype: "ReferentielijstVisibility", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Internetadressen", JSONRolnaam: "internetadressen", Doeltype: "ReferentielijstInternetadres", Momentvoorkomen: Meervoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Referentielijst_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Referentielijst_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Referentielijstnaam"] = TypeMeta{
		Typenaam:               "Referentielijstnaam",
		Klassenaam:             "Referentielijstnaam",
		Description:            "Leesbare naam van een referentielijst.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Referentielijstnaam_Data",
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstnaam",
		Padnaam:                "referentielijstnamen",
		Meervoud:               "referentielijstnamen",
		Factory:                func() Representatie { return &Referentielijstnaam{} },
		Tabelnaam:              "referentielijstnaam",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Referentielijstnaam{} },
		DBSliceFactory:         func() any { return &[]Referentielijstnaam{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijst",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 1590, Y: -255}, EdgeID: "Referentielijst->Referentielijst_Referentielijstnaam", SourceHandle: "right", TargetHandle: "left"},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Referentielijstnaam_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Referentielijstnaam_Data"] = TypeMeta{
		Typenaam:               "Referentielijstnaam_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Referentielijstnaam.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstnaam_data",
		Padnaam:                "referentielijstnaam_data",
		Meervoud:               "referentielijstnaam_data",
		Factory:                func() Representatie { return &Referentielijstnaam_Data{} },
		SliceFactory:           func() any { return &[]Referentielijstnaam_Data{} },
		Tabelnaam:              "referentielijstnaam_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Referentielijstnaam_Data{} },
		DBSliceFactory:         func() any { return &[]Referentielijstnaam_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijstnaam",
	}
	MetaRegistry["Referentielijstomschrijving"] = TypeMeta{
		Typenaam:               "Referentielijstomschrijving",
		Klassenaam:             "Referentielijstomschrijving",
		Description:            "Omschrijving van een referentielijst.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Referentielijstomschrijving_Data",
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstomschrijving",
		Padnaam:                "referentielijstomschrijvingen",
		Meervoud:               "referentielijstomschrijvingen",
		Factory:                func() Representatie { return &Referentielijstomschrijving{} },
		Tabelnaam:              "referentielijstomschrijving",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Referentielijstomschrijving{} },
		DBSliceFactory:         func() any { return &[]Referentielijstomschrijving{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijst",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 1590, Y: -135}, EdgeID: "Referentielijst->Referentielijst_Referentielijstomschrijving", SourceHandle: "right", TargetHandle: "left"},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Referentielijstomschrijving_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Referentielijstomschrijving_Data"] = TypeMeta{
		Typenaam:               "Referentielijstomschrijving_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Referentielijstomschrijving.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstomschrijving_data",
		Padnaam:                "referentielijstomschrijving_data",
		Meervoud:               "referentielijstomschrijving_data",
		Factory:                func() Representatie { return &Referentielijstomschrijving_Data{} },
		SliceFactory:           func() any { return &[]Referentielijstomschrijving_Data{} },
		Tabelnaam:              "referentielijstomschrijving_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Referentielijstomschrijving_Data{} },
		DBSliceFactory:         func() any { return &[]Referentielijstomschrijving_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijstomschrijving",
	}
	MetaRegistry["ReferentielijstVisibility"] = TypeMeta{
		Typenaam:               "ReferentielijstVisibility",
		Klassenaam:             "Visibility",
		Description:            "Domeinzichtbaarheid van een referentielijst (register, modelspecifiek, extern).",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "ReferentielijstVisibility_Data",
		Kleur:                  "#fef3c7",
		Veldnaam:               "visibility",
		Padnaam:                "visibilities",
		Meervoud:               "visibilities",
		Factory:                func() Representatie { return &ReferentielijstVisibility{} },
		Tabelnaam:              "referentielijstvisibility",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &ReferentielijstVisibility{} },
		DBSliceFactory:         func() any { return &[]ReferentielijstVisibility{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijst",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 1590, Y: -15}, EdgeID: "Referentielijst->Referentielijst_ReferentielijstVisibility", SourceHandle: "right", TargetHandle: "left"},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "ReferentielijstVisibility_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["ReferentielijstVisibility_Data"] = TypeMeta{
		Typenaam:               "ReferentielijstVisibility_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van ReferentielijstVisibility.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstvisibility_data",
		Padnaam:                "referentielijstvisibility_data",
		Meervoud:               "referentielijstvisibility_data",
		Factory:                func() Representatie { return &ReferentielijstVisibility_Data{} },
		SliceFactory:           func() any { return &[]ReferentielijstVisibility_Data{} },
		Tabelnaam:              "referentielijstvisibility_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &ReferentielijstVisibility_Data{} },
		DBSliceFactory:         func() any { return &[]ReferentielijstVisibility_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "ReferentielijstVisibility",
	}
	MetaRegistry["ReferentielijstInternetadres"] = TypeMeta{
		Typenaam:               "ReferentielijstInternetadres",
		Klassenaam:             "Internetadres",
		Description:            "Internetadres (URL/URN) van een referentielijst.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "ReferentielijstInternetadres_Data",
		Kleur:                  "#fef3c7",
		Veldnaam:               "internetadres",
		Padnaam:                "internetadressen",
		Meervoud:               "internetadressen",
		Factory:                func() Representatie { return &ReferentielijstInternetadres{} },
		Tabelnaam:              "referentielijstinternetadres",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &ReferentielijstInternetadres{} },
		DBSliceFactory:         func() any { return &[]ReferentielijstInternetadres{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Meervoudig,
		BovenliggendTypenaam:   "Referentielijst",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 1590, Y: 85}, EdgeID: "Referentielijst->Referentielijst_ReferentielijstInternetadres", SourceHandle: "right", TargetHandle: "left"},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "ReferentielijstInternetadres_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["ReferentielijstInternetadres_Data"] = TypeMeta{
		Typenaam:               "ReferentielijstInternetadres_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van ReferentielijstInternetadres.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstinternetadres_data",
		Padnaam:                "referentielijstinternetadres_data",
		Meervoud:               "referentielijstinternetadres_data",
		Factory:                func() Representatie { return &ReferentielijstInternetadres_Data{} },
		SliceFactory:           func() any { return &[]ReferentielijstInternetadres_Data{} },
		Tabelnaam:              "referentielijstinternetadres_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &ReferentielijstInternetadres_Data{} },
		DBSliceFactory:         func() any { return &[]ReferentielijstInternetadres_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "ReferentielijstInternetadres",
	}
	MetaRegistry["Referentielijst_Aanvang"] = TypeMeta{
		Typenaam:               "Referentielijst_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van referentielijst.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijst_aanvang",
		Padnaam:                "referentielijst_aanvang",
		Meervoud:               "referentielijst_aanvang",
		Factory:                func() Representatie { return &Referentielijst_Aanvang{} },
		SliceFactory:           func() any { return &[]Referentielijst_Aanvang{} },
		Tabelnaam:              "referentielijst_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Referentielijst_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Referentielijst_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijst",
	}
	MetaRegistry["Referentielijst_Einde"] = TypeMeta{
		Typenaam:               "Referentielijst_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van referentielijst.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijst_einde",
		Padnaam:                "referentielijst_einde",
		Meervoud:               "referentielijst_einde",
		Factory:                func() Representatie { return &Referentielijst_Einde{} },
		SliceFactory:           func() any { return &[]Referentielijst_Einde{} },
		Tabelnaam:              "referentielijst_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Referentielijst_Einde{} },
		DBSliceFactory:         func() any { return &[]Referentielijst_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijst",
	}
}
