/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 17.0 		*/
/*  Created On : 28-Jan-2026 00:04:33 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "{representatie}" CASCADE
;

DROP TABLE IF EXISTS "Gebeurtenis" CASCADE
;

DROP TABLE IF EXISTS "O" CASCADE
;

DROP TABLE IF EXISTS "Opgave" CASCADE
;

DROP TABLE IF EXISTS "Registratie" CASCADE
;

DROP TABLE IF EXISTS "Wijziging" CASCADE
;

DROP TABLE IF EXISTS "X" CASCADE
;

/* Create Tables */

CREATE TABLE "{representatie}"
(
	"{representatie}ID" integer NOT NULL,
	"Naam" varchar(50) NULL,
	"WijzigingID" integer NOT NULL
)
;

CREATE TABLE "Gebeurtenis"
(
	"GebeurtenisID" integer NOT NULL,
	"OpgaveID" integer NULL,
	"Datum" date NULL,
	"Naam" varchar(50) NULL,
	"Opmerking" varchar(50) NULL
)
;

CREATE TABLE "O"
(
	"OID" integer NOT NULL,
	"XID" integer NULL,
	"Waarde" varchar(50) NULL,
	"WijzigingID" integer NULL
)
;

CREATE TABLE "Opgave"
(
	"OpgaveID" integer NOT NULL
)
;

CREATE TABLE "Registratie"
(
	"RegistratieID" integer NOT NULL,
	"RegistratieType" char(1) NULL,
	"Tijdstip" timestamp without time zone NULL,
	"Opmerking" varchar(50) NULL,
	"OpgaveID" integer NULL,
	"CorrigeertRegistratieID" integer NULL,
	"MaaktOngedaanRegistratieID" integer NULL
)
;

CREATE TABLE "Wijziging"
(
	"WijzigingID" integer NOT NULL,
	"WijzigingType" char(1) NULL,
	"RegistratieID" integer NULL,
	"Representatienaam" varchar(50) NULL,	-- de naam van de {Representatie} die gewijzigd is geworden.
	"Representatie_id" varchar(50) NULL,
	"Tijdstip" timestamp without time zone NULL	-- Het tijdstip van de Registratie.
)
;

CREATE TABLE "X"
(
	"XID" integer NOT NULL,
	"Waardevanx" varchar(50) NULL,
	"WijzigingID" integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "{representatie}" ADD CONSTRAINT "PK_{representatie}"
	PRIMARY KEY ("{representatie}ID")
;

ALTER TABLE "Gebeurtenis" ADD CONSTRAINT "PK_Gebeurtenis"
	PRIMARY KEY ("GebeurtenisID")
;

ALTER TABLE "O" ADD CONSTRAINT "PK_O"
	PRIMARY KEY ("OID")
;

ALTER TABLE "Opgave" ADD CONSTRAINT "PK_Opgave"
	PRIMARY KEY ("OpgaveID")
;

ALTER TABLE "Registratie" ADD CONSTRAINT "PK_Registratie"
	PRIMARY KEY ("RegistratieID")
;

CREATE INDEX "IXFK_Correctie_corrigeert" ON "Registratie" ("CorrigeertRegistratieID" ASC)
;

CREATE INDEX "IXFK_Registratie_Registratie" ON "Registratie" ("CorrigeertRegistratieID" ASC)
;

CREATE INDEX "IXFK_Registratie_Registratie_02" ON "Registratie" ("MaaktOngedaanRegistratieID" ASC)
;

ALTER TABLE "Wijziging" ADD CONSTRAINT "PK_Wijziging"
	PRIMARY KEY ("WijzigingID")
;

ALTER TABLE "X" ADD CONSTRAINT "PK_X"
	PRIMARY KEY ("XID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Gebeurtenis" ADD CONSTRAINT "FK_Gebeurtenis_Opgave"
	FOREIGN KEY ("OpgaveID") REFERENCES "Opgave" ("OpgaveID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "O" ADD CONSTRAINT "FK_O_Wijziging"
	FOREIGN KEY ("WijzigingID") REFERENCES "Wijziging" ("WijzigingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "O" ADD CONSTRAINT "FK_O_X"
	FOREIGN KEY ("XID") REFERENCES "X" ("XID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Registratie" ADD CONSTRAINT "FK_Corrigeert"
	FOREIGN KEY ("CorrigeertRegistratieID") REFERENCES "Registratie" ("RegistratieID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Registratie" ADD CONSTRAINT "FK_Registratie_Registratie"
	FOREIGN KEY ("MaaktOngedaanRegistratieID") REFERENCES "Registratie" ("RegistratieID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Registratie" ADD CONSTRAINT "FK_Registratie_registreert volgens"
	FOREIGN KEY ("OpgaveID") REFERENCES "Opgave" ("OpgaveID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Wijziging" ADD CONSTRAINT "FK_Wijziging_Registratie"
	FOREIGN KEY ("RegistratieID") REFERENCES "Registratie" ("RegistratieID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "X" ADD CONSTRAINT "FK_X_Wijziging"
	FOREIGN KEY ("WijzigingID") REFERENCES "Wijziging" ("WijzigingID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN "Wijziging"."Representatienaam"
	IS 'de naam van de {Representatie} die gewijzigd is geworden.'
;

COMMENT ON COLUMN "Wijziging"."Tijdstip"
	IS 'Het tijdstip van de Registratie.'
;
