/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 17.0 		*/
/*  Created On : 28-Jan-2026 15:23:54 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Gebeurtenis" CASCADE
;

DROP TABLE IF EXISTS "Opgave" CASCADE
;

DROP TABLE IF EXISTS "Registratie" CASCADE
;

DROP TABLE IF EXISTS "Wijziging" CASCADE
;

DROP TABLE IF EXISTS "X" CASCADE
;

DROP TABLE IF EXISTS "O" CASCADE
;

/* Create Tables */

CREATE TABLE "Gebeurtenis"
(
	gebeurtenis_id integer NOT NULL,
	opgave_id integer NULL,
	datum date NULL,
	naam varchar(50) NULL,
	opmerking varchar(50) NULL
)
;

CREATE TABLE "Opgave"
(
	opgave_id integer NOT NULL
)
;

CREATE TABLE "Registratie"
(
	registratie_id integer NOT NULL,
	registratietype char(1) NULL,
	tijdstip timestamp without time zone NULL,
	opmerking varchar(50) NULL,
	opgave_id integer NULL,
	corrigeert_registratie_id integer NULL,
	maakt_ongedaan_registratie_id integer NULL
)
;

CREATE TABLE "Wijziging"
(
	wijziging_id integer NOT NULL,
	wijzigingtype char(1) NULL,
	registratie_id integer NULL,
	representatienaam varchar(50) NULL,	-- de naam van de {Representatie} die gewijzigd is geworden.
	representatie_id varchar(50) NULL,
	tijdstip timestamp without time zone NULL	-- Het tijdstip van de Registratie.
)
;

CREATE TABLE "X"
(
	x_id integer NOT NULL,
	waarde_van_x varchar(50) NULL,
	wijziging_id integer NULL
)
;

CREATE TABLE "O"
(
	o_id integer NOT NULL,
	x_id integer NULL   DEFAULT x,
	waarde varchar(50) NULL,
	wijziging_id integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Gebeurtenis" ADD CONSTRAINT "PK_Gebeurtenis"
	PRIMARY KEY (gebeurtenis_id)
;

CREATE INDEX "IXFK_Gebeurtenis_Opgave" ON "Gebeurtenis" (opgave_id ASC)
;

ALTER TABLE "Opgave" ADD CONSTRAINT "PK_Opgave"
	PRIMARY KEY (opgave_id)
;

ALTER TABLE "Registratie" ADD CONSTRAINT "PK_Registratie"
	PRIMARY KEY (registratie_id)
;

CREATE INDEX "IXFK_Correctie_corrigeert" ON "Registratie" (corrigeert_registratie_id ASC)
;

CREATE INDEX "IXFK_Registratie_Registratie" ON "Registratie" (corrigeert_registratie_id ASC)
;

CREATE INDEX "IXFK_Registratie_Registratie_02" ON "Registratie" (maakt_ongedaan_registratie_id ASC)
;

CREATE INDEX "IXFK_Registratie_registreert volgens" ON "Registratie" (opgave_id ASC)
;

ALTER TABLE "Wijziging" ADD CONSTRAINT "PK_Wijziging"
	PRIMARY KEY (wijziging_id)
;

ALTER TABLE "X" ADD CONSTRAINT "PK_X"
	PRIMARY KEY (x_id)
;

CREATE INDEX "IXFK_X_Wijziging" ON "X" (wijziging_id ASC)
;

ALTER TABLE "O" ADD CONSTRAINT "PK_O"
	PRIMARY KEY (o_id)
;

CREATE INDEX "IXFK_O_Wijziging" ON "O" (wijziging_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "Gebeurtenis" ADD CONSTRAINT "FK_Gebeurtenis_Opgave"
	FOREIGN KEY (opgave_id) REFERENCES "Opgave" (opgave_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Registratie" ADD CONSTRAINT "FK_Corrigeert"
	FOREIGN KEY (corrigeert_registratie_id) REFERENCES "Registratie" (registratie_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Registratie" ADD CONSTRAINT "FK_Registratie_Registratie"
	FOREIGN KEY (maakt_ongedaan_registratie_id) REFERENCES "Registratie" (registratie_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Registratie" ADD CONSTRAINT "FK_Registratie_registreert volgens"
	FOREIGN KEY (opgave_id) REFERENCES "Opgave" (opgave_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Wijziging" ADD CONSTRAINT "FK_Wijziging_Registratie"
	FOREIGN KEY (registratie_id) REFERENCES "Registratie" (registratie_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "X" ADD CONSTRAINT "FK_X_Wijziging"
	FOREIGN KEY (wijziging_id) REFERENCES "Wijziging" (wijziging_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "O" ADD CONSTRAINT "FK_O_Wijziging"
	FOREIGN KEY (wijziging_id) REFERENCES "Wijziging" (wijziging_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "O" ADD CONSTRAINT "FK_O_X"
	FOREIGN KEY (x_id) REFERENCES "X" (x_id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN "Wijziging".representatienaam
	IS 'de naam van de {Representatie} die gewijzigd is geworden.'
;

COMMENT ON COLUMN "Wijziging".tijdstip
	IS 'Het tijdstip van de Registratie.'
;
