EVALUATE
    SELECTCOLUMNS(
        TOPN(
            10000,
            'Common Ground Initiatieven & Resultaten (uitgebreid)',
            'Common Ground Initiatieven & Resultaten (uitgebreid)'[FileSystemObjectType],
            ASC
        ),
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[FileSystemObjectType],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Id],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[ServerRedirectedEmbedUri],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[ServerRedirectedEmbedUrl],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Naam],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[OData__ColorTag],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[ComplianceAssetId],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Identificatie],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[e-Mailadres],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Korte omschrijving],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Type],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Indieneencomponentofeenstandaard],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Gemeenten die meedoen in de realisatie],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Gebruikende gemeenten ],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Startdatum initiatief],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Contact organisatie],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Contactpersoon],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Bijdrage wendbaarheid],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Bijdrage dienstverlening],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Bijdrage regie op gegevens],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Informatie over de planning],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Toegepaste gemeentelijke standaarden],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Vervangtditproductouderesoftware],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Fase initiatief],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Obstakels],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Zijnernogvragennaaraanleidingvan],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Checkcategoriezilver],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Fase CG portfolio],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Wanneerwordtverwachtdathetinitia],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[OData_16.Inhoeverredraagth],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[OData_18.Inhoeverredraagth],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[OData_22.Inhoeverredraagth],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Gemeenten die gebruik maken van dit initiatief],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Betrokken leveranciers],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Website],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Gemeenten die betrokken zijn bij de realisatie van dit initiatief],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Maandzilver],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Maandgoud],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[OData_5.Indieneentoepassin],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[RedenatiepromoverenZilver],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Redenatiepromoverengoud],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Leverancier],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Github],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Etalagelevel1],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Etalagelevel2],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Readyforuse],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Goudnietgehaald],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Redenatiegoudnietgehaald],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[ID.1],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Modified],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Aanmeldingsdatum],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[AuthorId],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[EditorId],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[OData__UIVersionString],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Attachments],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[GUID],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Inwelkdomeinpasthetinitiatief_x0.1],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Inwelkdomeinpasthetinitiatief_x0.2],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Inwelkdomeinpasthetinitiatief_x0.3],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Inwelkdomeinpasthetinitiatief_x0.4],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Inwelkdomeinpasthetinitiatief_x0.5],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Inwelkdomeinpasthetinitiatief_x0.6],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Inwelkdomeinpasthetinitiatief_x0.7],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Inwelkdomeinpasthetinitiatief_x0.8],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Inwelkdomeinpasthetinitiatief_x0.9],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Inwelkdomeinpasthetinitiatief_x0.10],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Welketypeorganisatieszijnbetrokk.1],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Welketypeorganisatieszijnbetrokk.2],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Welketypeorganisatieszijnbetrokk.3],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Welketypeorganisatieszijnbetrokk.4],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Welketypeorganisatieszijnbetrokk.5],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[OData_27.Opwelkelaagofopwe.1],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[OData_27.Opwelkelaagofopwe.2],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[OData_27.Opwelkelaagofopwe.3],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[OData_27.Opwelkelaagofopwe.4],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[OData_27.Opwelkelaagofopwe.5],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Sociaal Domein],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Dienstverlening],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Randvoorwaardelijk],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Burgerzaken],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Ruimtelijke ordening],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Bedrijfsvoering (HR, ICT, Finance, facilitair, inkoop)],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[(Lokale) belastingen],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Fysieke leefomgeving],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Bestuur],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Openbare orde en veiligheid],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Laag 1],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Laag 2],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Laag 3],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Laag 4],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Laag 5],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[VNG type organisatie],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Gemeenten type org],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Ketenpartners type org],
        'Common Ground Initiatieven & Resultaten (uitgebreid)'[Leveranciers type org]
    )
    ORDER BY 'Common Ground Initiatieven & Resultaten (uitgebreid)'[FileSystemObjectType] ASC
 