classDiagram

  class ReferentielijstAdrestype {
    <<enumeration>>
    URL
    URN
  }

  class KorteTekst {
    <<datatype>>
    +string basistype
  }

  class LangeTekst {
    <<datatype>>
    +string basistype
  }

  class AN40 {
    <<datatype>>
    +string basistype
  }

  class AN200 {
    <<datatype>>
    +string basistype
  }

  class Geheel {
    <<datatype>>
    +integer basistype
    +String format = "int32"
  }

  class Decimaal {
    <<datatype>>
    +number basistype
    +String format = "double"
  }

  class Bedrag {
    <<datatype>>
    +number basistype
    +String format = "double"
  }

  class Percentage {
    <<datatype>>
    +number basistype
    +String format = "double"
  }

  class Datum {
    <<datatype>>
    +string basistype
    +String format = "date"
  }

  class DatumTijd {
    <<datatype>>
    +string basistype
    +String format = "date-time"
  }

  class Jaar {
    <<datatype>>
    +integer basistype
  }

  class JaNee {
    <<datatype>>
    +boolean basistype
  }

  class IBAN {
    <<datatype>>
    +string basistype
    +String format = "iban"
    +String pattern
  }

  class KvKNummer {
    <<datatype>>
    +string basistype
    +String format = "kvk-nummer"
    +String pattern
  }

  class Emailadres {
    <<datatype>>
    +string basistype
    +String format = "email"
  }

  class Telefoonnummer {
    <<datatype>>
    +string basistype
    +String format = "phone"
  }

  class Versie {
    <<datatype>>
    +string basistype
    +String format = "versie"
    +String pattern
  }

  class Organisatie {
    <<entiteit>>
    <<materieel>>
  }

  class Organisatie_Contactgegevens {
    <<gegevenselement>>
    +string~uri~ url
    +Emailadres email
    +Telefoonnummer telefoonnummer
  }

  class Organisatie_Organisatienaam {
    <<gegevenselement>>
    +string naam
  }

  class Contactpersoon {
    <<relatie>>
    +string rol
  }

  class Persoon {
    <<entiteit>>
    <<materieel>>
  }

  class Persoon_Contactgegevens {
    <<gegevenselement>>
    +Emailadres email
    +Telefoonnummer telefoonnummer
  }

  class Persoon_Persoonnaam {
    <<gegevenselement>>
    +string naam
  }

  class Referentielijst {
    <<entiteit>>
    <<materieel>>
  }

  class Referentielijst_Referentielijstnaam {
    <<gegevenselement>>
    +string naam
  }

  class Referentielijst_Referentielijstomschrijving {
    <<gegevenselement>>
    +string omschrijving
  }

  class Referentielijst_ReferentielijstVisibility {
    <<gegevenselement>>
    +string domein
  }

  class Referentielijst_ReferentielijstInternetadres {
    <<gegevenselement>>
    +ReferentielijstAdrestype adrestype
    +string adres
    +string organisatie
  }

  namespace CGCT {
    class Repository {
      <<entiteit>>
      <<materieel>>
    }

    class Repository_RepoAddress {
      <<gegevenselement>>
      +string url
    }

    class Repository_RepoName {
      <<gegevenselement>>
      +string name
    }

    class Unnamed {
      <<relatie>>
      +string role
    }

    class RepoOrgRole {
      <<enumeration>>
      Owner
      Contributor
      User
    }

    class Repository_ {
      <<gegevenselement>>
      +AspectAnalysiTypes aspectType
      +DatumTijd readyAt
      +integer score
    }

    class AspectAnalysiTypes {
      <<enumeration>>
      Code
      Documentation
      Etc
    }

    class RepoAnalysis {
      <<entiteit>>
    }

    class Unnamed {
      <<relatie>>
    }

    class Unnamed {
      <<gegevenselement>>
      +DatumTijd checkedAt
      +Decimaal score
    }
  }
  Organisatie "1" --> "0..1" Organisatie_Contactgegevens : Contactgegevens
  Organisatie_Contactgegevens "1" --> "*" Emailadres
  Organisatie_Contactgegevens "1" --> "*" Telefoonnummer
  Organisatie "1" --> "0..1" Organisatie_Organisatienaam : Organisatienaam
  Organisatie "1" --> "0..1" Contactpersoon : Contactpersoon
  Contactpersoon "1" --> "0..*" Persoon : → Persoon
  Persoon "1" --> "0..1" Persoon_Contactgegevens : Contactgegevens
  Persoon_Contactgegevens "1" --> "*" Emailadres
  Persoon_Contactgegevens "1" --> "*" Telefoonnummer
  Persoon "1" --> "0..1" Persoon_Persoonnaam : Persoonnaam
  Referentielijst "1" --> "0..1" Referentielijst_Referentielijstnaam : Referentielijstnaam
  Referentielijst "1" --> "0..1" Referentielijst_Referentielijstomschrijving : Referentielijstomschrijving
  Referentielijst "1" --> "0..1" Referentielijst_ReferentielijstVisibility : ReferentielijstVisibility
  Referentielijst "1" --> "0..*" Referentielijst_ReferentielijstInternetadres : ReferentielijstInternetadres
  Referentielijst_ReferentielijstInternetadres "1" --> "*" ReferentielijstAdrestype
  Repository "1" --> "0..1" Repository_RepoAddress
  Repository "1" --> "0..*" relatie_1775754208569_5
  relatie_1775754208569_5 "1" --> "1" Organisatie
  Repository "1" --> "0..1" Repository_RepoName
  relatie_1775754208569_5 "1" --> "*" RepoOrgRole
  Repository_ "1" --> "*" DatumTijd
  Repository_ "1" --> "*" AspectAnalysiTypes
  RepoAnalysis "1" --> "0..1" Repository_
  Repository "1" --> "0..*" relatie_1775754922324_22
  relatie_1775754922324_22 "1" --> "1" RepoAnalysis
  RepoAnalysis "1" --> "0..1" gegevenselement_1775755031727_25
  gegevenselement_1775755031727_25 "1" --> "*" DatumTijd
  gegevenselement_1775755031727_25 "1" --> "*" Percentage
  Organisatie_Contactgegevens ..> Emailadres : uses
  Organisatie_Contactgegevens ..> Telefoonnummer : uses
  Persoon_Contactgegevens ..> Emailadres : uses
  Persoon_Contactgegevens ..> Telefoonnummer : uses
  Referentielijst_ReferentielijstInternetadres ..> ReferentielijstAdrestype : uses
  Repository_ ..> AspectAnalysiTypes : uses
  Repository_ ..> DatumTijd : uses
  Unnamed ..> DatumTijd : uses
  Unnamed ..> Decimaal : uses