// @ts-check

export const ELEMENT_TYPE_MAPPING = Object.freeze({
  BusinessActor: "business-actor",
  BusinessRole: "business-rol",
  BusinessProcess: "business-proces",
  BusinessFunction: "business-functie",
  BusinessService: "business-service",
  BusinessEvent: "business-event",
  BusinessObject: "business-object",
  ApplicationComponent: "app-component",
  ApplicationService: "app-service",
  ApplicationFunction: "app-functie",
  DataObject: "data-object",
  Node: "node",
  Device: "device",
  SystemSoftware: "systeemsoftware",
  TechnologyService: "tech-service",
  Artifact: "artifact",
  Stakeholder: "stakeholder",
  Driver: "driver",
  Goal: "goal",
  Principle: "principle",
  Requirement: "requirement",
  Constraint: "constraint",
  AndJunction: "junction",
  OrJunction: "junction",
  // ── 3.2-completering (04-09): de volledige elemententabel. De eerste
  // echte Archi-import (GEMMA-doelarchitectuur) strandde op deze typen. ──
  BusinessCollaboration: "business-collaboratie",
  BusinessInterface: "business-interface",
  BusinessInteraction: "business-interactie",
  Contract: "contract",
  Representation: "representatie",
  Product: "product",
  ApplicationCollaboration: "app-collaboratie",
  ApplicationInterface: "app-interface",
  ApplicationInteraction: "app-interactie",
  ApplicationProcess: "app-proces",
  ApplicationEvent: "app-event",
  TechnologyCollaboration: "tech-collaboratie",
  TechnologyInterface: "tech-interface",
  TechnologyFunction: "tech-functie",
  TechnologyProcess: "tech-proces",
  TechnologyInteraction: "tech-interactie",
  TechnologyEvent: "tech-event",
  Path: "pad",
  CommunicationNetwork: "communicatienetwerk",
  Equipment: "equipment",
  Facility: "facility",
  DistributionNetwork: "distributienetwerk",
  Material: "materiaal",
  Resource: "resource",
  Capability: "capability",
  CourseOfAction: "koers",
  ValueStream: "waardestroom",
  Assessment: "assessment",
  Outcome: "outcome",
  Meaning: "betekenis",
  Value: "waarde",
  WorkPackage: "werkpakket",
  Deliverable: "deliverable",
  ImplementationEvent: "implementatie-event",
  Plateau: "plateau",
  Gap: "gap",
  Location: "locatie",
  Grouping: "grouping",
});

export const RELATIONSHIP_TYPE_MAPPING = Object.freeze({
  Composition: "compositie",
  CompositionRelationship: "compositie",
  Aggregation: "aggregatie",
  AggregationRelationship: "aggregatie",
  Assignment: "toewijzing",
  AssignmentRelationship: "toewijzing",
  Realization: "realisatie",
  RealizationRelationship: "realisatie",
  Serving: "bediening",
  ServingRelationship: "bediening",
  Access: "toegang",
  AccessRelationship: "toegang",
  Influence: "beinvloeding",
  InfluenceRelationship: "beinvloeding",
  Triggering: "trigger",
  TriggeringRelationship: "trigger",
  Flow: "stroom",
  FlowRelationship: "stroom",
  Specialization: "specialisatie",
  SpecializationRelationship: "specialisatie",
  Association: "associatie",
  AssociationRelationship: "associatie",
});

export function mapElementType(exchangeType) {
  return ELEMENT_TYPE_MAPPING[exchangeType] || null;
}

export function mapRelationshipType(exchangeType) {
  return RELATIONSHIP_TYPE_MAPPING[exchangeType] || null;
}