package model

// Additieve MetaRegistry-entries — voegt types toe aan de bestaande MetaRegistry.
// Gegenereerd door cmd/codegen — niet handmatig bewerken.

func initRegisterMetaRegistry() {
	MetaRegistry["Land"] = TypeMeta{
		Typenaam:               "Land",
		Klassenaam:             "Land",
		Description:            "Referentielijst-item: individueel land.",
		Metatype:               MetatypeEntiteit,
		EntiteitSubtype:        EntiteitSubtypeReferentielijstItem,
		IsMaterieel:            true,
		Domein:                 "register",
		Kleur:                  "#fde68a",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 1170, Y: -120}},
		Veldnaam:               "land",
		Padnaam:                "landen",
		Meervoud:               "landen",
		Factory:                func() Representatie { return &Land{} },
		SliceFactory:           func() any { return &[]Land{} },
		Tabelnaam:              "land",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &Land{} },
		DBSliceFactory:         func() any { return &[]Land{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Landcodes", JSONRolnaam: "landcodes", Doeltype: "Landcode", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Landnamen", JSONRolnaam: "landnamen", Doeltype: "Landnaam", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Land_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Land_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Landcode"] = TypeMeta{
		Typenaam:               "Landcode",
		Klassenaam:             "Landcode",
		Description:            "Enkelvoudig gegevenselement landcode van Land.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "register",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Landcode_Data",
		Kleur:                  "#fde68a",
		Veldnaam:               "landcode",
		Padnaam:                "landcodes",
		Meervoud:               "landcodes",
		Factory:                func() Representatie { return &Landcode_Input{} },
		Tabelnaam:              "landcode",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Landcode{} },
		DBSliceFactory:         func() any { return &[]Landcode{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "land_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 1050, Y: 90}, EdgeID: "edge_1774646153149_10",
			SourceHandle: "bottom", TargetHandle: "top",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Landcode_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Landnaam"] = TypeMeta{
		Typenaam:               "Landnaam",
		Klassenaam:             "Landnaam",
		Description:            "Enkelvoudig gegevenselement landnaam van Land.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "register",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Landnaam_Data",
		Kleur:                  "#fde68a",
		Veldnaam:               "landnaam",
		Padnaam:                "landnamen",
		Meervoud:               "landnamen",
		Factory:                func() Representatie { return &Landnaam_Input{} },
		Tabelnaam:              "landnaam",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Landnaam{} },
		DBSliceFactory:         func() any { return &[]Landnaam{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "land_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 1290, Y: 90}, EdgeID: "edge_1774646072605_7",
			SourceHandle: "bottom", TargetHandle: "top",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Landnaam_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Landcode_Data"] = TypeMeta{
		Typenaam:               "Landcode_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Landcode.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fde68a",
		Veldnaam:               "landcode_data",
		Padnaam:                "landcode_data",
		Meervoud:               "landcode_data",
		Factory:                func() Representatie { return &Landcode_Data{} },
		SliceFactory:           func() any { return &[]Landcode_Data{} },
		Tabelnaam:              "landcode_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Landcode_Data{} },
		DBSliceFactory:         func() any { return &[]Landcode_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "land_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Landcode",
	}
	MetaRegistry["Landnaam_Data"] = TypeMeta{
		Typenaam:               "Landnaam_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Landnaam.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fde68a",
		Veldnaam:               "landnaam_data",
		Padnaam:                "landnaam_data",
		Meervoud:               "landnaam_data",
		Factory:                func() Representatie { return &Landnaam_Data{} },
		SliceFactory:           func() any { return &[]Landnaam_Data{} },
		Tabelnaam:              "landnaam_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Landnaam_Data{} },
		DBSliceFactory:         func() any { return &[]Landnaam_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "land_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Landnaam",
	}
	MetaRegistry["Land_Aanvang"] = TypeMeta{
		Typenaam:               "Land_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Land.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#fde68a",
		Veldnaam:               "land_aanvang",
		Padnaam:                "land_aanvang",
		Meervoud:               "land_aanvang",
		Factory:                func() Representatie { return &Land_Aanvang{} },
		SliceFactory:           func() any { return &[]Land_Aanvang{} },
		Tabelnaam:              "land_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Land_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Land_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "land_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Land",
	}
	MetaRegistry["Land_Einde"] = TypeMeta{
		Typenaam:               "Land_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Land.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#fde68a",
		Veldnaam:               "land_einde",
		Padnaam:                "land_einde",
		Meervoud:               "land_einde",
		Factory:                func() Representatie { return &Land_Einde{} },
		SliceFactory:           func() any { return &[]Land_Einde{} },
		Tabelnaam:              "land_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Land_Einde{} },
		DBSliceFactory:         func() any { return &[]Land_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "land_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Land",
	}
	MetaRegistry["Referentielijst"] = TypeMeta{
		Typenaam:               "Referentielijst",
		Klassenaam:             "Referentielijst",
		Description:            "Generieke referentielijst-entiteit. Individuele lijsten (Landenlijst, EULidstaten, etc.) zijn records.",
		Metatype:               MetatypeEntiteit,
		EntiteitSubtype:        EntiteitSubtypeReferentielijst,
		IsMaterieel:            true,
		Domein:                 "register",
		Kleur:                  "#fef3c7",
		Layout:                 &EditorLayout{Positie: &V3Positie{X: 1335, Y: -690}},
		Veldnaam:               "referentielijst",
		Padnaam:                "referentielijsten",
		Meervoud:               "referentielijsten",
		Factory:                func() Representatie { return &Referentielijst{} },
		SliceFactory:           func() any { return &[]Referentielijst{} },
		Tabelnaam:              "referentielijst",
		IDKolom:                "id",
		DBFactory:              func() Representatie { return &Referentielijst{} },
		DBSliceFactory:         func() any { return &[]Referentielijst{} },
		HeeftPFK:               false,
		RelatieveAutoincrement: false,
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Referentielijstnamen", JSONRolnaam: "referentielijstnamen", Doeltype: "Referentielijstnaam", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Referentielijstomschrijvingen", JSONRolnaam: "referentielijstomschrijvingen", Doeltype: "Referentielijstomschrijving", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Visibilities", JSONRolnaam: "visibilities", Doeltype: "ReferentielijstVisibility", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Internetadressen", JSONRolnaam: "internetadressen", Doeltype: "ReferentielijstInternetadres", Momentvoorkomen: Meervoudig},
			{Rolnaam: "LandenlijstLanden", JSONRolnaam: "landenlijst_landen", Doeltype: "LandenlijstLand", Momentvoorkomen: Meervoudig},
			{Rolnaam: "AdellijkeTitelsTitels", JSONRolnaam: "adellijke_titels_titels", Doeltype: "AdellijkeTitelsTitel", Momentvoorkomen: Meervoudig},
			{Rolnaam: "Aanvang", JSONRolnaam: "aanvang", Doeltype: "Referentielijst_Aanvang", Momentvoorkomen: Enkelvoudig},
			{Rolnaam: "Einde", JSONRolnaam: "einde", Doeltype: "Referentielijst_Einde", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Referentielijstnaam"] = TypeMeta{
		Typenaam:               "Referentielijstnaam",
		Klassenaam:             "Referentielijstnaam",
		Description:            "Leesbare naam van een referentielijst.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "register",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Referentielijstnaam_Data",
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstnaam",
		Padnaam:                "referentielijstnamen",
		Meervoud:               "referentielijstnamen",
		Factory:                func() Representatie { return &Referentielijstnaam_Input{} },
		Tabelnaam:              "referentielijstnaam",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Referentielijstnaam{} },
		DBSliceFactory:         func() any { return &[]Referentielijstnaam{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 1815, Y: -915}, EdgeID: "Referentielijst->Referentielijst_Referentielijstnaam",
			SourceHandle: "right", TargetHandle: "left",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Referentielijstnaam_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Referentielijstomschrijving"] = TypeMeta{
		Typenaam:               "Referentielijstomschrijving",
		Klassenaam:             "Referentielijstomschrijving",
		Description:            "Omschrijving van een referentielijst.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "register",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "Referentielijstomschrijving_Data",
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstomschrijving",
		Padnaam:                "referentielijstomschrijvingen",
		Meervoud:               "referentielijstomschrijvingen",
		Factory:                func() Representatie { return &Referentielijstomschrijving_Input{} },
		Tabelnaam:              "referentielijstomschrijving",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &Referentielijstomschrijving{} },
		DBSliceFactory:         func() any { return &[]Referentielijstomschrijving{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 1815, Y: -795}, EdgeID: "Referentielijst->Referentielijst_Referentielijstomschrijving",
			SourceHandle: "right", TargetHandle: "left",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "Referentielijstomschrijving_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["ReferentielijstVisibility"] = TypeMeta{
		Typenaam:               "ReferentielijstVisibility",
		Klassenaam:             "ReferentielijstVisibility",
		Description:            "Domeinzichtbaarheid van een referentielijst (register, modelspecifiek, extern).",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "register",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "ReferentielijstVisibility_Data",
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstvisibility",
		Padnaam:                "visibilities",
		Meervoud:               "visibilities",
		Factory:                func() Representatie { return &ReferentielijstVisibility_Input{} },
		Tabelnaam:              "referentielijstvisibility",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &ReferentielijstVisibility{} },
		DBSliceFactory:         func() any { return &[]ReferentielijstVisibility{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 1815, Y: -675}, EdgeID: "Referentielijst->Referentielijst_ReferentielijstVisibility",
			SourceHandle: "right", TargetHandle: "left",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "ReferentielijstVisibility_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["ReferentielijstInternetadres"] = TypeMeta{
		Typenaam:               "ReferentielijstInternetadres",
		Klassenaam:             "ReferentielijstInternetadres",
		Description:            "Internetadres (URL/URN) van een referentielijst.",
		Metatype:               MetatypeGegevenselement,
		IsMaterieel:            false,
		Domein:                 "register",
		GESubtype:              GESubtypeHub,
		DataTypenaam:           "ReferentielijstInternetadres_Data",
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstinternetadres",
		Padnaam:                "internetadressen",
		Meervoud:               "internetadressen",
		Factory:                func() Representatie { return &ReferentielijstInternetadres_Input{} },
		Tabelnaam:              "referentielijstinternetadres",
		IDKolom:                "rel_id",
		DBFactory:              func() Representatie { return &ReferentielijstInternetadres{} },
		DBSliceFactory:         func() any { return &[]ReferentielijstInternetadres{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Meervoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 1815, Y: -575}, EdgeID: "Referentielijst->Referentielijst_ReferentielijstInternetadres",
			SourceHandle: "right", TargetHandle: "left",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "ReferentielijstInternetadres_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["LandenlijstLand"] = TypeMeta{
		Typenaam:                  "LandenlijstLand",
		Klassenaam:                "LandenlijstLand",
		Description:               "Koppeling van een land aan referentielijst-instantie Landenlijst (referentielijst-items relatie).",
		Metatype:                  MetatypeRelatie,
		RelatieSubtype:            RelatieSubtypeReferentielijstItems,
		ReferentielijstInstantie:  "Landenlijst",
		IsMaterieel:               false,
		Domein:                    "register",
		GESubtype:                 GESubtypeHub,
		DataTypenaam:              "LandenlijstLand_Data",
		Kleur:                     "",
		Veldnaam:                  "landenlijstland",
		Padnaam:                   "landenlijst_landen",
		Meervoud:                  "landenlijst_landen",
		Factory:                   func() Representatie { return &LandenlijstLand_Input{} },
		Tabelnaam:                 "landenlijstland",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &LandenlijstLand{} },
		DBSliceFactory:            func() any { return &[]LandenlijstLand{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "referentielijst_id",
		SecondaireEntiteitIDKolom: "land_id",
		Momentvoorkomen:           Meervoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 1170, Y: -300}, EdgeID: "Referentielijst->LandenlijstLand",
			DoelEdgeID: "LandenlijstLand->Land",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "LandenlijstLand_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["AdellijkeTitelsTitel"] = TypeMeta{
		Typenaam:                  "AdellijkeTitelsTitel",
		Klassenaam:                "AdellijkeTitelsTitel",
		Description:               "Koppeling van een adellijke titel aan referentielijst-instantie AdellijkeTitels (referentielijst-items relatie).",
		Metatype:                  MetatypeRelatie,
		RelatieSubtype:            RelatieSubtypeReferentielijstItems,
		ReferentielijstInstantie:  "AdellijkeTitels",
		IsMaterieel:               false,
		Domein:                    "register",
		GESubtype:                 GESubtypeHub,
		DataTypenaam:              "AdellijkeTitelsTitel_Data",
		Kleur:                     "",
		Veldnaam:                  "adellijketitelstitel",
		Padnaam:                   "adellijke_titels_titels",
		Meervoud:                  "adellijke_titels_titels",
		Factory:                   func() Representatie { return &AdellijkeTitelsTitel_Input{} },
		Tabelnaam:                 "adellijketitelstitel",
		IDKolom:                   "rel_id",
		DBFactory:                 func() Representatie { return &AdellijkeTitelsTitel{} },
		DBSliceFactory:            func() any { return &[]AdellijkeTitelsTitel{} },
		HeeftPFK:                  true,
		RelatieveAutoincrement:    true,
		EntiteitIDKolom:           "referentielijst_id",
		SecondaireEntiteitIDKolom: "adellijketitel_id",
		Momentvoorkomen:           Meervoudig,
		Layout: &EditorLayout{
			Positie: &V3Positie{X: 1530, Y: -300}, EdgeID: "Referentielijst->AdellijkeTitelsTitel",
			DoelEdgeID: "AdellijkeTitelsTitel->AdellijkeTitel",
		},
		OnderliggendeGegevenselementen: []OnderliggendGegevenselement{
			{Rolnaam: "Data", JSONRolnaam: "data", Doeltype: "AdellijkeTitelsTitel_Data", Momentvoorkomen: Enkelvoudig},
		},
	}
	MetaRegistry["Referentielijstnaam_Data"] = TypeMeta{
		Typenaam:               "Referentielijstnaam_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Referentielijstnaam.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstnaam_data",
		Padnaam:                "referentielijstnaam_data",
		Meervoud:               "referentielijstnaam_data",
		Factory:                func() Representatie { return &Referentielijstnaam_Data{} },
		SliceFactory:           func() any { return &[]Referentielijstnaam_Data{} },
		Tabelnaam:              "referentielijstnaam_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Referentielijstnaam_Data{} },
		DBSliceFactory:         func() any { return &[]Referentielijstnaam_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijstnaam",
	}
	MetaRegistry["Referentielijstomschrijving_Data"] = TypeMeta{
		Typenaam:               "Referentielijstomschrijving_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van Referentielijstomschrijving.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstomschrijving_data",
		Padnaam:                "referentielijstomschrijving_data",
		Meervoud:               "referentielijstomschrijving_data",
		Factory:                func() Representatie { return &Referentielijstomschrijving_Data{} },
		SliceFactory:           func() any { return &[]Referentielijstomschrijving_Data{} },
		Tabelnaam:              "referentielijstomschrijving_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Referentielijstomschrijving_Data{} },
		DBSliceFactory:         func() any { return &[]Referentielijstomschrijving_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijstomschrijving",
	}
	MetaRegistry["ReferentielijstVisibility_Data"] = TypeMeta{
		Typenaam:               "ReferentielijstVisibility_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van ReferentielijstVisibility.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstvisibility_data",
		Padnaam:                "referentielijstvisibility_data",
		Meervoud:               "referentielijstvisibility_data",
		Factory:                func() Representatie { return &ReferentielijstVisibility_Data{} },
		SliceFactory:           func() any { return &[]ReferentielijstVisibility_Data{} },
		Tabelnaam:              "referentielijstvisibility_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &ReferentielijstVisibility_Data{} },
		DBSliceFactory:         func() any { return &[]ReferentielijstVisibility_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "ReferentielijstVisibility",
	}
	MetaRegistry["ReferentielijstInternetadres_Data"] = TypeMeta{
		Typenaam:               "ReferentielijstInternetadres_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van ReferentielijstInternetadres.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijstinternetadres_data",
		Padnaam:                "referentielijstinternetadres_data",
		Meervoud:               "referentielijstinternetadres_data",
		Factory:                func() Representatie { return &ReferentielijstInternetadres_Data{} },
		SliceFactory:           func() any { return &[]ReferentielijstInternetadres_Data{} },
		Tabelnaam:              "referentielijstinternetadres_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &ReferentielijstInternetadres_Data{} },
		DBSliceFactory:         func() any { return &[]ReferentielijstInternetadres_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "ReferentielijstInternetadres",
	}
	MetaRegistry["LandenlijstLand_Data"] = TypeMeta{
		Typenaam:               "LandenlijstLand_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van LandenlijstLand.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fef3c7",
		Veldnaam:               "landenlijstland_data",
		Padnaam:                "landenlijstland_data",
		Meervoud:               "landenlijstland_data",
		Factory:                func() Representatie { return &LandenlijstLand_Data{} },
		SliceFactory:           func() any { return &[]LandenlijstLand_Data{} },
		Tabelnaam:              "landenlijstland_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &LandenlijstLand_Data{} },
		DBSliceFactory:         func() any { return &[]LandenlijstLand_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "LandenlijstLand",
	}
	MetaRegistry["AdellijkeTitelsTitel_Data"] = TypeMeta{
		Typenaam:               "AdellijkeTitelsTitel_Data",
		Klassenaam:             "Data",
		Description:            "Geversioned inhoud van AdellijkeTitelsTitel.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeData,
		Kleur:                  "#fef3c7",
		Veldnaam:               "adellijketitelstitel_data",
		Padnaam:                "adellijketitelstitel_data",
		Meervoud:               "adellijketitelstitel_data",
		Factory:                func() Representatie { return &AdellijkeTitelsTitel_Data{} },
		SliceFactory:           func() any { return &[]AdellijkeTitelsTitel_Data{} },
		Tabelnaam:              "adellijketitelstitel_data",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &AdellijkeTitelsTitel_Data{} },
		DBSliceFactory:         func() any { return &[]AdellijkeTitelsTitel_Data{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "AdellijkeTitelsTitel",
	}
	MetaRegistry["Referentielijst_Aanvang"] = TypeMeta{
		Typenaam:               "Referentielijst_Aanvang",
		Klassenaam:             "Aanvang",
		Description:            "Aanvangsdatum van Referentielijst.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeAanvang,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijst_aanvang",
		Padnaam:                "referentielijst_aanvang",
		Meervoud:               "referentielijst_aanvang",
		Factory:                func() Representatie { return &Referentielijst_Aanvang{} },
		SliceFactory:           func() any { return &[]Referentielijst_Aanvang{} },
		Tabelnaam:              "referentielijst_aanvang",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Referentielijst_Aanvang{} },
		DBSliceFactory:         func() any { return &[]Referentielijst_Aanvang{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijst",
	}
	MetaRegistry["Referentielijst_Einde"] = TypeMeta{
		Typenaam:               "Referentielijst_Einde",
		Klassenaam:             "Einde",
		Description:            "Einddatum van Referentielijst.",
		Metatype:               MetatypeGegevenselement,
		GESubtype:              GESubtypeEinde,
		Kleur:                  "#fef3c7",
		Veldnaam:               "referentielijst_einde",
		Padnaam:                "referentielijst_einde",
		Meervoud:               "referentielijst_einde",
		Factory:                func() Representatie { return &Referentielijst_Einde{} },
		SliceFactory:           func() any { return &[]Referentielijst_Einde{} },
		Tabelnaam:              "referentielijst_einde",
		IDKolom:                "versie",
		DBFactory:              func() Representatie { return &Referentielijst_Einde{} },
		DBSliceFactory:         func() any { return &[]Referentielijst_Einde{} },
		HeeftPFK:               true,
		RelatieveAutoincrement: true,
		EntiteitIDKolom:        "referentielijst_id",
		Momentvoorkomen:        Enkelvoudig,
		BovenliggendTypenaam:   "Referentielijst",
	}
}
