// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Change struct {
	ID                 string        `json:"id"`
	ChangeType         string        `json:"changeType"`
	RegistrationID     string        `json:"registrationId"`
	RepresentationName string        `json:"representationName"`
	RepresentationID   string        `json:"representationId"`
	Timestamp          string        `json:"timestamp"`
	Registration       *Registration `json:"registration"`
}

type CreateDataElementAUInput struct {
	AID string `json:"aId"`
	Aaa string `json:"aaa"`
	Bbb string `json:"bbb"`
}

type CreateDataElementAVInput struct {
	AID string `json:"aId"`
	Ccc string `json:"ccc"`
}

type CreateDataElementBXInput struct {
	BID string `json:"bId"`
	Fff string `json:"fff"`
	Ggg string `json:"ggg"`
}

type CreateDataElementBYInput struct {
	BID string `json:"bId"`
	Hhh string `json:"hhh"`
}

type CreateEntityAInput struct {
	ID string `json:"id"`
}

type CreateEntityBInput struct {
	ID string `json:"id"`
}

type CreateRelationABInput struct {
	AID string `json:"aId"`
	BID string `json:"bId"`
}

type CreateTaskInput struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	DueDate     string `json:"dueDate"`
	Status      string `json:"status"`
}

type DataElementAu struct {
	RelID string `json:"relId"`
	AID   string `json:"aId"`
	Aaa   string `json:"aaa"`
	Bbb   string `json:"bbb"`
}

type DataElementAv struct {
	RelID string `json:"relId"`
	AID   string `json:"aId"`
	Ccc   string `json:"ccc"`
}

type DataElementBx struct {
	RelID string `json:"relId"`
	BID   string `json:"bId"`
	Fff   string `json:"fff"`
	Ggg   string `json:"ggg"`
}

type DataElementBy struct {
	RelID string `json:"relId"`
	BID   string `json:"bId"`
	Hhh   string `json:"hhh"`
}

type EntityA struct {
	ID             string           `json:"id"`
	Opvoer         *string          `json:"opvoer,omitempty"`
	Afvoer         *string          `json:"afvoer,omitempty"`
	DataElementAu  *DataElementAu   `json:"dataElementAU,omitempty"`
	DataElementsAv []*DataElementAv `json:"dataElementsAV"`
	Relations      []*RelationAb    `json:"relations"`
}

type EntityB struct {
	ID            string         `json:"id"`
	Opvoer        *string        `json:"opvoer,omitempty"`
	Afvoer        *string        `json:"afvoer,omitempty"`
	DataElementBx *DataElementBx `json:"dataElementBX,omitempty"`
	DataElementBy *DataElementBy `json:"dataElementBY,omitempty"`
	Relations     []*RelationAb  `json:"relations"`
}

type Mutation struct {
}

type Query struct {
}

type Registration struct {
	ID                     string    `json:"id"`
	RegistrationType       string    `json:"registrationType"`
	Timestamp              string    `json:"timestamp"`
	Remark                 *string   `json:"remark,omitempty"`
	CorrectsRegistrationID *string   `json:"correctsRegistrationId,omitempty"`
	UndoesRegistrationID   *string   `json:"undoesRegistrationId,omitempty"`
	Changes                []*Change `json:"changes"`
}

type RelationAb struct {
	ID      string   `json:"id"`
	AID     string   `json:"aId"`
	BID     string   `json:"bId"`
	EntityA *EntityA `json:"entityA"`
	EntityB *EntityB `json:"entityB"`
}

type Task struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	DueDate     string `json:"dueDate"`
	Status      string `json:"status"`
}

type UpdateDataElementAUInput struct {
	Aaa *string `json:"aaa,omitempty"`
	Bbb *string `json:"bbb,omitempty"`
}

type UpdateEntityAInput struct {
	Opvoer *string `json:"opvoer,omitempty"`
	Afvoer *string `json:"afvoer,omitempty"`
}

type UpdateEntityBInput struct {
	Opvoer *string `json:"opvoer,omitempty"`
	Afvoer *string `json:"afvoer,omitempty"`
}

type UpdateTaskInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	DueDate     *string `json:"dueDate,omitempty"`
	Status      *string `json:"status,omitempty"`
}
